/*
 * Copyright (c) 2021 Eclipse Foundation and/or its affiliates. All rights reserved.
 * Copyright (c) 2021 Contributors to the Eclipse Foundation
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

package org.glassfish.tests.utils.junit;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * A set of resource paths with HK2 "inhabitant files" processed by HK2.
 * <p>
 * The "META-INF/hk2-locator/default" is automatically generated by the hk2-inhabitant-generator
 * even for tests and {@link HK2JUnit5Extension} automatically honors it, this mechanism can
 * be disabled by using this annotation with an empty {@link #value()}.
 * <p>
 * Note: This annotation is ignored when processing the file provided by the {@link DomainXml}
 * annotation.
 *
 * @author David Matejcek
 */
@Documented
@Inherited
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface LocatorFiles {

    /**
     * @return set of resource paths with HK2 "inhabitant files".
     */
    String[] value();
}
