type=page
status=published
title=change-master-broker
next=change-master-password.html
prev=change-admin-password.html
~~~~~~

= change-master-broker

[[change-master-broker-1]][[GSRFM00005]][[change-master-broker]]

== change-master-broker

Changes the master broker in a Message Queue cluster providing JMS
services for a {productName} cluster.

=== Synopsis

[source]
----
asadmin [asadmin-options] change-master-broker [--help]
clustered-instance-name
----

=== Description

The `change-master-broker` subcommand changes the master broker in a
Message Queue cluster that is the JMS provider for a {productName}
cluster. By default, the master broker is the one associated with the
first instance configured in the {productName} cluster.

This subcommand is supported in remote mode only. Remote `asadmin`
subcommands require a running domain administration server (DAS).

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

clustered-instance-name::
  The name of the server instance whose Message Queue broker is to
  become the master broker of the Message Queue cluster. This server
  instance must be an instance in a {productName} cluster.

=== Examples

[[GSRFM449]][[sthref58]]

==== Example 1   Changing the master broker

The following subcommand changes the Message Queue master broker to the
one for the `clustinst3` clustered instance.

[source]
----
asadmin> change-master-broker clustinst3
Command change-master-broker executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]


