type=page
status=published
title=create-node-config
next=create-node-ssh.html
prev=create-network-listener.html
~~~~~~

= create-node-config

[[create-node-config]]

== create-node-config

Creates a node that is not enabled for remote communication

=== Synopsis

[source]
----
asadmin [asadmin-options] create-node-config [--help]
[--nodehost node-host]
[--installdir as-install-parent] [--nodedir node-dir] node-name
----

=== Description

The `create-node-config` subcommand creates a node that is not enabled
for remote communication. The `create-node-config` subcommand does not
require the secure shell (SSH) to be configured to create the node.

A node represents a host on which the {productName} software is
installed. A node must exist for every host on which {productName}
instances reside.


[NOTE]
====
To represent the host where the DAS is running, {productName}
provides the predefined node ``localhost-``domain. The predefined node
``localhost-``domain is not enabled for remote communication.
====


All administration of instances on a node that is not enabled for remote
communication must be performed on the host that the node represents.
The domain administration server (DAS) on a remote host cannot contact
the node. To administer instances on a node that represents a host that
is remote from the DAS, you must use the following subcommands:

* xref:create-local-instance.adoc#create-local-instance[`create-local-instance`(1)]
* xref:delete-local-instance.adoc#delete-local-instance[`delete-local-instance`(1)]
* xref:start-local-instance.adoc#start-local-instance[`start-local-instance`(1)]

However, you may use
xref:stop-local-instance.adoc#stop-local-instance[`stop-local-instance`(1)]
or xref:stop-instance.adoc#stop-instance[`stop-instance`(1)] to stop
the instances.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--nodehost`::
  The name of the host that the node represents. If this option is
  omitted, no host is specified for the node.
`--installdir`::
  The full path to the parent of the base installation directory of the
  {productName} software on the host, for example,
  `/export/glassfish8/`. If this option is omitted, no parent of the
  base installation directory of the {productName} software is
  specified for the node.
`--nodedir`::
  The path to the directory that is to contain {productName}
  instances that are created on the node. If a relative path is
  specified, the path is relative to the as-install directory. If this
  option is omitted, no directory for instances is specified for the
  node.

=== Operands

node-name::
  The name of the node. +
  The name must meet the following requirements:

  * The name may contain only ASCII characters.
  * The name must start with a letter, a number, or an underscore.
  * The name may contain only the following characters:
  ** Lowercase letters
  ** Uppercase letters
  ** Numbers
  ** Hyphen
  ** Period
  ** Underscore
  * The name must be unique in the domain and must not be the name of
  another node, a cluster, a named configuration, or a {productName}
  instance.
  * The name must not be `domain`, `server`, or any other keyword that
  is reserved by {productName}.

=== Examples

==== Example 1   Creating a Node That Is Not Enabled for Remote Communication

This example creates the node `sj03` for host `sj03.example.com`. The
node is not enabled for remote communication.

[source]
----
asadmin> create-node-config --nodehost sj03.example.com sj03

Command create-node-config executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-local-instance.adoc#create-local-instance[`create-local-instance`(1)],
xref:create-node-ssh.adoc#create-node-ssh[`create-node-ssh`(1)],
xref:delete-local-instance.adoc#delete-local-instance[`delete-local-instance`(1)],
xref:delete-node-config.adoc#delete-node-config[`delete-node-config`(1)],
xref:install-node.adoc#install-node[`install-node`(1)],
xref:install-node-ssh.adoc#install-node-ssh[`install-node-ssh`(1)],
xref:list-nodes.adoc#list-nodes[`list-nodes`(1)],
xref:start-local-instance.adoc#start-local-instance[`start-local-instance`(1)],
xref:stop-instance.adoc#stop-instance[`stop-instance`(1)],
xref:stop-local-instance.adoc#stop-local-instance[`stop-local-instance`(1)],
xref:uninstall-node.adoc#uninstall-node[`uninstall-node`(1)],
xref:uninstall-node-ssh.adoc#uninstall-node-ssh[`uninstall-node-ssh`(1)],
xref:update-node-config.adoc#update-node-config[`update-node-config`(1)],
xref:update-node-ssh.adoc#update-node-ssh[`update-node-ssh`(1)]


