type=page
status=published
title=create-admin-object
next=create-application-ref.html
prev=copy-config.html
~~~~~~

= create-admin-object

[[create-admin-object]]

== create-admin-object

Adds the administered object with the specified JNDI name for a resource adapter

=== Synopsis

[source]
----
asadmin [asadmin-options] create-admin-object [--help]
[--target target]
--restype restype
[--classname classname]
--raname raname
[--enabled={true|false}]
[--description description]
[--property name=value[:name=value]*]
jndi_name
----

=== Description

The `create-admin-object` subcommand creates the administered object
with the specified JNDI name and the interface definition for a resource adapter.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target on which you are creating the administered
  object. Valid values are as follows:

  `server`;;
    Creates the administered object for the default server instance
    `server` and is the default value.
  configuration_name;;
    Creates the administered object for the named configuration.
  cluster_name;;
    Creates the administered object for every server instance in the
    cluster.
  instance_name;;
    Creates the administered object for a particular server instance.

+
[NOTE]
====
The resource is always created for the domain as a whole, but the
`resource-ref` for the resource is only created for the specified
`--target`. This means that although the resource is defined at the
domain level, it is only available at the specified target level. Use
the `create-resource-ref` subcommand to refer to the resource in
multiple targets if needed.
====

`--restype`::
  Specifies the interface definition for the administered object. The
  resource type must be an interface definition that is specified in the
  `ra.xml` file of the resource adapter.
`--classname`::
  Specifies the class name of the administered object. Required if
  multiple administered objects use the same interface definition.
`--raname`::
  Specifies the name of the resource adapter associated with this
  administered object.
`--enabled`::
  Specifies if this object is enabled. Default is true.
`--description`::
  Text string describing the administered object.
`--property`::
  Description of the name/values pairs for configuring the resource.
  Dependent on the resource adapter. For JMS properties, see
  link:create-jms-resource.html#create-jms-resource[`create-jms-resource`(1)]
  for JMS destination resources.

=== Operands

jndi_name::
  JNDI name of the administered object to be created.

=== Examples

[[sthref120]]

==== Example 1   Creating an Administered Object

In this example, `jmsra` is a system resource adapter with the admin
object interfaces, `jakarta.jms.Queue` and `jakarta.jms.Topic`.

[source]
----
asadmin> create-admin-object --restype jakarta.jms.Queue
--raname jmsra --description "sample administered object"
--property Name=sample_jmsqueue jms/samplequeue
Command create-admin-object executed successfully
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-resource-ref.html#create-resource-ref[`create-resource-ref`(1)],
link:delete-admin-object.html#delete-admin-object[`delete-admin-object`(1)],
link:list-admin-objects.html#list-admin-objects[`list-admin-objects`(1)]


