type=page
status=published
title=delete-audit-module
next=delete-auth-realm.html
prev=delete-application-ref.html
~~~~~~

= delete-audit-module

[[delete-audit-module-1]][[GSRFM00065]][[delete-audit-module]]

== delete-audit-module

Removes the named audit-module

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-audit-module [--help]
[--target target]
audit_module_name
----

=== Description

This subcommand removes the named audit module. This subcommand is
supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target on which you are deleting the audit module. Valid
  values are as follows:

  `server`;;
    Deletes the audit module for the default server instance `server`
    and is the default value.
  configuration_name;;
    Deletes the audit module for the named configuration.
  cluster_name;;
    Deletes the audit module for every server instance in the cluster.
  instance_name;;
    Deletes the audit module for a particular server instance.

=== Operands

audit_module_name::
  The name of the audit module to be deleted.

=== Examples

[[GSRFM532]][[sthref598]]

==== Example 1   Deleting an audit module

[source]
----
asadmin> delete-audit-module sampleAuditModule
Command delete-audit-module executed successfully
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-audit-module.html#create-audit-module[`create-audit-module`(1)],
link:list-audit-modules.html#list-audit-modules[`list-audit-modules`(1)]


