type=page
status=published
title=delete-instance
next=delete-jacc-provider.html
prev=delete-iiop-listener.html
~~~~~~

= delete-instance

[[delete-instance]]

== delete-instance

Deletes a {productName} instance

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-instance [--help]
instance-name
----

=== Description

The `delete-instance` subcommand deletes a {productName} instance.
This subcommand requires the secure shell (SSH) to be configured on the host where
the domain administration server (DAS) is running and on the host that
is represented by the node where the instance resides.

[NOTE]
====
SSH is not required if the instance resides on a node of type
`CONFIG` that represents the local host. A node of type `CONFIG` is not
enabled for remote communication over SSH.
====

You may run this subcommand from any host that can contact the DAS.

The subcommand can delete any {productName} instance, regardless of
how the instance was created. For example, this subcommand can delete an
instance that was created by using the
xref:create-local-instance.adoc#create-local-instance[`create-local-instance`(1)]
subcommand.

The instance that is being deleted must not be running. Otherwise, an
error occurs.

The subcommand deletes an instance by performing the following actions:

* Removing the instance from the configuration of the domain
  administration server (DAS)
* Deleting the instance's files from file system

If the instance that is being deleted is the only instance that is using
the node directory, that directory is also removed.

If a standalone instance is deleted, the instance's standalone
configuration is also deleted. A standalone instance refers to a
configuration that is named instance-name`-config` to which no other
clusters or unclustered instances refer.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

instance-name::
  The name of the instance to delete.

=== Examples

[[sthref758]]

==== Example 1   Deleting a {productName} Instance

This example deletes the {productName} instance `pmdsainst`.

[source]
----
asadmin> delete-instance pmdsainst

Command delete-instance executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-instance.adoc#create-instance[`create-instance`(1)],
xref:create-local-instance.adoc#create-local-instance[`create-local-instance`(1)],
xref:delete-local-instance.adoc#delete-local-instance[`delete-local-instance`(1)],
xref:setup-ssh.adoc#setup-ssh[`setup-ssh`(1)],
xref:start-instance.adoc#start-instance[`start-instance`(1)],
xref:start-local-instance.adoc#start-local-instance[`start-local-instance`(1)],
xref:stop-instance.adoc#stop-instance[`stop-instance`(1)],
xref:stop-local-instance.adoc#stop-local-instance[`stop-local-instance`(1)]


