type=page
status=published
title=delete-connector-resource
next=delete-connector-security-map.html
prev=delete-connector-connection-pool.html
~~~~~~

= delete-connector-resource

[[delete-connector-resource]]

== delete-connector-resource

Removes the connector resource with the specified JNDI name

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-connector-resource [--help]
[--target target] jndi_name
----

=== Description

The `delete-connector-resource` subcommand removes the connector
resource with the specified JNDI name.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target from which you want to remove the
  connector resource. Valid targets are:
+
[NOTE]
====
Resources are always created for a domain as a whole but are only
active for targets for which a `<resource-ref>` has been created using
the `--target` option when the resource was created. This means that
deleting a resource only deletes the `<resource-ref>` element for the
specified `--target`, and does not delete the resource from the domain
as a whole unless `domain` is specified as the `--target` for the
deletion.
====

  `server`;;
    Deletes the connector resource from the default server instance.
    This is the default value.
  `domain`;;
    Deletes the connector resource from the domain.
  cluster_name;;
    Deletes the connector resource from every server instance in the
    cluster.
  instance_name;;
    Deletes the connector resource from a specified server instance.

=== Operands

jndi_name::
  The JNDI name of this connector resource.

=== Examples

[[sthref638]]

==== Example 1   Deleting a Connector Resource

This example deletes a connector resource named `jms/qConnFactory`.

[source]
----
asadmin> delete-connector-resource jms/qConnFactory
Command delete-connector-resource executed successfully
----

[[sthref639]]

==== Example 2   Using the delete-connector-resource subcommand

This example shows the usage of this subcommand.

[source]
----
asadmin> delete-connector-resource jms/qConnFactory
Command delete-connector-resource executed successfully
----

Where `jms/qConnFactory` is the connector resource that is removed.

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-connector-resource.adoc#create-connector-resource[`create-connector-resource`(1)],
xref:list-connector-resources.adoc#list-connector-resources[`list-connector-resources`(1)]


