type=page
status=published
title=delete-connector-security-map
next=delete-connector-work-security-map.html
prev=delete-connector-resource.html
~~~~~~

= delete-connector-security-map

[[delete-connector-security-map]]

== delete-connector-security-map

Deletes a security map for the specified connector connection pool

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-connector-security-map [--help]
--poolname connector_connection_pool_name [--target target] mapname
----

=== Description

The `delete-connector-security-map` subcommand deletes a security map
for the specified connector connection pool.

For this subcommand to succeed, you must have first created a connector
connection pool using the `create-connector-connection-pool` subcommand.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--poolname`::
  Specifies the name of the connector connection pool to which the
  security map that is to be deleted belongs.
`--target`::
  Do not specify this option. This option is retained for compatibility
  with earlier releases. If you specify this option, a syntax error does
  not occur. Instead, the subcommand runs successfully and displays a
  warning message that the option is ignored.

=== Operands

mapname::
  Name of the security map to be deleted.

=== Examples

[[sthref647]]

==== Example 1   Deleting a Connector Security Map

This example deletes `securityMap1` for the existing connection pool
named `connector-pool1`.

[source]
----
asadmin> delete-connector-security-map
--poolname connector-pool1 securityMap1
Command delete-connector-security-map executed successfully
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-connector-security-map.adoc#create-connector-security-map[`create-connector-security-map`(1)],
xref:list-connector-security-maps.adoc#list-connector-security-maps[`list-connector-security-maps`(1)],
xref:update-connector-security-map.adoc#update-connector-security-map[`update-connector-security-map`(1)]


