type=page
status=published
title=delete-system-property
next=delete-threadpool.html
prev=delete-ssl.html
~~~~~~

= delete-system-property

[[delete-system-property]]

== delete-system-property

Removes a system property of the domain, configuration, cluster, or
server instance, one at a time

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-system-property [--help]
[--target target_name ]
[property_name]
----

=== Description

The `delete-system-property` subcommand deletes a system property of a
domain, configuration, cluster, or server instance. Make sure that the
system property is not referenced elsewhere in the configuration before
deleting it.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target on which you are deleting the system
  properties. The valid targets for this subcommand are instance,
  cluster, configuration, domain, and server. Server is the default option.

=== Operands

property_name::
  The name of the system property to remove.

=== Examples

[[sthref988]]

==== Example 1   Deleting a System Property

This example deletes the system property named `http-listener-port`.

[source]
----
asadmin> delete-system-property http-listener-port
Command delete-system-property executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-system-properties.html#create-system-properties[`create-system-properties`(1)],
link:list-system-properties.html#list-system-properties[`list-system-properties`(1)]


