type=page
status=published
title=delete-password-alias
next=delete-profiler.html
prev=delete-node-ssh.html
~~~~~~

= delete-password-alias

[[delete-password-alias-1]][[GSRFM00101]][[delete-password-alias]]

== delete-password-alias

Deletes a password alias

[[sthref922]]

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-password-alias [--help]
aliasname
----

[[sthref923]]

=== Description

This subcommand deletes a password alias.

[[sthref924]]

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the link:asadmin.html#asadmin-1m[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[sthref925]]

=== Operands

aliasname::
  This is the name of the substitute password as it appears in
  `domain.xml`.

[[sthref926]]

=== Examples

[[GSRFM572]][[sthref927]]

==== Example 1   Deleting a Password Alias

[source]
----
asadmin>delete-password-alias
jmspassword-alias
----

Command delete-password-alias executed successfully

[[sthref928]]

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

[[sthref929]]

=== See Also

link:asadmin.html#asadmin-1m[`asadmin`(1M)]

link:create-password-alias.html#create-password-alias-1[`create-password-alias`(1)],
link:list-password-aliases.html#list-password-aliases-1[`list-password-aliases`(1)],
link:update-password-alias.html#update-password-alias-1[`update-password-alias`(1)]


