type=page
status=published
title=delete-iiop-listener
next=delete-instance.html
prev=delete-http-redirect.html
~~~~~~

= delete-iiop-listener

[[delete-iiop-listener-1]][[GSRFM00084]][[delete-iiop-listener]]

== delete-iiop-listener

Removes an IIOP listener

=== Synopsis

[source]
----
delete-iiop-listener [--help] [--target target] listener_id
----

=== Description

The `delete-iiop-listener` subcommand removes the specified IIOP
listener. This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target from which you are deleting the IIOP listener.
  Valid values are

  `server`;;
    Deletes the listener from the default server instance `server` and
    is the default value.
  configuration_name;;
    Deletes the listener from the named configuration.
  cluster_name;;
    Deletes the listener from every server instance in the cluster.
  instance_name;;
    Deletes the listener from a particular server instance.

=== Operands

listener_id::
  The unique identifier for the IIOP listener to be deleted.

=== Examples

[[GSRFM552]][[sthref750]]

==== Example 1   Deleting an IIOP Listener

The following command deletes the IIOP listener named
`sample_iiop_listener`:

[source]
----
asadmin> delete-iiop-listener sample_iiop_listener
Command delete-iiop-listener executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-iiop-listener.html#create-iiop-listener[`create-iiop-listener`(1)],
link:list-iiop-listeners.html#list-iiop-listeners[`list-iiop-listeners`(1)]


