type=page
status=published
title=delete-jdbc-connection-pool
next=delete-jdbc-resource.html
prev=delete-javamail-resource.html
~~~~~~

= delete-jdbc-connection-pool

[[delete-jdbc-connection-pool-1]][[GSRFM00088]][[delete-jdbc-connection-pool]]

== delete-jdbc-connection-pool

Removes the specified JDBC connection pool

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-jdbc-connection-pool [--help]
[--cascade={false|true}]
[--target target]
jdbc_connection_pool_id
----

=== Description

The `delete-jdbc-connection-pool` subcommand deletes a JDBC connection
pool. Before running this subcommand, all associations to the JDBC
connection pool must be removed.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--cascade`::
  If the option is set to true, all the JDBC resources associated with
  the pool, apart from the pool itself, are deleted. When set to false,
  the deletion of pool fails if any resources are associated with the
  pool. Resources must be deleted explicitly or the option must be set
  to true. The default value is false.
`--target`::
  Do not specify this option. This option is retained for compatibility
  with earlier releases. If you specify this option, a syntax error does
  not occur. Instead, the subcommand runs successfully and displays a
  warning message that the option is ignored.

=== Operands

jdbc_connection_pool_id::
  The name of the JDBC resource to be removed.

=== Examples

[[GSRFM556]][[sthref782]]

==== Example 1   Deleting a JDBC Connection Pool

This example deletes the `sample_derby_pool` JDBC connection pool.

[source]
----
asadmin> delete-jdbc-connection-pool --cascade=false sample_derby_pool
Command delete-jdbc-connection-pool executed correctly.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-jdbc-connection-pool.html#create-jdbc-connection-pool[`create-jdbc-connection-pool`(1)],link:list-jdbc-connection-pools.html#list-jdbc-connection-pools[`list-jdbc-connection-pools`(1)]


