type=page
status=published
title=delete-protocol-finder
next=delete-resource-adapter-config.html
prev=delete-protocol-filter.html
~~~~~~

= delete-protocol-finder

[[delete-protocol-finder]]

== delete-protocol-finder

Removes a protocol finder

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-protocol-finder [--help]
--protocol protocol-name
[--target server]
protocol-finder-name
----

=== Description

The `delete-protocol-finder` subcommand removes the specified protocol
finder. This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--protocol-name`::
  The name of the associated protocol.
`--target`::
  Deletes the protocol finder only from the specified target. Valid
  values are as follows:

  `server`;;
    Deletes the protocol finder from the default server instance. This
    is the default value.
  configuration-name;;
    Deletes the protocol finder from the specified configuration.
  cluster-name;;
    Deletes the protocol finder from all server instances in the
    specified cluster.
  standalone-instance-name;;
    Deletes the protocol finder from the specified standalone server
    instance.

=== Operands

protocol-finder-name::
  The name of the protocol finder to be deleted.

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-protocol-finder.html#create-protocol-finder[`create-protocol-finder`(1)],
link:list-protocol-finders.html#list-protocol-finders[`list-protocol-finders`(1)]


