type=page
status=published
title=delete-javamail-resource
next=delete-jdbc-connection-pool.html
prev=delete-jacc-provider.html
~~~~~~

= delete-javamail-resource

[[delete-javamail-resource]]

== delete-javamail-resource

Removes a JavaMail session resource

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-javamail-resource [--help]
[--target target] jndi_name
----

=== Description

The `delete-javamail-resource` subcommand removes the specified JavaMail
session resource. Ensure that you remove all references to this resource
before running this subcommand.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target from which you are deleting the
  JavaMail session resource. Valid values are:

  `server`;;
    Deletes the resource from the default server instance. This is the
    default value.
  `domain`;;
    Deletes the resource from the domain.
  cluster_name;;
    Deletes the resource from every server instance in the cluster.
  instance_name;;
    Deletes the resource from a particular server instance.

=== Operands

jndi_name::
  The JNDI name of the JavaMail session resource to be deleted.

=== Examples

[[sthref774]]

==== Example 1   Deleting a JavaMail Resource

This example deletes the JavaMail session resource named
`mail/MyMailSession`.

[source]
----
asadmin> delete-javamail-resource mail/MyMailSession
Command delete-javamail-resource executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-javamail-resource.adoc#create-javamail-resource[`create-javamail-resource`(1)],
xref:list-javamail-resources.adoc#list-javamail-resources[`list-javamail-resources`(1)]


