type=page
status=published
title=delete-transport
next=delete-virtual-server.html
prev=delete-threadpool.html
~~~~~~

= delete-transport

[[delete-transport]]

== delete-transport

Removes a transport

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-transport [--help]
[--target target]
transport-name
----

=== Description

The `delete-transport` subcommand removes the specified transport. This
subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Deletes the transport only from the specified target. Valid values are
  as follows:

  `server`;;
    Deletes the transport from the default server instance. This is the
    default value.
  configuration-name;;
    Deletes the transport from the specified configuration.
  cluster-name;;
    Deletes the transport from all server instances in the specified
    cluster.
  standalone-instance-name;;
    Deletes the transport from the specified standalone server instance.

=== Operands

transport-name::
  The name of the transport to be deleted.

=== Examples

[[sthref1004]]

==== Example 1   Deleting a Transport

The following command deletes the transport named `http1-trans`:

[source]
----
asadmin> delete-transport http1-trans
Command delete-transport executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-transport.adoc#create-transport[`create-transport`(1)],
xref:list-transports.adoc#list-transports[`list-transports`(1)]


