type=page
status=published
title=delete-password-alias
next=delete-profiler.html
prev=delete-node-ssh.html
~~~~~~

= delete-password-alias

[[delete-password-alias-1]][[GSRFM00101]][[delete-password-alias]]

== delete-password-alias

Deletes a password alias

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-password-alias [--help]
aliasname
----

=== Description

This subcommand deletes a password alias.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

aliasname::
  This is the name of the substitute password as it appears in
  `domain.xml`.

=== Examples

[[GSRFM572]][[sthref927]]

==== Example 1   Deleting a Password Alias

[source]
----
asadmin>delete-password-alias
jmspassword-alias
----

Command delete-password-alias executed successfully

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-password-alias.html#create-password-alias[`create-password-alias`(1)],
link:list-password-aliases.html#list-password-aliases[`list-password-aliases`(1)],
link:update-password-alias.html#update-password-alias[`update-password-alias`(1)]


