type=page
status=published
title=delete-virtual-server
next=deploy.html
prev=delete-transport.html
~~~~~~

= delete-virtual-server

[[delete-virtual-server-1]][[GSRFM00113]][[delete-virtual-server]]

== delete-virtual-server

Removes a virtual server

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-virtual-server [--help]
[--target target] virtual-server-id
----

=== Description

The `delete-virtual-server` subcommand removes the virtual server with
the specified virtual server ID. This subcommand is supported in remote
mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Deletes the virtual server only from the specified target. Valid
  values are as follows:

  `server`;;
    Deletes the virtual server from the default server instance. This is
    the default value.
  configuration-name;;
    Deletes the virtual server from the specified configuration.
  cluster-name;;
    Deletes the virtual server from all server instances in the
    specified cluster.
  standalone-instance-name;;
    Deletes the virtual server from the specified standalone server
    instance.

=== Operands

virtual-server-id::
  The unique identifier for the virtual server to be deleted.

=== Examples

[[GSRFM583]][[sthref1012]]

==== Example 1   Deleting a Virtual Server

The following command deletes the virtual server named `sample_vs1`:

[source]
----
asadmin> delete-virtual-server sample_vs1
Command delete-virtual-server executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-virtual-server.html#create-virtual-server[`create-virtual-server`(1)],
link:list-virtual-servers.html#list-virtual-servers[`list-virtual-servers`(1)]


