type=page
status=published
title=delete-module-config
next=delete-network-listener.html
prev=delete-message-security-provider.html
~~~~~~

= delete-module-config

[[delete-module-config]]

== delete-module-config

Removes the configuration of a module from `domain.xml`

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-module-config [--help]
[--target target]
service_name
----

=== Description

The `delete-module-config` subcommand removes the configuration of a
module from `domain.xml` and causes the module to use the default
configuration included in the module.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target from which the configuration is to be deleted.
  Possible values are as follows:

  `server`;;
    Deletes the configuration from the default server instance. This is
    the default value.
  `domain`;;
    Deletes the configuration from the default domain.
  cluster-name;;
    Deletes the configuration from every server instance in the
    specified cluster.
  instance-name;;
    Deletes the configuration from the specified instance.

=== Operands

service_name::
  The name of the module for which configuration is to be removed.

=== Examples

[[sthref887]]

==== Example 1   Deleting a Default Configuration From domain.xml

This example deletes the configuration of the web container module from
`domain1` in `server-config` (the default configuration).

[source]
----
asadmin> delete-module-config web-container
Command delete-module-config executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-module-config.adoc#create-module-config[`create-module-config`(1)],
xref:get-active-module-config.adoc#get-active-module-config[`get-active-module-config`(1)]


