type=page
status=published
title=delete-http-lb
next=delete-http-lb-config.html
prev=delete-http-health-checker.html
~~~~~~

= delete-http-lb

[[delete-http-lb]]

== delete-http-lb

Deletes a load balancer

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-http-lb [--help]
load_balancer_name
----

=== Description

Use the `delete-http-lb` subcommand to delete a physical load balancer.

[NOTE]
====
This subcommand is only applicable to {productName}. This
subcommand is not applicable to {productName}.
====

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

load_balancer_name::
  The name of the load balancer to be deleted.

=== Examples

[[sthref712]]

==== Example 1   Deleting a Load Balancer Configuration

This example deletes the load balancer configuration named `mylb`.

[source]
----
asadmin> delete-http-lb mylb

Command delete-http-lb executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-http-lb.html#create-http-lb[`create-http-lb`(1)],
link:list-http-lbs.html#list-http-lbs[`list-http-lbs`(1)]


