type=page
status=published
title=disable-secure-admin-principal
next=enable.html
prev=disable-secure-admin-internal-user.html
~~~~~~

= disable-secure-admin-principal

[[disable-secure-admin-principal]]

== disable-secure-admin-principal

Disables the certificate for authorizing access in secure
administration.

=== Synopsis

[source]
----
asadmin [asadmin-options] disable-secure-admin-principal [--help]
--alias aliasname | DN
----

=== Description

The `disable-secure-admin-principal` subcommand disables the certificate
as being valid for authorizing access as part of secure administration.

You must specify either the `--alias` option, or the DN.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--alias`::
  The alias name of the certificate in the truststore. {productName}
  looks up the certificate in the truststore using that alias and, if
  found, disables the corresponding DN as being valid for secure
  administration. Because alias-name must be an alias associated with a
  certificate currently in the truststore, you may find it most useful
  for self-signed certificates.

=== Operands

DN::
  The distinguished name of the certificate, specified as a
  comma-separated list in quotes. For example,
  `"CN=system.amer.oracle.com,OU=GlassFish,O=Oracle Corporation,L=Santa Clara,ST=California,C=US"`
  .

=== Examples

[[sthref1092]]

==== Example 1   Disables trust of a DN for secure administration

The following example shows how to disable trust of a DN for authorizing
access in secure administration.

[source]
----
asadmin> disable-secure-admin-principal
"CN=system.amer.oracle.com,OU=GlassFish,
O=Oracle Corporation,L=Santa Clara,ST=California,C=US"

Command disable-secure-admin-principal executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:enable-secure-admin.adoc#enable-secure-admin[`enable-secure-admin`(1)],
xref:enable-secure-admin-principal.adoc#enable-secure-admin-principal[`enable-secure-admin-principal`(1)]


