type=page
status=published
title=disable-secure-admin-internal-user
next=disable-secure-admin-principal.html
prev=disable-secure-admin.html
~~~~~~

= disable-secure-admin-internal-user

[[disable-secure-admin-internal-user]]

== disable-secure-admin-internal-user

Instructs the {productName} DAS and instances to not use the
specified admin user to authenticate with each other and to authorize
admin operations.

=== Synopsis

[source]
----
asadmin [asadmin-options] disable-secure-admin-internal-user [--help]
admin-username
----

=== Description

The `disable-secure-admin-internal-user` subcommand disables secure
admin from using the username (instead of SSL certificates) to
authenticate the DAS and instances with each other and to authorize
admin operations.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

admin-username::
  The admin user name that {productName} should not use to
  authenticate the DAS and instances with each other and to authorize
  admin operations.

=== Examples

[[sthref1084]]

==== Example 1   Disabling a user name for secure admin

The following example disables secure admin from using username tester
to authenticate the DAS and instances with each other and to authorize
admin operations.

[source]
----
asadmin> disable-secure-admin-internal-user tester

Command disable-secure-admin-internal-user executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:enable-secure-admin.adoc#enable-secure-admin[`enable-secure-admin`(1)],
xref:enable-secure-admin-internal-user.adoc#enable-secure-admin-internal-user[`enable-secure-admin-internal-user`(1)]


