type=page
status=published
title=disable-secure-admin
next=disable-secure-admin-internal-user.html
prev=disable-monitoring.html
~~~~~~

= disable-secure-admin

[[disable-secure-admin-1]][[GSRFM00121]][[disable-secure-admin]]

== disable-secure-admin

Disables secure admin if it is already enabled.

=== Synopsis

[source]
----
asadmin [asadmin-options] disable-secure-admin [--help]
----

=== Description

The `disable-secure-admin` subcommand disables secure admin if it is
already enabled.

[NOTE]
====
You must restart any running servers in the domain after you enable or
disable secure admin. It is simpler to enable or disable secure admin
with only the DAS running, then restart the DAS, and then start any
other instances.
====

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Examples

[[GSRFM596]][[sthref1076]]

==== Example 1   Disabling `secure admin` for a domain

The following example shows how to disable `secure admin` for a domain.

[source]
----
asadmin> disable-secure-admin
server-config
default-config

Command disable-secure-admin executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:enable-secure-admin.html#enable-secure-admin-1[`enable-secure-admin`(1)]


