type=page
status=published
title=enable-http-lb-application
next=enable-http-lb-server.html
prev=enable.html
~~~~~~

= enable-http-lb-application

[[enable-http-lb-application]]

== enable-http-lb-application

Enables a previously-disabled application managed by a load balancer

=== Synopsis

[source]
----
asadmin [asadmin-options] enable-http-lb-application [--help]
--name application_name target
----

=== Description

The `enable-http-lb-application` subcommand enables load balancing for
applications deployed on a standalone instance or cluster. You can
enable load balancing for an application on all instances in a cluster,
or on a single standalone server instance. By default, load balancing is
enabled for applications.

[NOTE]
====
This subcommand is only applicable to {productName}. This
subcommand is not applicable to {productName}.
====

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--name`::
  The name of the application to be enabled.

=== Operands

target::
  This operand specifies on which server instance or cluster to enable
  the application. Valid values are:
+
  * cluster_name- The name of a target cluster.
  * instance_name- The name of a target server instance.

=== Examples

[[sthref1108]]

==== Example 1   Enabling Load Balancing for an Application

This example enables an application named `webapps-simple` to use load
balancing on a cluster named `mycluster`.

[source]
----
asadmin> enable-http-lb-application --name webapps-simple mycluster

Command enable-http-lb-application executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:disable-http-lb-application.adoc#disable-http-lb-application[`disable-http-lb-application`(1)]


