type=page
status=published
title=enable-http-lb-server
next=enable-monitoring.html
prev=enable-http-lb-application.html
~~~~~~

= enable-http-lb-server

[[enable-http-lb-server]]

== enable-http-lb-server

Enables a previously disabled sever or cluster managed by a load
balancer

=== Synopsis

[source]
----
asadmin [asadmin-options] enable-http-lb-server [--help]
target
----

=== Description

The `enable-http-lb-server` subcommand enables a standalone server
instance or cluster for load balancing. By default, load balancing is
enabled for instances and clusters.

[NOTE]
====
This subcommand is only applicable to {productName}. This
subcommand is not applicable to {productName}.
====

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

target::
  This operand specifies which server instances and clusters to enable.
  Valid values are:

  * cluster_name- The name of a target cluster.
  * instance_name- The name of a target server instance.

=== Examples

[[sthref1116]]

==== Example 1   Enabling a Cluster for Load Balancing

This example enables load balancing for a cluster named `mycluster`.

[source]
----
asadmin> enable-http-lb-server mycluster

Command enable-http-lb-server executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-http-lb-ref.html#create-http-lb-ref[`create-http-lb-ref`(1)],
link:disable-http-lb-server.html#disable-http-lb-server[`disable-http-lb-server`(1)]


