type=page
status=published
title=freeze-transaction-service
next=generate-jvm-report.html
prev=flush-jmsdest.html
~~~~~~

= freeze-transaction-service

[[freeze-transaction-service-1]][[GSRFM00137]][[freeze-transaction-service]]

== freeze-transaction-service

Freezes the transaction subsystem

=== Synopsis

[source]
----
asadmin [asadmin-options] freeze-transaction-service [--help]
[--target target]
----

=== Description

The `freeze-transaction-service` subcommand freezes the transaction
subsystem, preventing the transaction manager from starting, completing,
or changing the state of all in-flight transactions. Invoke this command
before rolling back any in-flight transactions. Invoking this subcommand
on an already frozen transaction subsystem has no effect. Restarting the
server unfreezes the transaction subsystem. This subcommand is supported
in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target on which you are freezing the
  transaction service. Valid values are:

  `server`;;
    Freezes the transaction service for the default server instance
    `server` and is the default value.
  configuration_name;;
    Freezes the transaction service for all server instances that use
    the named configuration.
  cluster_name;;
    Freezes the transaction service for every server instance in the
    cluster.
  instance_name;;
    Freezes the transaction service for a particular server instance.

=== Examples

[[GSRFM616]][[sthref1197]]

==== Example 1   Using freeze-transaction-service

[source]
----
% asadmin freeze-transaction-service
Command freeze-transaction-service executed successfully
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:recover-transactions.html#recover-transactions-1[`recover-transactions`(1)],
link:rollback-transaction.html#rollback-transaction-1[`rollback-transaction`(1)],
link:unfreeze-transaction-service.html#unfreeze-transaction-service-1[`unfreeze-transaction-service`(1)]

link:administration-guide/transactions.html#GSADG00022[Administering Transactions]
in {productName} Administration Guide

https://eclipse-ee4j.github.io/jakartaee-tutorial/#transactions[Transactions]
in The Jakarta EE Tutorial


