type=page
status=published
title=list-protocol-finders
next=list-protocols.html
prev=list-protocol-filters.html
~~~~~~

= list-protocol-finders

[[list-protocol-finders]]

== list-protocol-finders

Lists the existing protocol finders

=== Synopsis

[source]
----
asadmin [asadmin-options] list-protocol-finders [--help]
[--target server]
protocol-name
----

=== Description

The `list-protocol-finders` subcommand lists the existing protocol
finders. This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
target::
  Restricts the listing to protocol finders for a specified target.
  Valid values are as follows:

  `server`;;
    Lists the protocol finders for the default server instance. This is
    the default value.
  configuration-name;;
    Lists the protocol finders for the specified configuration.
  cluster-name;;
    Lists the protocol finders for all server instances in the specified
    cluster.
  instance-name;;
    Lists the protocol finders for the specified server instance.

=== Operands

protocol-name::
  The name of the protocol for which to list protocol finders.

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-protocol-finder.adoc#create-protocol-finder[`create-protocol-finder`(1)],
xref:delete-protocol-finder.adoc#delete-protocol-finder[`delete-protocol-finder`(1)]


