type=page
status=published
title=list-iiop-listeners
next=list-instances.html
prev=list-http-listeners.html
~~~~~~

= list-iiop-listeners

[[list-iiop-listeners]]

== list-iiop-listeners

Lists the existing IIOP listeners

=== Synopsis

[source]
----
asadmin [asadmin-options] list-iiop-listeners [--help]
[target]
----

=== Description

The `list-iiop-listeners` subcommand lists the existing IIOP listeners.
This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

target::
  This operand specifies the target for which the IIOP listeners are to
  be listed. Valid values are:

  `server`;;
    Lists the listeners in the default server instance `server` and is
    the default value.
  configuration_name;;
    Lists the listeners in the specified configuration.
  cluster_name;;
    Lists the listeners in the specified cluster.
  instance_name;;
    Lists the listeners in a particular server instance.

=== Examples

[[sthref1514]]

==== Example 1   Using the list-iiop-listeners subcommand

The following command lists all the IIOP listeners for the server
instance:

[source]
----
asadmin> list-iiop-listeners
orb-listener-1
SSL
SSL_MUTUALAUTH
sample_iiop_listener
Command list-iiop-listeners executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-iiop-listener.html#create-iiop-listener[`create-iiop-listener`(1)],
link:delete-iiop-listener.html#delete-iiop-listener[`delete-iiop-listener`(1)]


