type=page
status=published
title=list-jacc-providers
next=list-javamail-resources.html
prev=list-instances.html
~~~~~~

= list-jacc-providers

[[list-jacc-providers]]

== list-jacc-providers

Enables administrators to list JACC providers defined for a domain

=== Synopsis

[source]
----
asadmin [asadmin-options] list-jacc-providers [--help]
[target]
----

=== Description

The `list-jacc-providers` subcommand enables administrators to list the
JACC providers defined for a domain. JACC providers are defined as
`jacc-provider` elements in the `security-service` element in the
domain's `domain.xml` file. JACC providers can be created using the
{productName} Admin Console or the `create-jacc-provider` subcommand.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

target::
  Specifies the target for which you want to list JACC providers. The
  following values are valid:

  `server`;;
    Lists the JACC providers on the default server instance. This is the
    default value.
  configuration_name;;
    Lists the JACC providers in the specified configuration.
  cluster_name;;
    Lists the JACC providers on all server instances in the specified
    cluster.
  instance_name;;
    Lists the JACC providers on a specified server instance.

=== Examples

[[sthref1533]]

==== Example 1   Listing JACC providers

The following example shows how to list JACC providers for the default domain.

[source]
----
asadmin> list-jacc-providers
default
simple
testJACC

Command list-jacc-providers executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-jacc-provider.html#create-jacc-provider[`create-jacc-provider`(1)],
link:delete-jacc-provider.html#delete-jacc-provider[`delete-jacc-provider`(1)]


