type=page
status=published
title=list-jdbc-connection-pools
next=list-jdbc-resources.html
prev=list-jacc-providers.html
~~~~~~

= list-jdbc-connection-pools

[[list-jdbc-connection-pools]]

== list-jdbc-connection-pools

Lists all JDBC connection pools

=== Synopsis

[source]
----
asadmin [asadmin-options] list-jdbc-connection-pools [--help]
----

=== Description

The `list-jdbc-connection-pools` subcommand lists the current JDBC
connection pools.

This subcommand is supported in the remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Examples

[[sthref1548]]

==== Example 1   Listing the JDBC Connection Pools

This example lists the existing JDBC connection pools.

[source]
----
asadmin> list-jdbc-connection-pools
sample_derby_pool
__TimerPool
Command list-jdbc-connection-pools executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-jdbc-connection-pool.adoc#create-jdbc-connection-pool[`create-jdbc-connection-pool`(1)],
xref:delete-jdbc-connection-pool.adoc#delete-jdbc-connection-pool[`delete-jdbc-connection-pool`(1)]


