type=page
status=published
title=list-password-aliases
next=list-persistence-types.html
prev=list-nodes-ssh.html
~~~~~~

= list-password-aliases

[[list-password-aliases]]

== list-password-aliases

Lists all password aliases

=== Synopsis

[source]
----
asadmin [asadmin-options] list-password-aliases [--help]
----

=== Description

This subcommand lists all of the password aliases.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Examples

[[sthref1740]]

==== Example 1   Listing all password aliases

[source]
----
asadmin> list-password-aliases
jmspassword-alias
Command list-password-aliases executed successfully
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-password-alias.html#create-password-alias[`create-password-alias`(1)],
link:delete-password-alias.html#delete-password-alias[`delete-password-alias`(1)],
link:update-password-alias.html#update-password-alias[`update-password-alias`(1)]


