type=page
status=published
title=list-jdbc-connection-pools
next=list-jdbc-resources.html
prev=list-javamail-resources.html
~~~~~~

= list-jdbc-connection-pools

[[list-jdbc-connection-pools-1]][[GSRFM00173]][[list-jdbc-connection-pools]]

== list-jdbc-connection-pools

Lists all JDBC connection pools

[[sthref1544]]

=== Synopsis

[source]
----
asadmin [asadmin-options] list-jdbc-connection-pools [--help]
----

[[sthref1545]]

=== Description

The `list-jdbc-connection-pools` subcommand lists the current JDBC
connection pools.

This subcommand is supported in the remote mode only.

[[sthref1546]]

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the link:asadmin.html#asadmin-1m[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[sthref1547]]

=== Examples

[[GSRFM670]][[sthref1548]]

==== Example 1   Listing the JDBC Connection Pools

This example lists the existing JDBC connection pools.

[source]
----
asadmin> list-jdbc-connection-pools
sample_derby_pool
__TimerPool
Command list-jdbc-connection-pools executed successfully.
----

[[sthref1549]]

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

[[sthref1550]]

=== See Also

link:asadmin.html#asadmin-1m[`asadmin`(1M)]

link:create-jdbc-connection-pool.html#create-jdbc-connection-pool-1[`create-jdbc-connection-pool`(1)],
link:delete-jdbc-connection-pool.html#delete-jdbc-connection-pool-1[`delete-jdbc-connection-pool`(1)]


