type=page
status=published
title=list-connector-work-security-maps
next=list-containers.html
prev=list-connector-security-maps.html
~~~~~~

= list-connector-work-security-maps

[[list-connector-work-security-maps]]

== list-connector-work-security-maps

Lists the work security maps belonging to the specified resource adapter

=== Synopsis

[source]
----
asadmin [asadmin-options] list-connector-work-security-maps [--help]
[--securitymap securitymap]
resource_adapter_name
----

=== Description

The `list-connector-work-security-maps` subcommand lists the work
security maps belonging to the specified resource adapter.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--securitymap`::
  Specifies the name of the security map contained within the resource
  adapter from which the identity and principals should be listed.

=== Operands

resource_adapter_name::
  The name of the resource adapter for which you want to list security
  maps.

=== Examples

[[sthref1435]]

==== Example 1   Listing Connector Work Security Maps

This example lists the current connector work security maps for the
resource adapter named `my_resource_adapter`.

[source]
----
asadmin> list-connector-work-security-maps my_resource_adapter
workSecurityMap1: EIS principal=eis-principal-2, mapped principal=server-principal-2
workSecurityMap1: EIS principal=eis-principal-1, mapped principal=server-principal-1
workSecurityMap2: EIS principal=eis-principal-2, mapped principal=server-principal-2
workSecurityMap2: EIS principal=eis-principal-1, mapped principal=server-principal-1
Command list-connector-work-security-maps executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-connector-work-security-map.adoc#create-connector-work-security-map[`create-connector-work-security-map`(1)],
xref:delete-connector-work-security-map.adoc#delete-connector-work-security-map[`delete-connector-work-security-map`(1)],
xref:update-connector-work-security-map.adoc#update-connector-work-security-map[`update-connector-work-security-map`(1)]


