type=page
status=published
title=list-jdbc-resources
next=list-jmsdest.html
prev=list-jdbc-connection-pools.html
~~~~~~

= list-jdbc-resources

[[list-jdbc-resources]]

== list-jdbc-resources

Lists all JDBC resources

=== Synopsis

[source]
----
asadmin [asadmin-options] list-jdbc-resources [--help]
[target target]
----

=== Description

The `list-jdbc-resources` subcommand displays a list of the existing
JDBC resources.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

`--target`::
  This operand specifies which JDBC resources you can list. Usage of
  this operand is optional. Valid values are:

  `server`;;
    Lists the JDBC resources in the current server and is the default.
  `domain`;;
    Lists the JDBC resources in the current domain.
  cluster_name;;
    Lists the JDBC resources in a cluster.
  instance_name;;
    Lists the JDBC resources for a particular instance.

=== Examples

[[sthref1556]]

==== Example 1   Listing the JDBC Resources

This example lists the current JDBC resources.

[source]
----
asadmin> list-jdbc-resources
jdbc/DerbyPool
Command list-jdbc-resources executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-jdbc-resource.adoc#create-jdbc-resource[`create-jdbc-resource`(1)],
xref:delete-jdbc-resource.adoc#delete-jdbc-resource[`delete-jdbc-resource`(1)]


