type=page
status=published
title=list-nodes-dcom
next=list-nodes-ssh.html
prev=list-nodes-config.html
~~~~~~

= list-nodes-dcom

[[list-nodes-dcom]]

== list-nodes-dcom

Lists all {productName} nodes that support communication over DCOM
in a domain

=== Synopsis

[source]
----
asadmin [asadmin-options] list-nodes-dcom [--help]
[--long={false|true}]
----

=== Description

The `list-nodes-dcom` subcommand lists all {productName} nodes that
support communication over the Distributed Component Object Model (DCOM)
remote protocol. The DCOM protocol is available only on Windows systems.

[NOTE]
====
To list all nodes in a domain regardless of the type of the node, run
the xref:list-nodes.adoc#list-nodes[`list-nodes`(1)] subcommand.
====

By default, the subcommand displays the following information for each
node that is listed:

* The name of the node
* The type of the node, which is `DCOM`
* The name of the host that the node represents

The `--long` option of the subcommand specifies whether the nodes are
listed in long format. In long format, the following additional
information about each node is displayed:

* The path to the parent of the base installation directory of
{productName} on the host that the node represents
* A comma-separated list of the names of the {productName} instances
that reside on the node

If the `--terse` option of the
xref:asadmin.adoc#asadmin[`asadmin`(1M)] utility is `true` and the
`--long` option of the subcommand is `false`, the subcommand lists only
the name of each node.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--long`::
`-l`::
  Specifies whether the nodes are listed in long format. +
  Possible values are as follows:

  `true`;;
    The nodes are listed in long format.
  `false`;;
    The nodes are listed in short format (default).

=== Examples

[[sthref1722]]

==== Example 1   Listing {productName} Nodes

This example displays the name, type, and host for all {productName}
nodes that support communication over DCOM in a domain.

[source]
----
asadmin> list-nodes-dcom
xkyd  DCOM  xkyd.example.com
wpmdl2  DCOM  wpmdl2.example.com
wpmdl1  DCOM  wpmdl1.example.com
Command list-nodes-dcom executed successfully.
----

[[sthref1723]]

==== Example 2   Listing Only the Names of {productName} Nodes

This example uses the `--terse` option of the `asadmin` utility to list
only the names of the {productName} nodes that support communication
over DCOM in a domain.

[source]
----
asadmin> list-nodes-dcom --terse=true
xkyd
wpmdl2
wpmdl1
----

[[sthref1724]]

==== Example 3   Listing {productName} Nodes in Long Format

This example lists the {productName} nodes that support
communication over DCOM in a domain in long format.

[source]
----
asadmin> list-nodes-dcom --long=true
NODE NAME    TYPE   NODE HOST            INSTALL DIRECTORY   REFERENCED BY
xkyd         DCOM   xkyd.example.com     C:\glassfish8
wpmdl2       DCOM   wpmdl2.example.com   C:\glassfish8       wdi2
wpmdl1       DCOM   wpmdl1.example.com   C:\glassfish8       wdi1
Command list-nodes-dcom executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-node-config.adoc#create-node-config[`create-node-config`(1)],
xref:create-node-dcom.adoc#create-node-dcom[`create-node-dcom`(1)],
xref:create-node-ssh.adoc#create-node-ssh[`create-node-ssh`(1)],
xref:delete-node-config.adoc#delete-node-config[`delete-node-config`(1)],
xref:delete-node-dcom.adoc#delete-node-dcom[`delete-node-dcom`(1)],
xref:delete-node-ssh.adoc#delete-node-ssh[`delete-node-ssh`(1)],
xref:list-nodes.adoc#list-nodes[`list-nodes`(1)],
xref:list-nodes-config.adoc#list-nodes-config[`list-nodes-config`(1)],
xref:#list-nodes-dcom[`list-nodes-dcom`(1)]


