type=page
status=published
title=list-timers
next=list-transports.html
prev=list-threadpools.html
~~~~~~

= list-timers

[[list-timers-1]][[GSRFM00205]][[list-timers]]

== list-timers

Lists all of the persistent timers owned by server instance(s)

=== Synopsis

[source]
----
asadmin [asadmin-options] list-timers [--help]
[target]
----

=== Description

The `list-timers` subcommand lists the persistent timers owned by a
specific server instance or a cluster of server instances. This command
is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

target::
  The target is either a standalone server instance or a cluster. If the
  target is the stand-alone instance, then the number of timers owned by
  the instance is listed. If the target is a cluster, then the number of
  timers owned by each instance in the cluster is listed. The default
  target is `server`, the default server instance.

=== Examples

[[GSRFM715]][[sthref1839]]

==== Example 1   Listing Current Timers in a Server Instance

This example lists persistent timers in a particular standalone server
instance. There is one currently active timer set.

[source]
----
asadmin> list-timers server
1

The list-timers command was executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:migrate-timers.html#migrate-timers-1[`migrate-timers`(1)]

https://eclipse-ee4j.github.io/jakartaee-tutorial/#using-the-timer-service[
Using the Timer Service] in The Jakarta EE Tutorial

"link:application-development-guide/ejb.html#GSDVG00146[EJB Timer Service]"
in {productName} Application Development Guide


