type=page
status=published
title=list-backups
next=list-batch-job-executions.html
prev=list-auth-realms.html
~~~~~~

= list-backups

[[list-backups]]

== list-backups

Lists all backups

=== Synopsis

[source]
----
asadmin [asadmin-options] list-backups [--help]
[--long[={false|true}]]
[--domaindir domain-root-dir]
[--backupdir backup-directory]
[--backupconfig backup-config-name]
[domain-name]
----

=== Description

The `list-backups` subcommand displays information about domain backups.

This subcommand is supported in local mode only in {productName}, and is support in local mode and remote mode in {productName}.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--long`::
`-l`::
  Displays detailed information about each backup. +
  The default value is `false`.
`--domaindir`::
  Specifies the domain root directory, the parent directory of the
  domain upon which the command will operate. +
  The default value is as-install``/domains``.
`--backupdir`::
  Specifies the directory under which backup files are stored. +
  The default value is as-install``/domains/``domain-dir``/backups``. If the
  domain is not in the default location, the location is
  domain-dir``/backups``.
`--backupconfig`::
  (Supported only in {productName}.) Restricts the listing of
  backup files in the backup directory to those for the specified domain
  backup configuration.

=== Operands

domain-name::
  Specifies the domain for which backups are listed. +
  This operand is optional if only one domain exists in the
  {productName} installation.

=== Examples

[[sthref1337]]

==== Example 1   Listing Domain Backups

This example provides detailed information about backups in the default domain.

[source]
----
asadmin> list-backups --long

Description               : domain1 backup created on 2021_12_20 by user dmatej
GlassFish Version         : Eclipse GlassFish  7.0.0  (build 2021-12-10T19:08:14+0100)
Backup User               : admin
Backup Date               : Mon Dec 20 19:24:17 CET 2021
Domain Name               : domain1
Backup Type               : full
Backup Config Name        :
Backup Filename (origin)  : /glassfish7/glassfish/domains/domain1/backups/domain1_2021_12_20_v00001.zip
Domain Directory          : /glassfish7/glassfish/domains/domain1

Description               : domain1 backup created on 2021_12_20 by user dmatej
GlassFish Version         : Eclipse GlassFish  7.0.0  (build 2021-12-10T19:08:14+0100)
Backup User               : admin
Backup Date               : Mon Dec 20 19:24:20 CET 2021
Domain Name               : domain1
Backup Type               : full
Backup Config Name        :
Backup Filename (origin)  : /glassfish7/glassfish/domains/domain1/backups/domain1_2021_12_20_v00002.zip
Domain Directory          : /glassfish7/glassfish/domains/domain1


Command list-backups executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:backup-domain.adoc#backup-domain[`backup-domain`(1)],
xref:restore-domain.adoc#restore-domain[`restore-domain`(1)]


