type=page
status=published
title=list-jobs
next=list-jvm-options.html
prev=list-jndi-resources.html
~~~~~~

= list-jobs

[[list-jobs-1]][[GSRFM867]][[list-jobs]]

== list-jobs

Lists information about subcommands that were started using
`asadmin --detach` or that contain progress information

=== Synopsis

[source]
----
asadmin [asadmin-options] list-jobs [--help]
[job_id]
----

=== Description

The `list-jobs` subcommand lists information about subcommands that were
started using the `asadmin` utility option `--detach` or that contain
progress information. The `--detach` option detaches long-running
subcommands and executes them in the background in detach mode.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

job_id::
  The ID of the job for which you want to list information.

=== Examples

[[GSRFM868]][[sthref1605]]

==== Example 1   Checking Job Status

This example provides information about subcommands that were started
using `asadmin --detach` or that contain progress information.

[source]
----
asadmin> list-jobs
JOB ID     COMMAND           STATE       EXIT CODE TIME OF COMPLETION
1          create-cluster    COMPLETED   SUCCESS   2013-02-15 16:16:16 PST
2          deploy            COMPLETED   FAILURE   2013-02-15 18:26:30 PST
Command list-jobs executed successfully
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:attach.html#attach[`attach`(1)],
link:configure-managed-jobs.html#configure-managed-jobs[`configure-managed-jobs`(1)]


