type=page
status=published
title=list-http-listeners
next=list-iiop-listeners.html
prev=list-http-lbs.html
~~~~~~

= list-http-listeners

[[list-http-listeners-1]][[GSRFM00168]][[list-http-listeners]]

== list-http-listeners

Lists the existing network listeners

=== Synopsis

[source]
----
asadmin [asadmin-options] list-http-listeners [--help]
[target]
----

=== Description

The `list-http-listeners` subcommand lists the existing network listeners.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

target::
  Restricts the listing to network listeners for a specified target.
  Valid values are as follows:

  `server`;;
    Lists the netowork listeners for the default server instance. This
    is the default value.
  configuration-name;;
    Lists the network listeners for the specified configuration.
  cluster-name;;
    Lists the network listeners for all server instances in the
    specified cluster.
  instance-name;;
    Lists the network listeners for the specified server instance.

=== Examples

[[GSRFM662]][[sthref1506]]

==== Example 1   Listing Network Listeners

The following command lists all the network listeners for the server
instance:

[source]
----
asadmin> list-http-listeners
http-listener-1
http-listener-2
admin-listener
Command list-http-listeners executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-http-listener.html#create-http-listener-1[`create-http-listener`(1)],
link:delete-http-listener.html#delete-http-listener-1[`delete-http-listener`(1)]


