type=page
status=published
title=list-protocol-filters
next=list-protocol-finders.html
prev=list-persistence-types.html
~~~~~~

= list-protocol-filters

[[list-protocol-filters]]

== list-protocol-filters

Lists the existing protocol filters

=== Synopsis

[source]
----
asadmin [asadmin-options] list-protocol-filters [--help]
[--target server]
protocol-name
----

=== Description

The `list-protocol-filters` subcommand lists the existing protocol
filters. This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
target::
  Restricts the listing to protocol filters for a specified target.
  Valid values are as follows:

  `server`;;
    Lists the protocol filters for the default server instance. This is
    the default value.
  configuration-name;;
    Lists the protocol filters for the specified configuration.
  cluster-name;;
    Lists the protocol filters for all server instances in the specified
    cluster.
  instance-name;;
    Lists the protocol filters for the specified server instance.

=== Operands

protocol-name::
  The name of the protocol for which to list protocol filters.

=== Examples

[[sthref1755]]

==== Example 1   Listing Protocol Filters

The following command lists all the protocol filters for the server
instance:

[source]
----
asadmin> list-protocol-filters http1
http1-filter
https1-filter
Command list-protocol-filters executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-protocol-filter.adoc#create-protocol-filter[`create-protocol-filter`(1)],
xref:delete-protocol-filter.adoc#delete-protocol-filter[`delete-protocol-filter`(1)]


