type=page
status=published
title=list-transports
next=list-virtual-servers.html
prev=list-timers.html
~~~~~~

= list-transports

[[list-transports]]

== list-transports

Lists the existing transports

=== Synopsis

[source]
----
asadmin [asadmin-options] list-transports [--help]
[target]
----

=== Description

The `list-transports` subcommand lists the existing transports. This
subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

target::
  Restricts the listing to transports for a specified target. Valid
  values are as follows:

  `server`;;
    Lists the transports for the default server instance. This is the
    default value.
  configuration-name;;
    Lists the transports for the specified configuration.
  cluster-name;;
    Lists the transports for all server instances in the specified
    cluster.
  instance-name;;
    Lists the transports for the specified server instance.

=== Examples

[[sthref1847]]

==== Example 1   Listing Transports

The following command lists all the transports for the server instance:

[source]
----
asadmin> list-transports
http1-trans
tcp
Command list-transports executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-transport.html#create-transport[`create-transport`(1)],
link:delete-transport.html#delete-transport[`delete-transport`(1)]


