type=page
status=published
title=list-javamail-resources
next=list-jdbc-connection-pools.html
prev=list-jacc-providers.html
~~~~~~

= list-javamail-resources

[[list-javamail-resources-1]][[GSRFM00172]][[list-javamail-resources]]

== list-javamail-resources

Lists the existing JavaMail session resources

=== Synopsis

[source]
----
asadmin [asadmin-options] list-javamail-resources [--help]
[target]
----

=== Description

The `list-javamail-resources` subcommand lists the existing JavaMail
session resources.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

=== Operands

target::
  This operand specifies the target for which the JavaMail session
  resources are to be listed. Valid values are:

  `server`;;
    Lists the resources for the default server instance. This is the
    default value.
  `domain`;;
    Lists the resources for the domain.
  cluster_name;;
    Lists the resources for the specified cluster.
  instance_name;;
    Lists the resources for a particular server instance.

=== Examples

[[GSRFM669]][[sthref1541]]

==== Example 1   Listing JavaMail Resources

This example lists the JavaMail session resources for the server
instance.

[source]
----
asadmin> list-javamail-resources
mail/MyMailSession
Command list-javamail-resources executed successfuly.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:create-javamail-resource.html#create-javamail-resource[`create-javamail-resource`(1)],
link:delete-javamail-resource.html#delete-javamail-resource[`delete-javamail-resource`(1)]


