type=page
status=published
title=list-resource-adapter-configs
next=list-resource-refs.html
prev=list-protocols.html
~~~~~~

= list-resource-adapter-configs

[[list-resource-adapter-configs]]

== list-resource-adapter-configs

Lists the names of the current resource adapter configurations

=== Synopsis

[source]
----
asadmin [asadmin-options] list-resource-adapter-configs [--help]
[--raname raname] [--verbose {false|true}]
----

=== Description

This command lists the configuration information in the `domain.xml` for
the connector module. It lists an entry called `resource-adapter-config`
in the `domain.xml` file. If the `--raname` option is specified, only
the resource adapter configurations for the specified connector module
are listed.

This command is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--raname`::
  Specifies the connector module name.
`--verbose`::
  Lists the properties that are configured. Default value is false.

=== Examples

[[sthref1776]]

==== Example 1   Listing the Resource Adapter Configurations

This example lists the current resource adapter configurations.

[source]
----
asadmin> list-resource-adapter-configs
ra1
ra2
Command list-resource-adapter-configs executed successfully
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-resource-adapter-config.adoc#create-resource-adapter-config[`create-resource-adapter-config`(1)],
xref:delete-resource-adapter-config.adoc#delete-resource-adapter-config[`delete-resource-adapter-config`(1)]


