type=page
status=published
title=migrate-timers
next=monitor.html
prev=login.html
~~~~~~

= migrate-timers

[[migrate-timers-1]][[GSRFM00211]][[migrate-timers]]

== migrate-timers

Moves EJB timers when a clustered instance was stopped or has crashed

=== Synopsis

[source]
----
asadmin [asadmin-options] migrate-timers [--help]
[--target target_server_name]
server_name
----

=== Description

The `migrate-timers` subcommand moves EJB timers to a specified server
when a server instance stops or crashes, if automatic timer migration is
not enabled in the cluster configuration. This subcommand is supported
in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This is the target server instance. If this option is not specified,
  then DAS will find a server instance or multiple server instances. A
  migration notification will be sent to the selected server instances.
`--destination`::
  This option is deprecated. It works exactly as the `--target` option
  does.

=== Operands

server_name::
  This is the server instance on which the timers are currently located.
  This server instance should not be running during the migration
  process.

=== Examples

[[GSRFM722]][[sthref1887]]

==== Example 1   Migrating Timers

This example shows how to migrate timers from the server named
`instance1` to a server named `instance2`.

[source]
----
asadmin>migrate-timers --target instance2 instance1
This command was successfully executed.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

link:list-timers.html#list-timers-1[`list-timers`(1)]


