type=page
status=published
title=monitoring
next=passwords.html
prev=logging.html
~~~~~~

= monitoring

[[monitoring]]

== monitoring

Reviewing the runtime state of components and services deployed in {productName}

=== Description

Monitoring is the process of reviewing the statistics of a system to
improve performance or solve problems. By monitoring the state of
various components and services deployed in {productName},
performance bottlenecks can be identified, failures can be anticipated,
and runtime standards can be established and observed. Data gathered by
monitoring can also be useful in performance tuning and capacity
planning.

The {productName} monitoring service is enabled by default, that is,
the `monitoring-enabled` attribute of the `monitoring-service` element
is set to true. Once the monitoring service is enabled, a deployed
module can then be enabled for monitoring by setting its monitoring
level to HIGH or LOW (default is OFF). Monitoring can be configured
dynamically by using the Administration Console or the
`enable-monitoring` and the `disable-monitoring` subcommands. The `set`
subcommand can also be used with dotted names to enable or disable
monitoring. However, a server restart is required for changes made by
using the `set` subcommand to take affect.

Monitoring data can be viewed by using the Administration Console or by
using the subcommands of the `asadmin` utility.

* The `monitor` subcommand displays monitoring data for a given type,
similar to the UNIX `top` command. The data is presented at given
intervals.
* The `list` and `get` subcommands display comprehensive data. Both use
dotted names to specify monitorable objects.

Alternate tools for monitoring {productName} components and services
include JConsole and the REST interface.

The Monitoring Scripting Client or DTrace Monitoring can be used to
start the available monitoring probes. Using these tools is helpful in
identifying performance issues during runtime. Monitoring Scripting
Client or DTrace Monitoring are only usable if their modules are
present.

=== See Also

xref:monitor.adoc#monitor[`monitor`(1)],
xref:enable-monitoring.adoc#enable-monitoring[`enable-monitoring`(1)],
xref:disable-monitoring.adoc#disable-monitoring[`disable-monitoring`(1)],
xref:list.adoc#list[`list`(1)], xref:get.adoc#get[`get`(1)],
xref:set.adoc#set[`set`(1)]

xref:dotted-names.adoc#dotted-names[`dotted-names`(5ASC)]

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

"xref:administration-guide.adoc#administering-the-monitoring-service[Administering the Monitoring Service]" in {productName} Administration Guide


