type=page
status=published
title=restart-instance
next=restart-local-instance.html
prev=restart-domain.html
~~~~~~

= restart-instance

[[restart-instance]]

== restart-instance

Restarts a running {productName} instance

=== Synopsis

[source]
----
asadmin restart-instance
[--debug <debug>]
[--timeout <timeout>]
instancename
----

=== Description

The `restart-instance` subcommand restarts a running {productName}
instance. This subcommand requires secure shell (SSH) to be configured
on the machine where the domain administration server (DAS) is running
and on the machine where the instance resides.

[NOTE]
====
SSH is not required if the instance resides on a node of type `CONFIG`
that represents the local host. A node of type `CONFIG` is not enabled
for communication over SSH.
====

You may run this subcommand from any machine that can contact the DAS.

The subcommand can restart any {productName} instance, regardless of
how the instance was created. For example, this subcommand can restart
an instance that was created by using the
xref:create-local-instance.adoc#create-local-instance[`create-local-instance`(1)]
subcommand.

When this subcommand restarts an instance, the DAS synchronizes the
instance with changes since the last synchronization as follows:

* For the `config` directory, the DAS synchronizes the instance with all changes.
* For the `applications` directory and `docroot` directory, only a
change to a top-level subdirectory causes the DAS to synchronize all
files under that subdirectory.
+
If a file below a top level subdirectory is changed without a change to
a file in the top level subdirectory, full synchronization is required.
In normal operation, files below the top level subdirectories of these
directories are not changed. If an application is deployed and
undeployed, full synchronization is not necessary to update the instance
with the change.

If different synchronization behavior is required, the instance must be
stopped and restarted by using following sequence of subcommands:

1. xref:stop-instance.adoc#stop-instance[`stop-instance`(1)]
2. xref:start-instance.adoc#start-instance[`start-instance`(1)]

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--debug`::
  Specifies whether the instance is restarted with
  https://docs.oracle.com/en/java/javase/17/docs/specs/jpda/jpda.html[Java Platform Debugger Architecture (JPDA)]
  debugging enabled. Possible values are as follows:

  `true`;;
    The instance is restarted with JPDA debugging enabled and the port
    number for JPDA debugging is displayed.
  `false`;;
    The instance is restarted with JPDA debugging disabled.

+
The default is the current setting of this option for the instance
  that is being restarted.

`--timeout`::
  Specifies timeout in seconds to evaluate the expected result.
  If the timeout is exceeded, the command fails - however it does
  not mean it did not make any changes. The instance status is unknown
  in such case.

=== Operands

instance-name::
  The name of the {productName} instance to restart. If the instance
  is not running, the subcommand displays a warning message and attempts
  to start the instance.

=== Examples

[[sthref1991]]

==== Example 1   Restarting a {productName} Instance

This example restarts the {productName} instance `pmdsa1`.

[source]
----
asadmin> restart-instance pmdsa1
Instance pmdsa1 was restarted.

Command restart-instance executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-instance.adoc#create-instance[`create-instance`(1)],
xref:create-local-instance.adoc#create-local-instance[`create-local-instance`(1)],
xref:delete-instance.adoc#delete-instance[`delete-instance`(1)],
xref:delete-local-instance.adoc#delete-local-instance[`delete-local-instance`(1)],
xref:restart-local-instance.adoc#restart-local-instance[`restart-local-instance`(1)],
xref:setup-ssh.adoc#setup-ssh[`setup-ssh`(1)],
xref:start-instance.adoc#start-instance[`start-instance`(1)],
xref:start-local-instance.adoc#start-local-instance[`start-local-instance`(1)],
xref:stop-instance.adoc#stop-instance[`stop-instance`(1)],
xref:stop-local-instance.adoc#stop-local-instance[`stop-local-instance`(1)]

Java Platform Debugger Architecture (JPDA)
(https://docs.oracle.com/en/java/javase/17/docs/specs/jpda/jpda.html)


