type=page
status=published
title=rollback-transaction
next=rotate-log.html
prev=restore-domain.html
~~~~~~

= rollback-transaction

[[rollback-transaction]]

== rollback-transaction

Rolls back the named transaction

=== Synopsis

[source]
----
asadmin [asadmin-options] rollback-transaction [--help]
[--target target]
transaction_id
----

=== Description

The `rollback-transaction` subcommand rolls back the named transaction.

Before you can roll back a transaction, you must do the following:

1. Enable monitoring using the `set` subcommand. For example:
+
[source]
----
asadmin> set clstr1-config.monitoring-service.module-monitoring-levels.transaction-service=HIGH
----
2. Use the `freeze-transaction-service` subcommand to halt in-process
transactions.
3. Look up the active transactions using the `get` subcommand with the
`--monitor` option. For example:
+
[source]
----
asadmin> get --monitor inst1.server.transaction-service.activeids-current
----

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target on which you are rolling back the
  transactions. Valid values are `server` or any other clustered or
  stand-alone instance.

=== Operands

transaction_id::
  Identifier for the transaction to be rolled back.

=== Examples

[[sthref2013]]

==== Example 1   Using rollback-transaction command

[source]
----
% asadmin rollback-transaction 0000000000000001_00
Command rollback-transaction executed succeessfully
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:freeze-transaction-service.adoc#freeze-transaction-service[`freeze-transaction-service`(1)],
xref:recover-transactions.adoc#recover-transactions[`recover-transactions`(1)],
xref:unfreeze-transaction-service.adoc#unfreeze-transaction-service[`unfreeze-transaction-service`(1)],

"link:administration-guide/transactions.html#administering-transactions[Administering Transactions]" in {productName} Administration Guide

"https://eclipse-ee4j.github.io/jakartaee-tutorial/#transactions[Transactions]"
in The Jakarta EE Tutorial


