type=page
status=published
title=set-log-levels
next=setup-ssh.html
prev=set-log-file-format.html
~~~~~~

= set-log-levels

[[set-log-levels]]

== set-log-levels

Sets the log level for one or more loggers

=== Synopsis

[source]
----
asadmin [asadmin-options] set-log-levels [--help]
[--target=target]
logger-name=logger-level[:logger-name=logger-level]*
----

=== Description

The `set-log-levels` subcommand sets the log level for one or more
loggers. Changes take effect with some latency for the reconfiguration.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  The server instance or cluster for which log levels will be set. Valid
  values are:
  * `server` - The default server instance. If no target is specified
    then log levels are set for the default server instance.
  * cluster-name - The name of a cluster.
  * instance-name - The name of a standalone server instance.

=== Operands

logger-name::
  The name of the logger. The `list-log-levels` subcommand can be used
  to list the names of the current loggers.
logger-level::
  The level to set for the logger. Log level values are `SEVERE`,
  `WARNING`, `INFO`, `CONFIG`, `FINE`, `FINER`, and `FINEST`. The
  default setting is `INFO`.

=== Examples

[[sthref2062]]

==== Example 1   Setting a Log Level for a Logger

This example sets the log level of the web container logger to
`WARNING`.

[source]
----
asadmin> set-log-levels jakarta.enterprise.system.container.web=WARNING
Command set-log-level executed successfully.
----

[[sthref2063]]

==== Example 2   Setting the Log Level for Multiple Loggers

This example sets the log level of the web container logger to `FINE`
and the log level of the EJB container logger to `SEVERE`:

[source]
----
asadmin set-log-levels jakarta.enterprise.system.container.web=FINE:
jakarta.enterprise.system.container.ejb=SEVERE
Command set-log-level executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:collect-log-files.adoc#collect-log-files[`collect-log-files`(1)],
xref:list-log-attributes.adoc#list-log-attributes[`list-log-attributes`(1)],
xref:list-log-levels.adoc#list-log-levels[`list-log-levels`(1)],
xref:rotate-log.adoc#rotate-log[`rotate-log`(1)],
xref:set-log-attributes.adoc#set-log-attributes[`set-log-attributes`(1)]

"xref:administration-guide.adoc#administering-the-logging-service[Administering the Logging Service]" in {productName} Administration Guide


