type=page
status=published
title=start-cluster
next=start-database.html
prev=show-component-status.html
~~~~~~

= start-cluster

[[start-cluster]]

== start-cluster

Starts a cluster

=== Synopsis

[source]
----
asadmin start-cluster
[--debug[=<debug(default:false)>]]
[--help|-?]
[--timeout <timeout>]
[--verbose[=<verbose(default:false)>]]
clustername
----

=== Description

The `start-cluster` subcommand starts a cluster by starting all
{productName} instances in the cluster that are not already running.
This subcommand requires the secure shell (SSH) to be configured on the host where
the domain administration server (DAS) is running and on all hosts where
instances in the cluster reside.

[NOTE]
====
If all instances reside on the same host as the DAS, SSH is not
required. You might require to start a cluster in which instances reside
on hosts where SSH is not configured that are remote from the
DAS. In this situation, run the
xref:start-local-instance.adoc#start-local-instance[`start-local-instance`(1)]
subcommand for each instance from the host where the instance resides.
====

You may run this subcommand from any host that can contact the DAS.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--debug`::
`-d`::
  Specifies whether the domain is started with
  http://java.sun.com/javase/technologies/core/toolsapis/jpda/[Java
  Platform Debugger Architecture (JPDA)]
  (https://docs.oracle.com/en/java/javase/11/docs/specs/jpda/conninv.html)
  debugging enabled. With debugging enabled extra exceptions can be printed.
  Possible values are as follows:

  `true`;;
    The instance is started with JPDA debugging enabled and the port
    number for JPDA debugging is displayed.
  `false`;;
    The instance is started with JPDA debugging disabled (default).

`--timeout`::
  Specifies timeout in seconds to evaluate the expected result.
  If the timeout is exceeded, the command fails - however it does
  not mean it did not make any changes. The status of instances is
  unknown in such case.

`--verbose`::
  Specifies whether additional status information is displayed when the
  cluster is started.
  Valid values are as follows:

  `true`;;
    Displays the command to start each instance in the cluster and
    whether the attempt to start each instance succeeded.
  `false`;;
    Displays no additional status information (default).

=== Operands

cluster-name::
  The name of the cluster to start.

=== Examples

[[sthref2114]]

==== Example 1   Staring a Cluster

This example starts the cluster `ymlcluster`. Additional status
information is displayed when the cluster is started.

[source]
----
asadmin> start-cluster --verbose ymlcluster
start-instance yml-i-sr1-usca-02
start-instance yml-i-sr1-usca-01

The command start-instance executed successfully for:
yml-i-sr1-usca-02 yml-i-sr1-usca-01

Command start-cluster executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-cluster.adoc#create-cluster[`create-cluster`(1)],
xref:delete-cluster.adoc#delete-cluster[`delete-cluster`(1)],
xref:list-clusters.adoc#list-clusters[`list-clusters`(1)],
xref:setup-ssh.adoc#setup-ssh[`setup-ssh`(1)],
xref:start-local-instance.adoc#start-local-instance[`start-local-instance`(1)],
xref:stop-cluster.adoc#stop-cluster[`stop-cluster`(1)]


