type=page
status=published
title=stop-domain
next=stop-instance.html
prev=stop-database.html
~~~~~~

= stop-domain

[[stop-domain]]

== stop-domain

Stops the Domain Administration Server of the specified domain

=== Synopsis

[source]
----
asadmin stop-domain
[--domaindir <domaindir>]
[--force[=<force(default:true)>]]
[--help|-?]
[--kill[=<kill(default:false)>]]
[--timeout <timeout>]
[domain_name]
----

=== Description

The `stop-domain` subcommand stops the Domain Administration Server
(DAS) of the specified domain. If the domain directory is not specified,
the domain in the default domains directory is stopped. If there are two
or more domains in the domains directory, the domain-name operand must
be specified.

This subcommand is supported in local or remote mode. If you specify a
host name, the subcommand assumes you are operating in remote mode,
which means you must correctly authenticate to the remote server. In
local mode, you normally do not need to authenticate to the server as
long as you are running the subcommand as the same user who started the server.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

`--domaindir`::
  Specifies the directory of the domain that is to be stopped. If
  specified, the path must be accessible in the file system. If not
  specified, the domain in the default as-install``/domains`` directory is
  stopped.

`--force`::
  Specifies whether the domain is forcibly stopped immediately. +
  Possible values are as follows:

  `true`;;
    The domain is forcibly stopped immediately (default).
  `false`;;
    The subcommand waits until all threads that are associated with the
    domain are exited before stopping the domain.

`--kill`::
  Specifies whether the domain is killed by using functionality of the
  operating system to terminate the domain process. +
  Possible values are as follows:

  `false`;;
    The domain is not killed. The subcommand uses functionality of the
    Java platform to terminate the domain process (default).
  `true`;;
    The domain is killed. The subcommand uses functionality of the
    operating system to terminate the domain process.

`--timeout`::
  Specifies timeout in seconds to evaluate the expected result.
  If the timeout is exceeded, the command fails - however it does
  not mean it did not make any changes. The domain status is unknown
  in such case.


=== Operands

domain-name::
  The name of the domain you want to stop. Default is the name specified
  during installation, usually `domain1`.

=== Examples

[[sthref2170]]

==== Example 1   Stopping a Domain

This example stops the domain named `sampleDomain` in the default
domains directory.

[source]
----
asadmin> stop-domain sampleDomain
Waiting for the domain to stop .................
Command stop-domain executed successfully.
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:delete-domain.adoc#delete-domain[`delete-domain`(1)],
xref:list-domains.adoc#list-domains[`list-domains`(1)],
xref:restart-domain.adoc#restart-domain[`restart-domain`(1)],
xref:start-domain.adoc#start-domain[`start-domain`(1)]


