type=page
status=published
title=stop-instance
next=stop-local-instance.html
prev=stop-domain.html
~~~~~~

= stop-instance

[[stop-instance]]

== stop-instance

Stops a running {productName} instance

=== Synopsis

[source]
----
asadmin stop-instance
[--force[=<force(default:true)>]]
[--help|-?]
[--kill[=<kill(default:false)>]]
[--timeout <timeout>]
instancename
----

=== Description

The `stop-instance` subcommand stops a running {productName} instance.

The subcommand can stop any {productName} instance, regardless of
how the instance was created. For example, this subcommand can stop an
instance that was created by using the
xref:create-local-instance.adoc#create-local-instance[`create-local-instance`(1)] subcommand.

This command is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--force`::
  Specifies whether the instance is forcibly stopped immediately. +
  Possible values are as follows:

  `true`;;
    The instance is forcibly stopped immediately (default).
  `false`;;
    The subcommand waits until all threads that are associated with the
    instance are exited before stopping the instance.

`--kill`::
  Specifies whether the instance is killed by using functionality of the
  operating system to terminate the instance process. +
  Possible values are as follows:

  `false`;;
    The instance is not killed. The subcommand uses functionality of the
    Java platform to terminate the instance process (default).
  `true`;;
    The instance is killed. The subcommand uses functionality of the
    operating system to terminate the instance process.

`--timeout`::
  Specifies timeout in seconds to evaluate the expected result.
  If the timeout is exceeded, the command fails - however it does
  not mean it did not make any changes. The instance status is unknown
  in such case.

=== Operands

instance-name::
  This is the name of the {productName} instance to stop.

=== Examples

This example stops the {productName} instance `yml-i-sj01`.

[[sthref2178]]

==== Example 1   Stopping a {productName} Instance

[source]
----
asadmin> stop-instance yml-i-sj01
The instance, yml-i-sj01, was stopped.

Command stop-instance executed successfully.
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:create-instance.adoc#create-instance[`create-instance`(1)],
xref:create-local-instance.adoc#create-local-instance[`create-local-instance`(1)],
xref:delete-instance.adoc#delete-instance[`delete-instance`(1)],
xref:delete-local-instance.adoc#delete-local-instance[`delete-local-instance`(1)],
xref:start-domain.adoc#start-domain[`start-domain`(1)],
xref:start-instance.adoc#start-instance[`start-instance`(1)],
xref:start-local-instance.adoc#start-local-instance[`start-local-instance`(1)],
xref:stop-domain.adoc#stop-domain[`stop-domain`(1)],
xref:stop-local-instance.adoc#stop-local-instance[`stop-local-instance`(1)]


