type=page
status=published
title=update-password-alias
next=uptime.html
prev=update-node-ssh001.html
~~~~~~

= update-password-alias

[[update-password-alias-1]][[GSRFM00257]][[update-password-alias]]

== update-password-alias

Updates a password alias

[[sthref2308]]

=== Synopsis

[source]
----
asadmin [asadmin-options] update-password-alias [--help]
aliasname
----

[[sthref2309]]

=== Description

This subcommand updates the password alias IDs in the named target. An
alias is a token of the form `${ALIAS=password-alias-password}`. The
password corresponding to the alias name is stored in an encrypted form.
The `update-password-alias` subcommand takes both a secure interactive
form (in which the user is prompted for all information) and a more
script-friendly form, in which the password is propagated on the command line.

This subcommand is supported in remote mode only.

[[sthref2310]]

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the link:asadmin.html#asadmin-1m[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[sthref2311]]

=== Operands

aliasname::
  This is the name of the password as it appears in `domain.xml`.

[[sthref2312]]

=== Examples

[[GSRFM794]][[sthref2313]]

==== Example 1   Updating a Password Alias

[source]
----
asadmin> update-password-alias jmspassword-alias
Please enter the alias password>
Please enter the alias password again>
Command update-password-alias executed successfully.
----

[[sthref2314]]

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

[[sthref2315]]

=== See Also

link:asadmin.html#asadmin-1m[`asadmin`(1M)]

link:create-password-alias.html#create-password-alias-1[`create-password-alias`(1)],
link:delete-password-alias.html#delete-password-alias-1[`delete-password-alias`(1)],
link:list-password-aliases.html#list-password-aliases-1[`list-password-aliases`(1)]


