type=page
status=published
title=verify-domain-xml
next=version.html
prev=validate-multicast.html
~~~~~~

= verify-domain-xml

[[verify-domain-xml-1]][[GSRFM00260]][[verify-domain-xml]]

== verify-domain-xml

Verifies the content of the domain.xml file

=== Synopsis

[source]
----
asadmin [asadmin-options] verify-domain-xml [--help]
[--domaindir domain-dir] [domain-name]
----

=== Description

Verifies the content of the `domain.xml` file by checking the following:

* That the `domain.xml` file can be parsed
* That the names for elements that have them are unique

This subcommand is supported in local mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`-h` `--help`::
  Displays the help text for the subcommand.
`--domaindir`::
  Specifies the domain root directory, where the domains are located.
  The path must be accessible in the file system. The default is
  as-install``/domains``.

=== Operands

domain_name::
  Specifies the name of the domain. The default is `domain1`.

=== Examples

[[GSRFM799]][[sthref2344]]

==== Example 1   Using verify-domain-xml

[source]
----
asadmin> verify-domain-xml
All Tests Passed.
domain.xml is valid
----

=== Exit Status

0::
  command executed successfully
1::
  error in executing the command

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]


