/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

package org.glassfish.orb.http.fory.grpc.glassfish;

import jakarta.inject.Inject;
import jakarta.inject.Singleton;

import java.io.IOException;

import org.glassfish.hk2.api.PostConstruct;
import org.glassfish.internal.data.ApplicationRegistry;
import org.glassfish.orb.http.fory.grpc.ForyGeneratedServiceRegistry;
import org.glassfish.orb.http.fory.grpc.ForyGrpcCatalog;
import org.glassfish.orb.http.fory.grpc.ForyGrpcServerAdapter;
import org.glassfish.orb.http.glassfish.GlassFishContainerBridge;
import org.glassfish.orb.http.glassfish.GlassFishSecurityBridge;
import org.glassfish.orb.http.glassfish.GlassFishTransactionBridge;
import org.glassfish.orb.http.glassfish.OrbHttpExtension;
import org.glassfish.orb.http.server.ServerExchange;
import org.jvnet.hk2.annotations.Service;

/**
 * Serves the deployed beans' remote business views to clients generated by
 * the Fory compiler: the IDL documents under {@link ForyGrpcCatalog#PREFIX},
 * and the calls under {@code /fory/}.
 *
 * <p>An extension of the endpoint rather than a part of it, so that a server
 * without this module serves remote EJB and JNDI over HTTP unchanged.
 */
@Service
@Singleton
public class ForyGrpcExtension implements OrbHttpExtension, PostConstruct {

    private static final String CALLS = "/fory/";

    @Inject
    private ApplicationRegistry applications;

    @Inject
    private GlassFishContainerBridge container;

    @Inject
    private GlassFishSecurityBridge security;

    @Inject
    private GlassFishTransactionBridge transactions;

    private ForyGrpcCatalog foryCatalog;

    private ForyGrpcServerAdapter foryGrpc;

    @Override
    public void postConstruct() {
        ForyEjbIndex index = new ForyEjbIndex(applications);
        foryCatalog = new ForyGrpcCatalog();
        ForyGeneratedServiceRegistry registry = index.foryRegistry();
        // This runs while the server starts, before any application is
        // deployed, so what is published here is usually empty. Both the
        // catalog and the registry rebuild themselves when they are asked for
        // something they do not have, which is how a bean deployed later
        // becomes visible without restarting the server.
        ForyGrpcCatalog catalog = foryCatalog;
        Runnable republish = () -> {
            catalog.clear();
            index.foryIdl().forEach(catalog::register);
            index.refreshForyRegistry();
        };
        catalog.onMiss(republish);
        registry.onMiss(republish);
        republish.run();
        foryGrpc = new ForyGrpcServerAdapter(registry,
                (path, exchange) -> {
                    ForyEjbIndex.ForyRoute route = index.foryRoute(path);
                    if (route == null) throw new IllegalStateException("unknown Fory route: " + path);
                    Object securityToken = security.establish(exchange.authenticatedUser());
                    try {
                        var key = container.resolve(route.app(), route.module(), null, route.bean(), null);
                        Object target = container.getTargetObject(key, route.view());
                        return new ForyGrpcServerAdapter.Target() {
                            @Override public Object value() { return target; }
                            @Override public void close() {
                                try {
                                    container.releaseTargetObject(target);
                                } finally {
                                    security.clear(securityToken);
                                }
                            }
                        };
                    } catch (RuntimeException | Error failure) {
                        security.clear(securityToken);
                        throw failure;
                    }
                },
                16 * 1024 * 1024, transactions);
    }

    @Override
    public boolean serves(String path) {
        return path.contains(CALLS) || path.contains(ForyGrpcCatalog.PREFIX);
    }

    @Override
    public void dispatch(String path, ServerExchange exchange) throws IOException {
        if (path.contains(CALLS)) {
            foryGrpc.dispatch(exchange);
        } else {
            foryCatalog.dispatch(exchange);
        }
    }
}
