type=page
status=published
title=Packaging, Integrating, and Delivering an Add-On Component
next=integration-point-reference.html
prev=session-persistence-modules.html
~~~~~~

= Packaging, Integrating, and Delivering an Add-On Component

[[packaging-integrating-and-delivering-an-add-on-component]]
== Packaging, Integrating, and Delivering an Add-On Component

Packaging an add-on component enables the component to interact with the
{productName} kernel in the same way as other components. Integrating
a component with {productName} enables {productName} to discover
the component at runtime.

The following topics are addressed here:

* xref:#packaging-an-add-on-component[Packaging an Add-On Component]
* xref:#integrating-an-add-on-component-with-glassfish-server[Integrating an Add-On Component With {productName}]

[[packaging-an-add-on-component]]

=== Packaging an Add-On Component

To enable an add-on component to plug in to the {productName} kernel
in the same way as other components, package the component as an OSGi
bundle.

A bundle is the unit of deployment in the OSGi module management
subsystem. To package a component as an OSGi bundle, package the
component's constituent files in a Java archive (JAR) file with
appropriate manifest entries. The manifest entries provide information
about the component that is required to enable the component to be
plugged into the {productName} kernel, such as:

* Name
* Version
* Dependencies
* Capabilities

[[integrating-an-add-on-component-with-glassfish-server]]

=== Integrating an Add-On Component With {productName}

Integrating an add-on component with {productName} enables {productName} to
discover the component at runtime. To integrate an add-on
component with {productName}, ensure that the JAR file that contains
the component is copied to or installed in the as-install``/modules/`` directory.

For information about how to create IPS packages, see the
http://wikis.oracle.com/display/IpsBestPractices/[IPS best practices
document] (`http://wikis.oracle.com/display/IpsBestPractices/`).

