type=page
status=published
title=Eclipse GlassFish Server Add-On Component Development Guide, Release 7
next=preface.html
prev=lot.html

Eclipse GlassFish Server Add-On Component Development Guide, Release 7
======================================================================


[[eclipse-glassfish-server]]
Eclipse GlassFish Server
------------------------

Add-On Component Development Guide

Release 7

Contributed 2018-2022

This document explains how to use published interfaces of Eclipse GlassFish
Server to develop add-on components for GlassFish
Server. This document explains how to perform only those tasks that
ensure that the add-on component is suitable for GlassFish Server.

This document is for software developers who are developing add-on
components for GlassFish Server. This document assumes that the
developers are working with a distribution of GlassFish Server. Access
to the source code of the GlassFish project is not required to perform
the tasks in this document. This document also assumes the ability to
program in the Java language.

[[sthref1]]

'''''

Eclipse GlassFish Server Add-On Component Development Guide,
Release 7

Copyright © 2013, 2019 Oracle and/or its affiliates. All rights reserved.

This program and the accompanying materials are made available under the
terms of the Eclipse Public License v. 2.0, which is available at
http://www.eclipse.org/legal/epl-2.0.

SPDX-License-Identifier: EPL-2.0

Oracle and Java are registered trademarks of Oracle and/or its
affiliates. Other names may be trademarks of their respective owners.

Intel and Intel Xeon are trademarks or registered trademarks of Intel
Corporation. All SPARC trademarks are used under license and are
trademarks or registered trademarks of SPARC International, Inc. AMD,
Opteron, the AMD logo, and the AMD Opteron logo are trademarks or
registered trademarks of Advanced Micro Devices. UNIX is a registered
trademark of The Open Group.

