/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

package org.glassfish.webservices.codegen;

import java.util.Iterator;
import org.glassfish.api.deployment.DeploymentContext;
import org.glassfish.hk2.api.ServiceLocator;

/**
 * This interface defines all behaviours of any codegen implementation
 *
 * @author  Jerome Dochez
 */
public interface Codegen {
    
    /**
     * perform the codegen with the context provided
     */
    public void run(ServiceLocator habitat, DeploymentContext context, String moduleClassPath) throws Exception;

    /**
     * @return the list of source files generated by this 
     * generator
     */
    public Iterator getListOfSourceFiles();
    
    /**
     * @return the list of binary files generated by this 
     * generator
     */
    public Iterator getListOfBinaryFiles();
    
}
