/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

package com.sun.jts.codegen.otsidl;


/**
* com/sun/jts/codegen/otsidl/JControlOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from com/sun/jts/ots.idl
* Tuesday, February 5, 2002 12:57:23 PM PST
*/


//#-----------------------------------------------------------------------------
public interface JControlOperations  extends org.omg.CosTransactions.ControlOperations
{
  org.omg.CosTransactions.otid_t getGlobalTID (org.omg.CosTransactions.StatusHolder status);

  // transaction, and a value that indicates the state of the transaction.
  long getLocalTID (org.omg.CosTransactions.StatusHolder status);

  // value that indicates the state of the transaction.
  org.omg.CosTransactions.Status getTranState ();

  // Returns the state of the transaction as the Control object knows it.
  void setTranState (org.omg.CosTransactions.Status state);
} // interface JControlOperations
