/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

package com.sun.jts.codegen.otsidl;


/**
* com/sun/jts/codegen/otsidl/ResourceStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from com/sun/jts/ots.idl
* Tuesday, February 5, 2002 12:57:23 PM PST
*/

public class ResourceStatus implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 5;
  private static com.sun.jts.codegen.otsidl.ResourceStatus[] __array = new com.sun.jts.codegen.otsidl.ResourceStatus [__size];

  public static final int _None = 0;
  public static final com.sun.jts.codegen.otsidl.ResourceStatus None = new com.sun.jts.codegen.otsidl.ResourceStatus(_None);
  public static final int _Registered = 1;
  public static final com.sun.jts.codegen.otsidl.ResourceStatus Registered = new com.sun.jts.codegen.otsidl.ResourceStatus(_Registered);
  public static final int _Completing = 2;
  public static final com.sun.jts.codegen.otsidl.ResourceStatus Completing = new com.sun.jts.codegen.otsidl.ResourceStatus(_Completing);
  public static final int _Completed = 3;
  public static final com.sun.jts.codegen.otsidl.ResourceStatus Completed = new com.sun.jts.codegen.otsidl.ResourceStatus(_Completed);
  public static final int _Heuristic = 4;
  public static final com.sun.jts.codegen.otsidl.ResourceStatus Heuristic = new com.sun.jts.codegen.otsidl.ResourceStatus(_Heuristic);

  public int value ()
  {
    return __value;
  }

  public static com.sun.jts.codegen.otsidl.ResourceStatus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ResourceStatus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ResourceStatus
