type=page
status=published
title=Setting Up a Development Environment
next=class-loaders.html
prev=part-tasks-and-tools.html
~~~~~~

= Setting Up a Development Environment

[[setting-up-a-development-environment]]
== Setting Up a Development Environment

This chapter gives guidelines for setting up an application development
environment in the {productName}. Setting up an environment
for creating, assembling, deploying, and debugging your code involves
installing the mainstream version of the {productName} and making use
of development tools. In addition, sample applications are available.

The following topics are addressed here:

* xref:#installing-and-preparing-the-server-for-development[Installing and Preparing the Server for Development]
* xref:#high-availability-features[High Availability Features]
* xref:#development-tools[Development Tools]
* xref:#sample-applications[Sample Applications]

[[installing-and-preparing-the-server-for-development]]

=== Installing and Preparing the Server for Development

For more information about {productName} installation, see the
xref:installation-guide.adoc#GSING[
{productName} Installation Guide].

The following components are included in the full installation.

* JDK
* {productName} core

** Java Platform, Standard Edition (Java SE) 11 or newer
** Jakarta EE 10 compliant application server
** Administration Console
** `asadmin` utility
** Other development and deployment tools
** Open Message Queue software
** Apache http://db.apache.org/derby/manuals[Derby database]
** Load balancer plug-ins for web servers

The NetBeans Integrated Development Environment (IDE) bundles the
GlassFish edition of the {productName}, so information about this IDE
is provided as well.

After you have installed {productName}, you can further optimize the
server for development in these ways:

* Locate utility classes and libraries so they can be accessed by the
proper class loaders. For more information, see
xref:class-loaders.adoc#using-the-common-class-loader[Using the Common Class Loader].
* Set up debugging. For more information, see
xref:debugging-apps.adoc#debugging-applications[Debugging Applications].
* Configure the Virtual Machine for the Java platform (JVM software).
For more information, see "xref:administration-guide.adoc#administering-the-virtual-machine-for-the-java-platform[
Administering the Virtual Machine for the Java Platform]"
in {productName} Administration Guide.

[[high-availability-features]]

=== High Availability Features

High availability features such as load balancing and session failover
are discussed in detail in the xref:ha-administration-guide.adoc#GSHAG[{productName}
High Availability Administration Guide]. This book describes the
following features in the following sections:

* For information about HTTP session persistence, see
xref:webapps.adoc#distributed-sessions-and-persistence[Distributed Sessions and Persistence].
* For information about checkpointing of the stateful session bean
state, see xref:ejb.adoc#stateful-session-bean-failover[Stateful Session Bean Failover].
* For information about failover and load balancing for Java clients,
see xref:java-clients.adoc#developing-java-clients[Developing Java Clients].
* For information about load balancing for message-driven beans, see
xref:jms.adoc#load-balanced-message-inflow[Load-Balanced Message Inflow].

[[development-tools]]

=== Development Tools

The following general tools are provided with the {productName}:

* xref:#the-asadmin-command[The `asadmin` Command]
* xref:#the-administration-console[The Administration Console]

The following development tools are provided with the {productName}
or downloadable from Oracle:

* xref:#the-migration-tool[The Migration Tool]
* xref:#the-netbeans-ide[The NetBeans IDE]

The following third-party tools might also be useful:

* xref:#debugging-tools[Debugging Tools]
* xref:#profiling-tools[Profiling Tools]

[[the-asadmin-command]]

==== The `asadmin` Command

The `asadmin` command allows you to configure a local or remote server
and perform both administrative and development tasks at the command
line. For general information about `asadmin`, see the
xref:reference-manual.adoc#GSRFM[{productName} Reference Manual].

The `asadmin` command is located in the as-install``/bin`` directory. Type
`asadmin help` for a list of subcommands.

[[the-administration-console]]

==== The Administration Console

The Administration Console lets you configure the server and perform
both administrative and development tasks using a web browser. For
general information about the Administration Console, click the Help
button in the Administration Console. This displays the {productName}
online help.

To access the Administration Console, type `http://`host`:4848` in your
browser. The host is the name of the machine on which the {productName} is running. By default, the host is `localhost`. For example:

[source]
----
http://localhost:4848
----

[[the-migration-tool]]

==== The Migration Tool

The Migration Tool converts and reassembles Jakarta EE applications and
modules developed on other application servers. This tool also generates
a report listing how many files are successfully and unsuccessfully
migrated, with reasons for migration failure. For more information and
to download the Migration Tool, see
`http://java.sun.com/j2ee/tools/migration/index.html`.

[[the-netbeans-ide]]

==== Code Editors

There is several advanced editors with an integration with GlassFish or
generic Jakarta EE servers. Sometimes you have to install additional
extensions, sometimes all you need is just some configuration.

* `https://www.jetbrains.com/idea/[IntelliJ IDEA]`
* `https://www.eclipse.org/downloads/packages/[Eclipse IDE]`
* `https://netbeans.apache.org[Apache NetBeans]`
* `https://code.visualstudio.com[Microsoft Visual Studio Code]`

[[debugging-tools]]

==== Debugging Tools

You can use several debugging tools with the {productName}. For more
information, see xref:debugging-apps.adoc#debugging-applications[Debugging Applications].

[[profiling-tools]]

==== Profiling Tools

You can use several profilers with the {productName}. For more
information, see xref:debugging-apps.adoc#debug-profiling-tools[Profiling Tools].

[[sample-applications]]

=== Sample Applications

The samples are available from `https://github.com/eclipse-ee4j/glassfish-samples`.

Most {productName} samples have the following directory structure:

* The `docs` directory contains instructions for how to use the sample.
* The `pom.xml` file defines Maven targets for the sample.
* The `src/` directory contains source code for the sample.


