type=page
status=published
title=Frequently Asked Questions
prev=specific-issues.html
~~~~~~

= Frequently Asked Questions

[[frequently-asked-questions]]
== 3 Frequently Asked Questions

This chapter lists a few of the Frequently Asked Questions (FAQs)
related to {productName} 7. For the latest FAQs, see the
GlassFish wiki at
`http://wikis.sun.com/display/GlassFish/GlassFishFAQIndex`.

This chapter contains the following:

* xref:#administration-faqs[Administration FAQs]
* xref:#application-faqs[Application FAQs]
* xref:#eclipse-faqs[Eclipse FAQs]
* xref:#extensibility-faqs[Extensibility FAQs]
* xref:#java-persistence-faqs[Java Persistence FAQs]

[[administration-faqs]]

=== Administration FAQs

[[which-asadmin-commands-are-supported]]

==== Which `asadmin` Commands are Supported?

Use `asadmin` `list-commands` to determine which commands are supported
and available for use. For related information, see
"xref:administration-guide.adoc#asadmin-subcommands[Subcommands for the asadmin Utility]" in {productName} Administration Guide.

[[application-faqs]]

=== Application FAQs

[[how-do-i-debug-applications]]

==== How Do I Debug Applications?

See "xref:application-development-guide.adoc#debugging-applications[Debugging Applications]" in {productName} Application Development Guide.

[[how-do-i-change-application-permissions]]

==== How Do I Change Application Permissions?

See "xref:application-development-guide.adoc#changing-permissions-for-an-application[Changing Permissions for an Application]" in
{productName} Application Development Guide.

[[what-are-the-restrictions-and-optimizations-for-session-beans]]

==== What Are the Restrictions and Optimizations for Session Beans?

See "xref:application-development-guide.adoc#session-bean-restrictions-and-optimizations[Session Bean Restrictions and Optimizations]" in
{productName} Application Development Guide.

[[eclipse-faqs]]

=== Eclipse FAQs

[[where-can-i-find-more-information-about-eclipse-and-glassfish-server-integration]]

==== Where Can I Find More Information About Eclipse and {productName} Integration?

Eclipse is a development environment that provides a framework, tools,
and runtime for deploying and managing software. The GlassFish plugin
for Eclipse provides important changes to better support {productName} and to provide optimal redeployment of web applications. For more
information, see the GlassFish Plugins page:
`http://glassfishplugins.java.net`.

[[extensibility-faqs]]

=== Extensibility FAQs

[[how-do-i-develop-add-on-components]]

==== How Do I Develop Add-On Components?

See the xref:add-on-component-development-guide.adoc#GSACG[{productName} Add-On
Component Development Guide] for complete details.

[[how-do-i-add-containers]]

==== How Do I Add Containers?

{productName} has a highly modular architecture that enables you to
add new types of containers that handle many application types, not just
Jakarta EE. {productName} defines a service provider interface (SPI),
which container developers implement. The {productName} framework
then invokes the container's implementation of the SPI to detect,
deploy, and manage applications of the new type.

For more information, see "xref:add-on-component-development-guide.adoc#adding-container-capabilities[Adding Container
Capabilities]" in {productName} Add-On Component
Development Guide.

[[how-do-i-extend-the-administration-console]]

==== How Do I Extend the Administration Console?

See "xref:add-on-component-development-guide.adoc#extending-the-administration-console[Extending the Administration Console]" in
{productName} Add-On Component Development Guide.

[[java-persistence-faqs]]

=== Java Persistence FAQs

[[what-are-the-restrictions-and-optimizations-for-the-java-persistence-api]]

==== What Are the Restrictions and Optimizations for the Java Persistence API?

See "xref:application-development-guide.adoc#restrictions-and-optimizations[Restrictions and Optimizations]" in {productName} Application Development Guide.

