type=page
status=published
title=delete-connector-work-security-map
next=delete-context-service.html
prev=delete-connector-security-map.html
~~~~~~
delete-connector-work-security-map
==================================

[[delete-connector-work-security-map-1]][[GSRFM00073]][[delete-connector-work-security-map]]

delete-connector-work-security-map
----------------------------------

deletes a work security map for the specified resource adapter

[[sthref650]]

Synopsis

[source,oac_no_warn]
----
asadmin [asadmin-options] delete-connector-work-security-map [--help] 
--raname raname
mapname
----

[[sthref651]]

Description

The `delete-connector-work-security-map` subcommand deletes a security
map associated with the specified resource adapter. For this subcommand
to succeed, you must have first created and deployed the specified
resource adapter.

The enterprise information system (EIS) is any system that holds the
data of an organization. It can be a mainframe, a messaging system, a
database system, or an application.

This subcommand is supported in remote mode only.

[[sthref652]]

Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the link:asadmin.html#asadmin-1m[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--raname`::
  Indicates the connector module name with which the work security map
  is associated.

[[sthref653]]

Operands

mapname::
  The name of the work security map to be deleted.

[[sthref654]]

Examples

[[GSRFM541]][[sthref655]]

Example 1   Deleting a Connector Work Security Map

This example deletes the work security map named
`work_security_map_name` for the resource adapter named `ra_name`.

[source,oac_no_warn]
----
asadmin delete-connector-work-security-map
--raname ra_name work_security_map_name
Command delete-connector-work-security-map executed successfully.
----

[[sthref656]]

Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

[[sthref657]]

See Also

link:asadmin.html#asadmin-1m[`asadmin`(1M)]

link:create-connector-work-security-map.html#create-connector-work-security-map-1[`create-connector-work-security-map`(1)],
link:list-connector-work-security-maps.html#list-connector-work-security-maps-1[`list-connector-work-security-maps`(1)],
link:update-connector-work-security-map.html#update-connector-work-security-map-1[`update-connector-work-security-map`(1)]


