type=page
status=published
title=disable-secure-admin-internal-user
next=disable-secure-admin-principal.html
prev=disable-secure-admin.html
~~~~~~
disable-secure-admin-internal-user
==================================

[[disable-secure-admin-internal-user-1]][[GSRFM00122]][[disable-secure-admin-internal-user]]

disable-secure-admin-internal-user
----------------------------------

Instructs the \{product---name} DAS and instances to not use the
specified admin user to authenticate with each other and to authorize
admin operations.

[[sthref1079]]

Synopsis

[source,oac_no_warn]
----
asadmin [asadmin-options] disable-secure-admin-internal-user [--help] 
admin-username
----

[[sthref1080]]

Description

The `disable-secure-admin-internal-user` subcommand disables secure
admin from using the username (instead of SSL certificates) to
authenticate the DAS and instances with each other and to authorize
admin operations.

[[sthref1081]]

Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the link:asadmin.html#asadmin-1m[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[sthref1082]]

Operands

admin-username::
  The admin user name that \{product---name} should not use to
  authenticate the DAS and instances with each other and to authorize
  admin operations.

[[sthref1083]]

Examples

[[GSRFM597]][[sthref1084]]

Example 1   Disabling a user name for secure admin

The following example disables secure admin from using username tester
to authenticate the DAS and instances with each other and to authorize
admin operations.

[source,oac_no_warn]
----
asadmin> disable-secure-admin-internal-user tester

Command disable-secure-admin-internal-user executed successfully.
----

[[sthref1085]]

Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

[[sthref1086]]

See Also

link:asadmin.html#asadmin-1m[`asadmin`(1M)]

link:enable-secure-admin.html#enable-secure-admin-1[`enable-secure-admin`(1)],
link:enable-secure-admin-internal-user.html#enable-secure-admin-internal-user-1[`enable-secure-admin-internal-user`(1)]


