type=page
status=published
title={productName} Upgrade Guide, Release {productMajorVersion}
next=preface.html
prev=lot.html
~~~~~~

= {productName} Upgrade Guide, Release {productMajorVersion}

[[eclipse-glassfish-server]]
== {productName}

Upgrade Guide

Release {productMajorVersion}

Contributed 2018 - 2024

This guide explains how to upgrade to {productName} {productMajorVersion}
from previous {productName} and Sun GlassFish Enterprise
Server product releases. Also included in this guide are instructions
for upgrading configuration data and Jakarta EE applications from
binary-compatible earlier versions of this software to work with
{productName} {productMajorVersion}. Finally, this guide describes
compatibility issues that affect data and applications that are to be
migrated.

Note: The main thrust of the {productName} {productMajorVersion}
release is to provide an application server for developers to explore
and begin exploiting the new and updated technologies in the Jakarta EE 10
platform. Thus, the upgrade feature of {productName} was not a focus
of this release. The feature is included in the release, but it may not
function properly with some of the new features added in support of the
Jakarta EE 10 platform.

[[sthref1]]

'''''

{productName} Upgrade Guide, Release {productMajorVersion}

Copyright © 2013, 2019 Oracle and/or its affiliates. All rights reserved.

This program and the accompanying materials are made available under the
terms of the Eclipse Public License v. 2.0, which is available at
http://www.eclipse.org/legal/epl-2.0.

SPDX-License-Identifier: EPL-2.0

Oracle and Java are registered trademarks of Oracle and/or its
affiliates. Other names may be trademarks of their respective owners.

Intel and Intel Xeon are trademarks or registered trademarks of Intel
Corporation. All SPARC trademarks are used under license and are
trademarks or registered trademarks of SPARC International, Inc. AMD,
Opteron, the AMD logo, and the AMD Opteron logo are trademarks or
registered trademarks of Advanced Micro Devices. UNIX is a registered
trademark of The Open Group.
