type=page
status=published
title={productName} Upgrade Guide, Release {product-majorVersion}
next=preface.html
~~~~~~

= {productName} Upgrade Guide, Release {product-majorVersion}

[[eclipse-glassfish-server]]
== {productName}

Upgrade Guide

Release {product-majorVersion}

This guide explains how to upgrade to {productName} {product-majorVersion}
from previous {productName} and Sun GlassFish Enterprise
Server product releases. Also included in this guide are instructions
for upgrading configuration data and Jakarta EE applications from
binary-compatible earlier versions of this software to work with
{productName} {product-majorVersion}. Finally, this guide describes
compatibility issues that affect data and applications that are to be
migrated.

[[sthref1]]

'''''

{productName} Upgrade Guide, Release {product-majorVersion}

Copyright © 2025 Contributors to the Eclipse Foundation. All rights reserved. +
Copyright © 2013, 2019 Oracle and/or its affiliates. All rights reserved.

This program and the accompanying materials are made available under the
terms of the Eclipse Public License v. 2.0, which is available at
http://www.eclipse.org/legal/epl-2.0.

SPDX-License-Identifier: EPL-2.0

Oracle and Java are registered trademarks of Oracle and/or its
affiliates. Other names may be trademarks of their respective owners.

Intel and Intel Xeon are trademarks or registered trademarks of Intel
Corporation. All SPARC trademarks are used under license and are
trademarks or registered trademarks of SPARC International, Inc. AMD,
Opteron, the AMD logo, and the AMD Opteron logo are trademarks or
registered trademarks of Advanced Micro Devices. UNIX is a registered
trademark of The Open Group.
