title=Subcommands for the asadmin Utility
next=loe.adoc
prev=part-appendixes.adoc
~~~~~~

= Subcommands for the asadmin Utility

[[asadmin-subcommands]]
== A Subcommands for the `asadmin` Utility

This appendix lists the `asadmin` subcommands that are included with
this release of the {productName} {product-majorVersion} software.

* <<General Administration Subcommands>>
* <<Batch Jobs Subcommands>>
* <<Concurrent Resources Subcommands>>
* <<Connectivity Subcommands>>
* <<Domain Subcommands>>
* <<Internet Connectivity Subcommands>>
* <<Jakarta Mail Subcommands>>
* <<JMS Subcommands>>
* <<JNDI Subcommands>>
* <<JVM Subcommands>>
* <<Life Cycle Module Subcommands>>
* <<Logging and Monitoring Subcommands>>
* <<ORB Subcommands>>
* <<Thread Pool Subcommands>>
* <<Transaction Service Subcommands>>

For information and instructions on using the `asadmin` application
deployment subcommands, see
the xref:application-deployment-guide.adoc#GSDPG[{productName} Application Deployment Guide].

Online help for the `asadmin` subcommands can be invoked on the command
line, for example, `asadmin create-domain` `help`.
The xref:reference-manual.adoc#GSRFM[{productName} Reference Manual] also
provides a collection of these help pages.


[NOTE]
====
The common options used with remote subcommands are described in the
xref:reference-manual.adoc#asadmin[`asadmin`(1M)] help page.
====


[[general-administration-subcommands]]

=== General Administration Subcommands

xref:reference-manual.adoc#add-resources[`add-resources`]::
  Creates the resources named in the specified XML file. Supported in
  remote mode only. For procedural information in this guide, see
  xref:general-administration.adoc#to-add-resources-from-an-xml-file[To Add Resources From an XML File].
xref:reference-manual.adoc#asadmin[`asadmin`]::
  Describes how the `asadmin` utility works.
xref:reference-manual.adoc#attach[`attach`]::
  Attaches to subcommands that were started using the `asadmin --detach`
  option or that contain progress information. For procedural
  information in this guide, see
  xref:general-administration.adoc#to-run-asadmin-subcommands-in---detach-mode[To Run `asadmin` Subcommands
  in `--detach` Mode].
xref:reference-manual.adoc#configure-managed-jobs[`configure-managed-jobs`]::
  Configures how long information about subcommands (jobs) that were
  started using the `asadmin --detach` option or that contain progress
  information is kept. For procedural information in this guide, see
  xref:general-administration.adoc#to-run-asadmin-subcommands-in---detach-mode[To Run `asadmin` Subcommands
  in `--detach` Mode].
xref:reference-manual.adoc#create-module-config[`create-module-config`]::
  Adds the default configuration of a module to `domain.xml`.
xref:reference-manual.adoc#create-service[`create-service`]::
  Configures the starting of a domain administration server (DAS) on an
  unattended boot. On Oracle Solaris 10, this subcommand uses the
  Service Management Facility (SMF). For procedural information in this
  guide, see xref:domains.adoc#to-configure-a-das-or-an-instance-for-automatic-restart-on-oracle-solaris[To Configure a DAS or an Instance
  for Automatic Restart on Oracle Solaris].
xref:reference-manual.adoc#create-system-properties[`create-system-properties`]::
  Creates or updates system properties. Supported in remote mode only.
  For procedural information in this guide, see
  xref:general-administration.adoc#to-create-system-properties[To Create System Properties].
xref:reference-manual.adoc#delete-module-config[`delete-module-config`]::
  Removes the configuration of a module from `domain.xml`.
xref:reference-manual.adoc#delete-system-property[`delete-system-property`]::
  Deletes system properties of a domain or configuration, or server
  instance. Supported in remote mode only. For procedural information in
  this guide, see xref:general-administration.adoc#to-delete-a-system-property[To Delete a
  System Property].
xref:reference-manual.adoc#get[`get`]::
  Gets an attribute of an element in the `domain.xml` file. With the
  `-m` option, gets the names and values of the monitorable or
  configurable attributes. For procedural information in this guide, see
  xref:monitoring.adoc#guidelines-for-using-the-list-and-get-subcommands-for-monitoring[Guidelines for Using the `list` and `get`
  Subcommands for Monitoring].
xref:reference-manual.adoc#get-active-module-config[`get-active-module-config`]::
  Displays the current active configuration of a module.
xref:reference-manual.adoc#list[`list`]::
  Lists the configurable element. On Oracle Solaris, quotes are needed
  when running subcommands with `*` as the option value or operand. For
  procedural information in this guide, see
  xref:monitoring.adoc#guidelines-for-using-the-list-and-get-subcommands-for-monitoring[Guidelines for Using the `list` and `get`
  Subcommands for Monitoring].
xref:reference-manual.adoc#list-commands[`list-commands`]::
  Lists all the `asadmin` subcommands, local subcommands first, then
  remote subcommands. You can specify that only remote subcommands or
  only local subcommands be displayed. Supported in remote mode only.
  For procedural information in this guide, see
  xref:general-administration.adoc#to-list-subcommands[To List Subcommands].
xref:reference-manual.adoc#list-containers[`list-containers`]::
  Lists application containers and the status of each container.
  Supported in remote mode only. For procedural information in this
  guide, see xref:general-administration.adoc#to-list-containers[To List Containers].
xref:reference-manual.adoc#list-jobs[`list-jobs`]::
  Lists information about subcommands that were started using the
  `asadmin --detach` option or that contain progress information. For
  procedural information in this guide, see
  xref:general-administration.adoc#to-run-asadmin-subcommands-in---detach-mode[To Run `asadmin` Subcommands
  in `--detach` Mode].
xref:reference-manual.adoc#list-modules[`list-modules`]::
  Lists modules that are accessible to the {productName} subsystem.
  The status of each module is included. Supported in remote mode only.
  For procedural information in this guide, see
  xref:general-administration.adoc#to-list-modules[To List Modules].
xref:reference-manual.adoc#list-system-properties[`list-system-properties`]::
  Lists the system properties of a domain or configuration. Supported in
  remote mode only. For procedural information in this guide, see
  xref:general-administration.adoc#to-list-system-properties[To List System Properties].
xref:reference-manual.adoc#list-timers[`list-timers`]::
  List the timers owned by a specific server instance. Supported in
  remote mode only. For procedural information in this guide, see
  xref:general-administration.adoc#to-list-timers[To List Timers].
xref:reference-manual.adoc#multimode[`multimode`]::
  Provides an `asadmin>` prompt for running multiple subcommands while
  preserving options and environment settings. Supported in local mode
  only. For procedural information, see
  xref:general-administration.adoc#using-the-asadmin-utility[Using the `asadmin` Utility].
xref:reference-manual.adoc#osgi[`osgi`]::
  Delegates the command line to the Apache Felix Gogo remote shell for
  the execution of OSGi shell commands. For procedural information in
  Remote Shell Commands].
xref:reference-manual.adoc#osgi-shell[`osgi-shell`]::
  Provides interactive access to the Apache Felix Gogo remote shell for
  the execution of OSGi shell commands.
xref:reference-manual.adoc#set[`set`]::
  Sets the values of one or more configurable attributes. For procedural
  information in this guide, see xref:monitoring.adoc#configuring-monitoring[Configuring
  Monitoring].
xref:reference-manual.adoc#setup-local-dcom[`setup-local-dcom`]::
  Sets up the Distributed Component Object Model (DCOM) remote protocol
  on the host where the subcommand is run. The DCOM remote protocol is
  available only on Windows systems.
xref:reference-manual.adoc#show-component-status[`show-component-status`]::
  Lists the status of existing components. Supported in remote mode
  only. For procedural information in this guide, see
  xref:general-administration.adoc#to-show-component-status[To Show Component Status].
xref:reference-manual.adoc#start-database[`start-database`]::
  Starts the Apache Derby database server. Use this subcommand only for
  working with applications deployed to the {productName}. For
  procedural information in this guide, see xref:jdbc.adoc#to-start-the-database[To Start
  the Database].
xref:reference-manual.adoc#stop-database[`stop-database`]::
  Stops a process of the Apache Derby DB database server. For procedural
  information in this guide, see xref:jdbc.adoc#to-stop-the-database[To Stop the
  Database].
xref:reference-manual.adoc#version[`version`]::
  Displays the version information for the option specified in archive
  or folder format. Supported in remote mode only. For procedural
  information in this guide, see
  xref:general-administration.adoc#to-display-the-glassfish-server-version[To Display the {productName}
  Version].

[[batch-jobs-subcommands]]

=== Batch Jobs Subcommands

xref:reference-manual.adoc#list-batch-jobs[`list-batch-jobs`]::
  Lists batch jobs and job details. For procedural information in this
  guide, see xref:batch.adoc#to-list-batch-jobs[To List Batch Jobs].
xref:reference-manual.adoc#list-batch-job-executions[`list-batch-job-executions`]::
  Lists batch job executions and execution details. For procedural
  information in this guide,
  see xref:batch.adoc#to-list-batch-job-executions[To List Batch Job Executions].
xref:reference-manual.adoc#list-batch-job-steps[`list-batch-job-steps`]::
  Lists steps for a specific batch job execution. For procedural
  information in this guide,
  see xref:batch.adoc#to-list-batch-job-steps[To List Batch Job Steps].
xref:reference-manual.adoc#list-batch-runtime-configuration[`list-batch-runtime-configuration`]::
  Displays the configuration of the batch runtime. For procedural
  information in this guide, see
  xref:batch.adoc#to-list-the-batch-runtime-configuration[To List the Batch Runtime Configuration].
xref:reference-manual.adoc#set-batch-runtime-configuration[`set-batch-runtime-configuration`]::
  Configures the batch runtime. For procedural information in this
  guide, see xref:batch.adoc#to-configure-the-batch-runtime[To Configure the Batch Runtime].

[[concurrent-resources-subcommands]]

=== Concurrent Resources Subcommands

xref:reference-manual.adoc#create-context-service[`create-context-service`]::
  Creates a context service resource. For procedural information in this
  guide, see xref:concurrent.adoc#to-create-a-context-service[To Create a Context Service].
xref:reference-manual.adoc#create-managed-executor-service[`create-managed-executor-service`]::
  Creates a managed executor service resource. For procedural
  information in this guide, see xref:concurrent.adoc#to-create-a-managed-executor-service[To Create
  a Managed Executor Service].
xref:reference-manual.adoc#create-managed-scheduled-executor-service[`create-managed-scheduled-executor-service`]::
  Creates a managed scheduled executor service resource. For procedural
  information in this guide, see xref:concurrent.adoc#to-create-a-managed-scheduled-executor-service[To Create
  a Managed Scheduled Executor Service].
xref:reference-manual.adoc#create-managed-thread-factory[`create-managed-thread-factory`]::
  Creates a managed thread factory resource. For procedural information
  in this guide, see xref:concurrent.adoc#to-create-a-managed-thread-factory[To Create a Managed
  Thread Factory].
xref:reference-manual.adoc#create-context-service[`list-context-services`]::
  Lists context service resources. For procedural information in this
  guide, see xref:concurrent.adoc#to-list-context-services[To List Context Services].
xref:reference-manual.adoc#create-managed-executor-service[`list-managed-executor-services`]::
  Lists managed executor service resources. For procedural information
  in this guide, see xref:concurrent.adoc#to-list-managed-executor-services[To List Managed
  Executor Services].
xref:reference-manual.adoc#create-managed-scheduled-executor-service[`list-managed-scheduled-executor-services`]::
  Lists managed scheduled executor service resources. For procedural
  information in this guide, see xref:concurrent.adoc#to-list-managed-scheduled-executor-services[To List
  Managed Scheduled Executor Services].
xref:reference-manual.adoc#create-managed-thread-factory[`list-managed-thread-factories`]::
  Lists managed thread factory resources. For procedural information in
  this guide, see xref:concurrent.adoc#to-list-managed-thread-factories[To List Managed Thread
  Factories].
xref:reference-manual.adoc#delete-context-service[`delete-context-service`]::
  Removes a context service resource. For procedural information in this
  guide, see xref:concurrent.adoc#to-delete-a-context-service[To Delete a Context Service].
xref:reference-manual.adoc#delete-managed-executor-service[`delete-managed-executor-service`]::
  Removes a managed executor service resource. For procedural
  information in this guide, see xref:concurrent.adoc#to-delete-a-managed-executor-service[To Delete
  a Managed Executor Service].
xref:reference-manual.adoc#delete-managed-scheduled-executor-service[`delete-managed-scheduled-executor-service`]::
  Removes a managed scheduled executor service resource. For procedural
  information in this guide, see xref:concurrent.adoc#to-delete-a-managed-scheduled-executor-service[To Delete
  a Managed Scheduled Executor Service].
xref:reference-manual.adoc#delete-managed-thread-factory[`delete-managed-thread-factory`]::
  Removes a managed thread factory resource. For procedural information
  in this guide, see xref:concurrent.adoc#to-delete-a-managed-thread-factory[To Delete a Managed
  Thread Factory].

[[connectivity-subcommands]]

=== Connectivity Subcommands

xref:reference-manual.adoc#create-admin-object[`create-admin-object`]::
  Creates an administered object. For procedural information in this
  guide, see xref:connectors.adoc#to-create-an-administered-object[To Create an Administered
  Object].
xref:reference-manual.adoc#create-connector-connection-pool[`create-connector-connection-pool`]::
  Adds a new connector connection pool with the specified connection
  pool name. For procedural information in this guide, see
  xref:connectors.adoc#to-create-a-connector-connection-pool[To Create a Connector Connection Pool].
xref:reference-manual.adoc#create-connector-resource[`create-connector-resource`]::
  Creates a connector resource. For procedural information in this
  guide, see xref:connectors.adoc#to-create-a-connector-resource[To Create a Connector Resource].
xref:reference-manual.adoc#create-connector-security-map[`create-connector-security-map`]::
  Creates a connector security map for the specified connector
  connection pool. For procedural information, see
  xref:connectors.adoc#to-create-a-connector-security-map[To Create a Connector Security Map].
xref:reference-manual.adoc#create-connector-work-security-map[`create-connector-work-security-map`]::
  Creates a connector work security map for the specified resource
  adapter. Supported in remote mode only. For procedural information in
  this guide, see xref:connectors.adoc#to-create-a-connector-work-security-map[To Create a Connector Work
  Security Map].
xref:reference-manual.adoc#create-jdbc-resource[`create-jdbc-resource`]::
  Creates a new JDBC resource. Supported in remote mode only. For
  procedural information in this guide, see xref:jdbc.adoc#to-create-a-jdbc-resource[To
  Create a JDBC Resource].
xref:reference-manual.adoc#create-jdbc-connection-pool[`create-jdbc-connection-pool`]::
  Registers a new JDBC connection pool with the specified JDBC
  connection pool name. Supported in remote mode only. For procedural
  information in this guide, see xref:jdbc.adoc#to-create-a-jdbc-connection-pool[To Create a JDBC
  Connection Pool].
xref:reference-manual.adoc#create-resource-adapter-config[`create-resource-adapter-config`]::
  Creates configuration information for the connector module. Supported
  in remote mode only. For procedural information in this guide, see
  xref:connectors.adoc#to-create-configuration-information-for-a-resource-adapter[To Create Configuration Information for a
  Resource Adapter].
xref:reference-manual.adoc#delete-admin-object[`delete-admin-object`]::
  Deletes an administered object. For procedural information in this
  guide, see xref:connectors.adoc#to-delete-an-administered-object[To Delete an Administered
  Object].
xref:reference-manual.adoc#delete-connector-connection-pool[`delete-connector-connection-pool`]::
  Removes the connector connection pool specified using the
  `connector_connection_pool_name` operand. For procedural information
  in this guide, see xref:connectors.adoc#to-delete-a-connector-connection-pool[To Delete a Connector
  Connection Pool].
xref:reference-manual.adoc#delete-connector-resource[`delete-connector-resource`]::
  Deletes connector resource. For procedural information in this guide,
  see xref:connectors.adoc#to-delete-a-connector-resource[To Delete a Connector Resource].
xref:reference-manual.adoc#delete-connector-security-map[`delete-connector-security-map`]::
  Deletes a specified connector security map. Supported in remote mode
  only. For procedural information in this guide, see
  xref:connectors.adoc#to-delete-a-connector-security-map[To Delete a Connector Security Map].
xref:reference-manual.adoc#delete-connector-work-security-map[`delete-connector-work-security-map`]::
  Deletes a specified connector work security map. Supported in remote
  mode only. For procedural information in this guide, see
  xref:connectors.adoc#to-delete-a-connector-work-security-map[To Delete a Connector Work Security Map].
xref:reference-manual.adoc#delete-jdbc-connection-pool[`delete-jdbc-connection-pool`]::
  Deletes the specified JDBC connection pool. Supported in remote mode
  only. For procedural information in this guide, see
  xref:jdbc.adoc#to-delete-a-jdbc-connection-pool[To Delete a JDBC Connection Pool].
xref:reference-manual.adoc#delete-jdbc-resource[`delete-jdbc-resource`]::
  Deletes a JDBC resource. The specified JNDI name identifies the
  resource to be deleted. Supported in remote mode only. For procedural
  information in this guide, see xref:jdbc.adoc#to-delete-a-jdbc-resource[To Delete a JDBC
  Resource].
xref:reference-manual.adoc#delete-resource-adapter-config[`delete-resource-adapter-config`]::
  Deletes configuration information for the connector module. Supported
  in remote mode only. For procedural information in this guide, see
  xref:connectors.adoc#to-delete-a-resource-adapter-configuration[To Delete a Resource Adapter Configuration].
xref:reference-manual.adoc#flush-connection-pool[`flush-connection-pool`]::
  Reintializes all connections established in the specified connection.
  For procedural information in this guide, see xref:jdbc.adoc#to-reset-flush-a-connection-pool[To
  Reset (Flush) a Connection Pool].
xref:reference-manual.adoc#list-admin-objects[`list-admin-objects`]::
  Lists administered objects. For procedural information in this guide,
  see xref:connectors.adoc#to-list-administered-objects[To List Administered Objects].
xref:reference-manual.adoc#list-connector-connection-pools[`list-connector-connection-pools`]::
  Lists the connector connection pools that have been created. For
  procedural information in this guide, see xref:connectors.adoc#to-list-connector-connection-pools[To
  List Connector Connection Pools].
xref:reference-manual.adoc#list-connector-resources[`list-connector-resources`]::
  Creates connector resources. For procedural information in this guide,
  see xref:connectors.adoc#to-list-connector-resources[To List Connector Resources].
xref:reference-manual.adoc#list-connector-security-maps[`list-connector-security-maps`]::
  Lists the connector security maps belonging to a specified connector
  connection pool. For procedural information in this guide, see
  xref:connectors.adoc#to-list-connector-security-maps[To List Connector Security Maps].
xref:reference-manual.adoc#list-connector-work-security-maps[`list-connector-work-security-maps`]::
  Lists the existing connector work security maps for a resource
  adapter. Supported in remote mode only. For procedural information in
  this guide, see xref:connectors.adoc#to-list-connector-work-security-maps[To List Connector Work
  Security Maps].
xref:reference-manual.adoc#list-jdbc-connection-pools[`list-jdbc-connection-pools`]::
  Lists the existing JDBC connection pools. Supported in remote mode
  only. For procedural information in this guide, see
  xref:jdbc.adoc#to-list-jdbc-connection-pools[To List JDBC Connection Pools].
xref:reference-manual.adoc#list-jdbc-resources[`list-jdbc-resources`]::
  Lists the existing JDBC resources. Supported in remote mode only. For
  procedural information in this guide, see xref:jdbc.adoc#to-list-jdbc-resources[To List
  JDBC Resources].
xref:reference-manual.adoc#list-resource-adapter-configs[`list-resource-adapter-configs`]::
  Lists configuration information for the connector modules. Supported
  in remote mode only. For procedural information in this guide, see
  xref:connectors.adoc#to-list-resource-adapter-configurations[To List Resource Adapter Configurations].
xref:reference-manual.adoc#ping-connection-pool[`ping-connection-pool`]::
  Tests if a JDBC connection pool is usable. Supported in remote mode
  only. For procedural information in this guide, see
  xref:jdbc.adoc#to-contact-ping-a-connection-pool[To Contact (Ping) a Connection Pool].
xref:reference-manual.adoc#update-connector-security-map[`update-connector-security-map`]::
  Modifies a security map for the specified connector connection pool.
  For procedural information in this guide, see
  xref:connectors.adoc#to-update-a-connector-security-map[To Update a Connector Security Map].
xref:reference-manual.adoc#update-connector-work-security-map[`update-connector-work-security-map`]::
  Modifies a work security map that belongs to a specific resource
  adapter (connector module). For procedure information in this guide,
  see xref:connectors.adoc#to-update-a-connector-work-security-map[To Update a Connector Work Security
  Map].

[[domain-subcommands]]

=== Domain Subcommands

xref:reference-manual.adoc#backup-domain[`backup-domain`]::
  Describes how to back up a domain. Supported in local mode only. For
  procedural information in this guide, see xref:domains.adoc#to-back-up-a-domain[To
  Back Up a Domain].
xref:reference-manual.adoc#create-domain[`create-domain`]::
  Creates the configuration of a domain. A domain can exist independent
  of other domains. Any user who has access to the `asadmin` utility on
  a given host can create a domain and store its configuration in a
  location of choice. For procedural information in this guide, see
  xref:domains.adoc#to-create-a-domain[To Create a Domain].
xref:reference-manual.adoc#delete-domain[`delete-domain`]::
  Deletes the specified domain. The domain must be stopped before it can
  be deleted. For procedural information in this guide, see
  xref:domains.adoc#to-delete-a-domain[To Delete a Domain].
xref:reference-manual.adoc#list-backups[`list-backups`]::
  Lists the existing domain backups. Supported in local mode only. For
  procedural information in this guide, see xref:domains.adoc#to-list-domain-backups[To
  List Domain Backups].
xref:reference-manual.adoc#list-domains[`list-domains`]::
  Lists the existing domains and their statuses. If the domain directory
  is not specified, the domains in the domain-root-dir, the default for
  which is as-install``/domains``, are displayed. For procedural
  information in this guide, see xref:domains.adoc#to-list-domains[To List
  Domains].
xref:reference-manual.adoc#login[`login`]::
  Allows you to log in to a domain. For procedural information in this
  guide, see xref:domains.adoc#to-log-in-to-a-domain[To Log In to a Domain].
xref:reference-manual.adoc#restart-domain[`restart-domain`]::
  Restarts the Domain Administration Server (DAS) of the specified
  domain. Supported in remote mode only. For procedural information in
  this guide, see xref:domains.adoc#to-restart-a-domain[To Restart a Domain].
xref:reference-manual.adoc#restore-domain[`restore-domain`]::
  Recovers and domain from a backup file. Supported in local mode only.
  For procedural information in this guide, see
  xref:domains.adoc#to-restore-a-domain[To Restore a Domain].
xref:reference-manual.adoc#start-domain[`start-domain`]::
  Starts a domain. If the domain directory is not specified, the default
  `domain1` in the default domain-root-dir directory is started. If
  there are two or more domains, the domain_name operand must be
  specified. For procedural information in this guide, see
  xref:domains.adoc#to-start-a-domain[To Start a Domain].
xref:reference-manual.adoc#stop-domain[`stop-domain`]::
  Stops the domain administration server (DAS) of the specified domain.
  Supported in remote mode only. For procedural information in this
  guide, see xref:domains.adoc#to-stop-a-domain[To Stop a Domain].
xref:reference-manual.adoc#uptime[`uptime`]::
  Displays the length of time that the domain administration server
  (DAS) has been running since the last restart. Supported in remote
  mode only. For procedural information in this guide, see
  xref:domains.adoc#to-display-domain-uptime[To Display Domain Uptime].

[[internet-connectivity-subcommands]]

=== Internet Connectivity Subcommands

xref:reference-manual.adoc#create-http[`create-http`]::
  Creates a set of HTTP parameters for a protocol, which in turn
  configures one or more network listeners. Supported in remote mode
  only. For procedural information in this guide, see
  xref:http_https.adoc#to-create-an-http-configuration[To Create an HTTP Configuration].
xref:reference-manual.adoc#create-http-listener[`create-http-listener`]::
  Creates a new HTTP listener socket. Supported in remote mode only. For
  procedural information in this guide, see xref:http_https.adoc#to-create-an-internet-connection[To
  Create an Internet Connection].
xref:reference-manual.adoc#create-network-listener[`create-network-listener`]::
  Creates a new HTTP listener socket. Supported in remote mode only. For
  procedural information in this guide, see xref:http_https.adoc#to-create-an-internet-connection[To
  Create an Internet Connection].
xref:reference-manual.adoc#create-protocol[`create-protocol`]::
  Creates a protocol for a listener. Supported in remote mode only. For
  procedural information in this guide, see xref:http_https.adoc#to-create-a-protocol[To
  Create a Protocol].
xref:reference-manual.adoc#create-transport[`create-transport`]::
  Creates a transport for a listener. Supported in remote mode only. For
  procedural information in this guide, see xref:http_https.adoc#to-create-a-transport[To
  Create a Transport].
xref:reference-manual.adoc#create-virtual-server[`create-virtual-server`]::
  Creates the specified virtual server element. Supported in remote mode
  only. For procedural information in this guide, see
  xref:http_https.adoc#to-create-a-virtual-server[To Create a Virtual Server].
xref:reference-manual.adoc#create-ssl[`create-ssl`]::
  Creates and configures the SSL element in the selected HTTP listener
  to enable secure communication on that listener/service. Supported in
  remote mode only. For procedural information in this guide, see
  xref:http_https.adoc#to-configure-an-http-listener-for-ssl[To Configure an HTTP Listener for SSL].
xref:reference-manual.adoc#delete-http[`delete-http`]::
  Deletes an existing HTTP configuration. Supported in remote mode only.
  For procedural information in this guide, see
  xref:http_https.adoc#to-delete-an-http-configuration[To Delete an HTTP Configuration].
xref:reference-manual.adoc#delete-http-listener[`delete-http-listener`]::
  Deletes the specified HTTP listener. Supported in remote mode only.
  For procedural information in this guide, see
  xref:http_https.adoc#to-delete-an-http-network-listener[To Delete an HTTP Network Listener].
xref:reference-manual.adoc#delete-network-listener[`delete-network-listener`]::
  Deletes the specified HTTP listener. Supported in remote mode only.
  For procedural information in this guide, see
  xref:http_https.adoc#to-delete-an-http-network-listener[To Delete an HTTP Network Listener].
xref:reference-manual.adoc#delete-protocol[`delete-protocol`]::
  Deletes and existing HTTP protocol. Supported in remote mode only. For
  procedural information in this guide, see xref:http_https.adoc#to-delete-a-protocol[To
  Delete a Protocol].
xref:reference-manual.adoc#delete-ssl[`delete-ssl`]::
  Deletes the SSL element in the selected HTTP listener. Supported in
  remote mode only. For procedural information in this guide, see
  xref:http_https.adoc#to-delete-ssl-from-an-http-listener[To Delete SSL From an HTTP Listener].
xref:reference-manual.adoc#delete-transport[`delete-transport`]::
  Deletes and existing HTTP transport. Supported in remote mode only.
  For procedural information in this guide, see
  xref:http_https.adoc#to-delete-a-transport[To Delete a Transport].
xref:reference-manual.adoc#delete-virtual-server[`delete-virtual-server`]::
  Deletes the specified virtual server element. Supported in remote mode
  only. For procedural information in this guide, see
  xref:http_https.adoc#to-delete-a-virtual-server[To Delete a Virtual Server].
xref:reference-manual.adoc#list-http-listeners[`list-http-listeners`]::
  Lists the existing HTTP listeners. Supported in remote mode only. For
  procedural information in this guide, see xref:http_https.adoc#to-list-http-network-listeners[To
  List HTTP Network Listeners].
xref:reference-manual.adoc#list-network-listeners[`list-network-listeners`]::
  Lists the existing HTTP listeners. Supported in remote mode only. For
  procedural information in this guide, see xref:http_https.adoc#to-list-http-network-listeners[To
  List HTTP Network Listeners].
xref:reference-manual.adoc#list-protocols[`list-protocols`]::
  Lists the existing HTTP protocols. Supported in remote mode only. For
  procedural information in this guide, see xref:http_https.adoc#to-list-protocols[To
  List Protocols].
xref:reference-manual.adoc#list-transports[`list-transports`]::
  Lists the existing HTTP transports. Supported in remote mode only. For
  procedural information in this guide, see xref:http_https.adoc#to-list-transports[To
  List Transports].
xref:reference-manual.adoc#list-virtual-servers[`list-virtual-servers`]::
  Lists the existing virtual servers. Supported in remote mode only. For
  procedural information in this guide, see xref:http_https.adoc#to-list-virtual-servers[To
  List Virtual Servers].

[[jakarta-mail-subcommands]]

=== Jakarta Mail Subcommands

xref:reference-manual.adoc#create-mail-resource[`create-mail-resource`]::
  Creates a Jakarta Mail session resource. Supported in remote mode only.
  For procedural information in this guide, see
  xref:jakarta-mail.adoc#to-create-a-jakarta-mail-resource[To Create a Jakarta Mail Resource].
xref:reference-manual.adoc#delete-mail-resource[`delete-mail-resource`]::
  Deletes a Jakarta Mail session resource. Supported in remote mode only.
  For procedural information in this guide, see
  xref:jakarta-mail.adoc#to-delete-a-jakarta-mail-resource[To Delete a Jakarta Mail Resource].
xref:reference-manual.adoc#list-mail-resources[`list-mail-resources`]::
  Creates Jakarta Mail session resources. Supported in remote mode only. For
  procedural information in this guide, see xref:jakarta-mail.adoc#to-list-mail-resources[To
  List Jakarta Mail Resources].

[[jms-subcommands]]

=== JMS Subcommands

xref:reference-manual.adoc#create-jmsdest[`create-jmsdest`]::
  Creates a JMS physical destination. Along with the physical
  destination, you use the `create-jms-resource` subcommand to create a
  JMS destination resource that has a `Name` property that specifies the
  physical destination. Supported in remote mode only. For procedural
  information in this guide, see xref:jms.adoc#to-create-a-jms-physical-destination[To Create a JMS
  Physical Destination].
xref:reference-manual.adoc#create-jms-host[`create-jms-host`]::
  Creates a JMS host within the JMS service. Supported in remote mode
  only. For procedural information in this guide, see
  xref:jms.adoc#to-create-a-jms-host[To Create a JMS Host].
xref:reference-manual.adoc#create-jms-resource[`create-jms-resource`]::
  Creates a JMS connection factory resource or JMS destination resource.
  Supported in remote mode only. Supported in remote mode only. For
  procedural information in this guide, see xref:jms.adoc#to-create-a-connection-factory-or-destination-resource[To Create
  a Connection Factory or Destination Resource].
xref:reference-manual.adoc#delete-jmsdest[`delete-jmsdest`]::
  Removes the specified JMS destination. Supported in remote mode only.
  For procedural information in this guide, see xref:jms.adoc#to-delete-a-jms-physical-destination[To
  Delete a JMS Physical Destination].
xref:reference-manual.adoc#delete-jms-host[`delete-jms-host`]::
  Deletes a JMS host within the JMS service. Supported in remote mode
  only. For procedural information in this guide, see
  xref:jms.adoc#to-delete-a-jms-host[To Delete a JMS Host].
xref:reference-manual.adoc#delete-jms-resource[`delete-jms-resource`]::
  Deletes a JMS connection factory resource or JMS destination resource.
  Supported in remote mode only. For procedural information in this
  guide, see xref:jms.adoc#to-delete-a-connection-factory-or-destination-resource[To Delete a Connection Factory or
  Destination Resource].
xref:reference-manual.adoc#flush-jmsdest[`flush-jmsdest`]::
  Purges the messages from a physical destination in the specified JMS
  Service configuration of the specified target. Supported in remote
  mode only. For procedural information in this guide, see
  xref:jms.adoc#to-purge-messages-from-a-physical-destination[To Purge Messages From a Physical Destination].
xref:reference-manual.adoc#jms-ping[`jms-ping`]::
  Checks if the JMS service (also known as the JMS provider) is up and
  running. Supported in remote mode only. For procedural information in
  this guide, see xref:jms.adoc#troubleshooting-the-jms-service[Troubleshooting the JMS Service].
xref:reference-manual.adoc#list-jmsdest[`list-jmsdest`]::
  Lists the JMS physical destinations. Supported in remote mode only.
  For procedural information in this guide, see xref:jms.adoc#to-list-jms-physical-destinations[To
  List JMS Physical Destinations].
xref:reference-manual.adoc#list-jms-hosts[`list-jms-hosts`]::
  Lists the existing JMS hosts. Supported in remote mode only. For
  procedural information in this guide, see xref:jms.adoc#to-list-jms-hosts[To List
  JMS Hosts].
xref:reference-manual.adoc#list-jms-resources[`list-jms-resources`]::
  Lists the existing JMS connection factory or destination resources.
  Supported in remote mode only. For procedural information in this
  guide, see xref:jms.adoc#to-list-jms-resources[To List JMS Resources].

[[jndi-subcommands]]

=== JNDI Subcommands

xref:reference-manual.adoc#create-custom-resource[`create-custom-resource`]::
  Creates a custom JNDI resource. Supported in remote mode only. For
  procedural information in this guide, see xref:jndi.adoc#to-create-a-custom-jndi-resource[To
  Create a Custom JNDI Resource].
xref:reference-manual.adoc#create-jndi-resource[`create-jndi-resource`]::
  Creates an external JNDI resource. Supported in remote mode only. For
  procedural information in this guide, see xref:jndi.adoc#to-register-an-external-jndi-resource[To
  Register an External JNDI Resource].
xref:reference-manual.adoc#delete-custom-resource[`delete-custom-resource`]::
  Deletes a custom JNDI resource. Supported in remote mode only. For
  procedural information in this guide, see xref:jndi.adoc#to-delete-a-custom-jndi-resource[To
  Delete a Custom JNDI Resource].
xref:reference-manual.adoc#delete-jndi-resource[`delete-jndi-resource`]::
  Deletes an external JNDI resource. Supported in remote mode only. For
  procedural information in this guide, see xref:jndi.adoc#to-delete-an-external-jndi-resource[To
  Delete an External JNDI Resource].
xref:reference-manual.adoc#list-custom-resources[`list-custom-resources`]::
  Lists the existing custom JNDI resources. Supported in remote mode
  only. For procedural information in this guide, see
  xref:jndi.adoc#to-list-custom-jndi-resources[To List Custom JNDI Resources].
xref:reference-manual.adoc#list-jndi-entries[`list-jndi-entries`]::
  Lists the entries in the JNDI tree. Supported in remote mode only. For
  procedural information in this guide, see xref:jndi.adoc#to-list-external-jndi-entries[To List
  External JNDI Entries],
xref:reference-manual.adoc#list-jndi-resources[`list-jndi-resources`]::
  Lists the existing external JNDI resources. Supported in remote mode
  only. For procedural information in this guide, see
  xref:jndi.adoc#to-list-external-jndi-resources[To List External JNDI Resources].

[[jvm-subcommands]]

=== JVM Subcommands

xref:reference-manual.adoc#create-jvm-options[`create-jvm-options`]::
  Creates a JVM option in the Java configuration or profiler elements of
  the `domain.xml` file. Supported in remote mode only. For procedural
  information in this guide, see xref:jvm.adoc#to-create-jvm-options[To Create JVM
  Options].
xref:reference-manual.adoc#create-profiler[`create-profiler`]::
  Creates a profiler element. Supported in remote mode only. For
  procedural information in this guide, see xref:jvm.adoc#to-create-a-profiler[To Create
  a Profiler].
xref:reference-manual.adoc#delete-jvm-options[`delete-jvm-options`]::
  Deletes the specified JVM option from the Java configuration or
  profiler elements of the `domain.xml` file. Supported in remote mode
  only. For procedural information in this guide, see
  xref:jvm.adoc#to-delete-jvm-options[To Delete JVM Options].
xref:reference-manual.adoc#delete-profiler[`delete-profiler`]::
  Deletes the specified profiler element. Supported in remote mode only.
  For procedural information in this guide, see xref:jvm.adoc#to-delete-a-profiler[To
  Delete a Profiler].
xref:reference-manual.adoc#generate-jvm-report[`generate-jvm-report`]::
  Generates a report showing the threads, classes, and memory for the
  virtual machine that runs {productName}. For procedural information
  in this guide, see xref:jvm.adoc#to-generate-a-jvm-report[To Generate a JVM Report].
xref:reference-manual.adoc#list-jvm-options[`list-jvm-options`]::
  Lists the command-line options that are passed to the Java application
  launcher when {productName} is started. Supported in remote mode
  only. For procedural information in this guide, see
  xref:jvm.adoc#to-list-jvm-options[To List JVM Options].

[[life-cycle-module-subcommands]]

=== Life Cycle Module Subcommands

xref:reference-manual.adoc#create-lifecycle-module[`create-lifecycle-module`]::
  Creates a new life cycle module. Supported in remote mode only. For
  procedural information in this guide, see
  xref:lifecycle-modules.adoc#to-create-a-life-cycle-module[To Create a Life Cycle Module].
xref:reference-manual.adoc#list-lifecycle-modules[`list-lifecycle-modules`]::
  Lists life cycle modules. Supported in remote mode only. For
  procedural information in this guide, see
  xref:lifecycle-modules.adoc#to-list-life-cycle-modules[To List Life Cycle Modules].
xref:reference-manual.adoc#delete-lifecycle-module[`delete-lifecycle-module`]::
  Deletes an existing life cycle module. Supported in remote mode only.
  For procedural information in this guide, see
  xref:lifecycle-modules.adoc#to-delete-a-life-cycle-module[To Delete a Life Cycle Module].

[[logging-and-monitoring-subcommands]]

=== Logging and Monitoring Subcommands

xref:reference-manual.adoc#collect-log-files[`collect-log-files`]::
  Collects all available log files and creates a ZIP archive. Supported
  in remote mode only. For procedural information in this guide, see
  xref:logging.adoc#to-collect-log-files-into-a-zip-archive[To Collect Log Files into a ZIP Archive].
xref:reference-manual.adoc#disable-monitoring[`disable-monitoring`]::
  Disables the monitoring service. Supported in remote mode only. For
  procedural information in this guide, see xref:monitoring.adoc#to-disable-monitoring[To
  Disable Monitoring].
xref:reference-manual.adoc#enable-monitoring[`enable-monitoring`]::
  Enables the monitoring service. Supported in remote mode only. For
  procedural information in this guide, see xref:monitoring.adoc#to-enable-monitoring[To
  Enable Monitoring].
xref:reference-manual.adoc#list-log-attributes[`list-log-attributes`]::
  Lists log file attributes. Supported in remote mode only. For
  procedural information in this guide, see
  xref:logging.adoc#configuring[Configuring the Logging Service].
xref:reference-manual.adoc#list-log-levels[`list-log-levels`]::
  Lists the existing loggers. Supported in remote mode only.
  For procedural information in this guide,
  see xref:logging.adoc#to-list-log-levels[To List Log Levels].
xref:reference-manual.adoc#list-loggers[`list-loggers`]::
  Lists all public loggers in your distribution of {productName}. Internal loggers are not listed. For procedural
  information in this guide, see xref:logging.adoc#to-list-loggers[To List Loggers].
xref:reference-manual.adoc#monitor[`monitor`]::
  Displays monitoring information for the common {productName}
  resources. Supported in remote mode only. For procedural information
  in this guide, see xref:monitoring.adoc#to-view-common-monitoring-data[To View Common Monitoring
  Data].
xref:reference-manual.adoc#rotate-log[`rotate-log`]::
  Rotates the `server.log` file and stores the old data in a
  time-stamped file. Supported in remote mode only. For procedural
  information in this guide, see xref:logging.adoc#to-rotate-log-files-manually[To Rotate Log Files Manually].
xref:reference-manual.adoc#set-log-attributes[`set-log-attributes`]::
  Sets log file attributes. Supported in remote mode only. For
  procedural information in this guide, see
  xref:logging.adoc#configuring[Configuring the Logging Service].
xref:reference-manual.adoc#set-log-file-format[`set-log-file-format`]::
  Sets the formatter used to format log records in log files. For
  procedural information in this guide, see
  xref:logging.adoc#setting-the-log-file-format[Setting the Log File Format].
xref:reference-manual.adoc#set-log-levels[`set-log-levels`]::
  Sets the log level for a module. Supported in remote mode only. For
  procedural information in this guide, see
  xref:logging.adoc#setting-log-levels[Setting Log Levels].

[[orb-subcommands]]

=== ORB Subcommands

xref:reference-manual.adoc#create-iiop-listener[`create-iiop-listener`]::
  Creates an IIOP listener. Supported in remote mode only. For
  procedural information in this guide, see xref:orb.adoc#to-create-an-iiop-listener[To Create
  an IIOP Listener].
xref:reference-manual.adoc#delete-iiop-listener[`delete-iiop-listener`]::
  Deletes an IIOP listener. Supported in remote mode only. For
  procedural information in this guide, see xref:orb.adoc#to-delete-an-iiop-listener[To Delete
  an IIOP Listener].
xref:reference-manual.adoc#list-iiop-listeners[`list-iiop-listeners`]::
  Lists the existing IIOP listeners. Supported in remote mode only. For
  procedural information in this guide, see xref:orb.adoc#to-list-iiop-listeners[To List
  IIOP Listeners].

[[thread-pool-subcommands]]

=== Thread Pool Subcommands

xref:reference-manual.adoc#create-threadpool[`create-threadpool`]::
  Creates a new thread pool. Supported in remote mode only. For
  procedural information in this guide, see
  xref:threadpools.adoc#to-create-a-thread-pool[To Create a Thread Pool].
xref:reference-manual.adoc#delete-threadpool[`delete-threadpool`]::
  Deletes the specified thread pool. Supported in remote mode only. For
  procedural information in this guide, see
  xref:threadpools.adoc#to-delete-a-thread-pool[To Delete a Thread Pool].
xref:reference-manual.adoc#list-threadpools[`list-threadpools`]::
  Lists the existing thread pools. Supported in remote mode only. For
  procedural information in this guide, see
  xref:threadpools.adoc#to-list-thread-pools[To List Thread Pools].

[[transaction-service-subcommands]]

=== Transaction Service Subcommands

xref:reference-manual.adoc#freeze-transaction-service[`freeze-transaction-service`]::
  Freezes the transaction subsystem during which time all the in-flight
  transactions are suspended. Supported in remote mode only. For
  procedural information, see xref:transactions.adoc#to-stop-the-transaction-service[To Stop the
  Transaction Service].
xref:reference-manual.adoc#recover-transactions[`recover-transactions`]::
  Manually recovers pending transactions. Supported in remote mode only.
  For procedural information, see xref:transactions.adoc#to-manually-recover-transactions[To
  Manually Recover Transactions].
xref:reference-manual.adoc#rollback-transaction[`rollback-transaction`]::
  Rolls back the named transaction. Supported in remote mode only. For
  procedural information, see xref:transactions.adoc#to-roll-back-a-transaction[To Roll Back a
  Transaction].
xref:reference-manual.adoc#unfreeze-transaction-service[`unfreeze-transaction-service`]::
  Resumes all the suspended in-flight transactions. Invoke this
  subcommand on an already frozen transaction. Supported in remote mode
  only. For procedural information, see xref:transactions.adoc#to-restart-the-transaction-service[To
  Restart the Transaction Service].


