type=page
status=published
title=Uninstalling GlassFish Server 7
prev=installing.html
~~~~~~

Uninstalling GlassFish Server 7
=================================

[[GSING00003]][[ghmlt]]


[[uninstalling-glassfish-server-5.0]]
2 Uninstalling GlassFish Server 7
-----------------------------------

This chapter describes how to uninstall GlassFish Server Open Source
Edition 7 software.

[[gjxfv]][[GSING00028]][[removing-a-glassfish-server-installation]]

Removing a GlassFish Server Installation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This section describes how to remove GlassFish Server Open Source
Edition 7 software.

The following topics are addressed here:

* link:#gkrfi[To Uninstall GlassFish Server Software After a ZIP File
Installation]

[[gkrfi]][[GSING00012]][[to-uninstall-glassfish-server-software-after-a-zip-file-installation]]

To Uninstall GlassFish Server Software After a ZIP File Installation
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This procedure describes how to uninstall GlassFish Server software that
was installed using a ZIP file, as described in
link:installing.html#ghmxb[Installing GlassFish Server From a ZIP File].

Before You Begin

Stop all domains and other related processes, including command prompts
using the installation directory or its subdirectories and any
applications using Java SE files.

To stop domains, use the `asadmin stop-domain` command. For more
information about stopping a domain, see
"link:../administration-guide/domains.html#GSADG00336[To Stop a Domain]"
in GlassFish Server Open Source Edition Administration Guide.

If orphaned processes remain, identify and terminate the processes as follows:

* Solaris, Linux, and Mac OS X systems:
+
Use the `ps -ef` command and terminate the processes using the `kill` command.
* Windows systems:
+
Use the Task Manager and terminate the processes.

Also see "link:../release-notes/release-notes.html#GSRLN00253[Known Issues]"
in GlassFish Server Open Source Edition Release Notes for known issues related to uninstallation.

1. Save any files in the installation directory that you may want to keep.
2. Manually delete installation directory and all its contents.

