<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2021, 2026 Contributors to Eclipse Foundation.
    Copyright (c) 1997, 2021 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.glassfish.main.web</groupId>
        <artifactId>web</artifactId>
        <version>8.0.5-SNAPSHOT</version>
    </parent>

    <artifactId>weld-integration-fragment</artifactId>
    <packaging>glassfish-jar</packaging>

    <name>Weld Integration Fragment</name>
    <description>This fragment bundle extends the weld osgi bundle to export additional packages from the weld-osgi-bundle as they are used in Weld generated proxies</description>

    <developers>
        <developer>
            <id>sivakumart</id>
            <name>Sivakumar Thyagarajan</name>
            <organization>Oracle, Inc.</organization>
            <roles>
                <role>developer</role>
            </roles>
        </developer>
    </developers>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <configuration>
                    <instructions>
                        <Bundle-Description>${project.description}</Bundle-Description>
                        <Bundle-ManifestVersion>2</Bundle-ManifestVersion>
                        <Bundle-SymbolicName>${project.groupId}.${project.artifactId}</Bundle-SymbolicName>
                        <Fragment-Host>org.jboss.weld.osgi-bundle;bundle-version=${weld.version}</Fragment-Host>
                        <Export-Package>
                            javassist.util.proxy,
                            org.jboss.weld.annotated.enhanced,
                            org.jboss.weld.annotated.slim,
                            org.jboss.weld.annotated.slim.backed,
                            org.jboss.weld.bean.builtin.ee,
                            org.jboss.weld.bean.proxy.util,
                            org.jboss.weld.context.http,
                            org.jboss.weld.contexts,
                            org.jboss.weld.contexts.bound,
                            org.jboss.weld.contexts.cache,
                            org.jboss.weld.injection.attributes,
                            org.jboss.weld.injection.producer,
                            org.jboss.weld.interceptor.proxy,
                            org.jboss.weld.interceptor.util.proxy,
                            org.jboss.weld.proxy.util,
                            org.jboss.weld.security,
                            org.jboss.weld.serialization,
                            org.jboss.weld.util.bean,
                            org.jboss.weld.util.collections
                        </Export-Package>
                        <Import-Package>org.glassfish.weld</Import-Package>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
