type=page
status=published
title=delete-managed-executor-service
next=delete-managed-scheduled-executor-service.html
prev=delete-local-instance.html
~~~~~~
delete-managed-executor-service
===============================

[[delete-managed-executor-service-1]][[GSRFM848]][[delete-managed-executor-service]]

delete-managed-executor-service
-------------------------------

removes a managed executor service resource with the specified JNDI name

[[sthref850]]

Synopsis

[source,oac_no_warn]
----
asadmin [asadmin-options] delete-managed-executor-service [--help]
[--target target]
managed_executor_service_name
----

[[sthref851]]

Description

The `delete-managed-executor-service` subcommand removes a managed
executor service resource with the specified JNDI name.

This subcommand is supported in remote mode only.

[[sthref852]]

Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the link:asadmin.html#asadmin-1m[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target from which you are deleting the resource. Valid
  targets are: +
  `server`;;
    Deletes the resource from the default server instance. This is the
    default value.
  `domain`;;
    Deletes the resource from the domain.
  cluster_name;;
    Deletes the resource from every server instance in the specified
    cluster.
  instance_name;;
    Deletes the resource from the specified server instance.

[[sthref853]]

Operands

managed_executor_service_name::
  The JNDI name of the resource to be deleted.

[[sthref854]]

Examples

[[GSRFM849]][[sthref855]]

Example 1   Deleting a Managed Executor Service Resource

This example deletes the managed executor service resource named
`concurrent/myExecutor`.

[source,oac_no_warn]
----
asadmin> delete-managed-executor-service concurrent/myExecutor
Managed executor service concurrent/myExecutor deleted successfully.
Command delete-managed-executor-service executed successfully.
----

[[sthref856]]

Exit Status

0::
  command executed successfully
1::
  error in executing the command

[[sthref857]]

See Also

link:asadmin.html#asadmin-1m[`asadmin`(1M)]

link:create-managed-executor-service.html#create-managed-executor-service-1[`create-managed-executor-service`(1)],
link:list-managed-executor-services.html#list-managed-executor-services-1[`list-managed-executor-services`(1)]


