type=page
status=published
title=delete-connector-connection-pool
next=delete-connector-resource.html
prev=delete-config.html
~~~~~~

delete-connector-connection-pool
================================

[[delete-connector-connection-pool-1]][[GSRFM00070]][[delete-connector-connection-pool]]

delete-connector-connection-pool
--------------------------------

Removes the specified connector connection pool

[[sthref625]]

=== Synopsis

[source]
----
asadmin [asadmin-options] delete-connector-connection-pool [--help]
[--target target]
[--cascade={false|true}] poolname
----

[[sthref626]]

=== Description

The `delete-connector-connection-pool` subcommand removes the specified
connector connection pool.

This subcommand is supported in remote mode only.

[[sthref627]]

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the link:asadmin.html#asadmin-1m[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Do not specify this option. This option is retained for compatibility
  with earlier releases. If you specify this option, a syntax error does
  not occur. Instead, the subcommand runs successfully and displays a
  warning message that the option is ignored.
`--cascade`::
  When set to true, all connector resources associated with the pool,
  and the pool itself, are deleted. When set to false, the deletion of
  pool fails if any resources are associated with the pool. The resource
  must be deleted explicitly or the option must be set to true. Default
  is false.

[[sthref628]]

=== Operands

poolname::
  The name of the connection pool to be removed.

[[sthref629]]

=== Examples

[[GSRFM537]][[sthref630]]

==== Example 1   Deleting a Connector Connection Pool

This example deletes the connector connection pool named
`jms/qConnPool`.

[source]
----
asadmin> delete-connector-connection-pool
--cascade=false jms/qConnPool
Command delete-connector-connection-pool executed successfully
----

[[sthref631]]

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

[[sthref632]]

=== See Also

link:asadmin.html#asadmin-1m[`asadmin`(1M)]

link:create-connector-connection-pool.html#create-connector-connection-pool-1[`create-connector-connection-pool`(1)],
link:list-connector-connection-pools.html#list-connector-connection-pools-1[`list-connector-connection-pools`(1)],
link:ping-connection-pool.html#ping-connection-pool-1[`ping-connection-pool`(1)]


