type=page
status=published
title=instance
next=logging.html
prev=dotted-names.html
~~~~~~

instance
========

[[instance-5asc]][[GSRFM00269]][[instance]]

instance
--------

An instance in {productName} has its own Jakarta EE configuration, Java
EE resources, application deployment areas, and server configuration
settings

[[sthref2403]]

=== Description

{productName} creates one server instance, called `server` at the
time of installation. You can delete the server instance and create a
new instance with a different name.

For many users, one server instance meets their needs. However,
depending upon your environment, you might want to create additional
server instances. For example, in a development environment you can use
different server instances to test different {productName}
configurations, or to compare and test different application
deployments. Because you can easily add or delete a server instance, you
can use them to create temporary "sandbox" areas to experiment with
while developing.


