type=page
status=published
title=list-connector-work-security-maps
next=list-containers.html
prev=list-connector-security-maps.html
~~~~~~
list-connector-work-security-maps
=================================

[[list-connector-work-security-maps-1]][[GSRFM00160]][[list-connector-work-security-maps]]

list-connector-work-security-maps
---------------------------------

lists the work security maps belonging to the specified resource adapter

[[sthref1430]]

Synopsis

[source,oac_no_warn]
----
asadmin [asadmin-options] list-connector-work-security-maps [--help] 
[--securitymap securitymap]
resource_adapter_name
----

[[sthref1431]]

Description

The `list-connector-work-security-maps` subcommand lists the work
security maps belonging to the specified resource adapter.

This subcommand is supported in remote mode only.

[[sthref1432]]

Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the link:asadmin.html#asadmin-1m[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--securitymap`::
  Specifies the name of the security map contained within the resource
  adapter from which the identity and principals should be listed.

[[sthref1433]]

Operands

resource_adapter_name::
  The name of the resource adapter for which you want to list security
  maps.

[[sthref1434]]

Examples

[[GSRFM652]][[sthref1435]]

Example 1   Listing Connector Work Security Maps

This example lists the current connector work security maps for the
resource adapter named `my_resource_adapter`.

[source,oac_no_warn]
----
asadmin> list-connector-work-security-maps my_resource_adapter
workSecurityMap1: EIS principal=eis-principal-2, mapped principal=server-principal-2
workSecurityMap1: EIS principal=eis-principal-1, mapped principal=server-principal-1
workSecurityMap2: EIS principal=eis-principal-2, mapped principal=server-principal-2
workSecurityMap2: EIS principal=eis-principal-1, mapped principal=server-principal-1
Command list-connector-work-security-maps executed successfully.
----

[[sthref1436]]

Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

[[sthref1437]]

See Also

link:asadmin.html#asadmin-1m[`asadmin`(1M)]

link:create-connector-work-security-map.html#create-connector-work-security-map-1[`create-connector-work-security-map`(1)],
link:delete-connector-work-security-map.html#delete-connector-work-security-map-1[`delete-connector-work-security-map`(1)],
link:update-connector-work-security-map.html#update-connector-work-security-map-1[`update-connector-work-security-map`(1)]


