type=page
status=published
title=Eclipse GlassFish Server Reference Manual, Release 7
next=preface.html
prev=toc.html
~~~~~~
Eclipse GlassFish Server Reference Manual, Release 7
======================================================

[[eclipse-glassfish-server]]
Eclipse GlassFish Server
------------------------

Reference Manual

Release 7

Contributed 2018, 2019

This reference manual describes administration commands and utility
commands that are available with Eclipse GlassFish Server
5.1. This reference manual also describes concepts that are related to
\{product---name} administration.

The available options, arguments, and operands for each command are
provided in accordance with standard rules of command syntax, along with
availability attributes, diagnostic information, and cross-references to
other manual pages and reference material with relevant information.

This reference manual is for all users of GlassFish Server Open Source
Edition.

[[sthref1]]

'''''

Eclipse GlassFish Server Reference Manual, Release 7

Copyright © 2013, 2019 Oracle and/or its affiliates. All rights reserved.

This program and the accompanying materials are made available under the 
terms of the Eclipse Public License v. 2.0, which is available at 
http://www.eclipse.org/legal/epl-2.0. 

SPDX-License-Identifier: EPL-2.0

Oracle and Java are registered trademarks of Oracle and/or its 
affiliates. Other names may be trademarks of their respective owners. 

Intel and Intel Xeon are trademarks or registered trademarks of Intel 
Corporation. All SPARC trademarks are used under license and are 
trademarks or registered trademarks of SPARC International, Inc. AMD, 
Opteron, the AMD logo, and the AMD Opteron logo are trademarks or 
registered trademarks of Advanced Micro Devices. UNIX is a registered 
trademark of The Open Group. 
