type=page
status=published
title=update-connector-work-security-map
next=update-file-user.html
prev=update-connector-security-map.html
~~~~~~
update-connector-work-security-map
==================================

[[update-connector-work-security-map-1]][[GSRFM00253]][[update-connector-work-security-map]]

update-connector-work-security-map
----------------------------------

modifies a work security map for the specified resource adapter

[[sthref2266]]

Synopsis

[source,oac_no_warn]
----
asadmin [asadmin-options] update-connector-work-security-map [--help] 
--raname raname
[--addprincipals eis-principal1=server-principal1[, eis-principal2=server-principal2]*] 
[--addgroups eis-group1=server-group1[, eis-group2=server-group2]*]
[--removeprincipals eis-principal1[,eis-principal2]*]
[--removegroups eis-group1[, eis-group2]*]
mapname
----

[[sthref2267]]

Description

The `update-connector-work-security-map` subcommand modifies a security
map for the specified resource adapter.

This subcommand is supported in remote mode only.

[[sthref2268]]

Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the link:asadmin.html#asadmin-1m[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--addgroups`::
  Specifies a comma-separated list of EIS groups to be added. Use either
  the `--addprincipals` option or the `--addgroups` option, but not
  both.
`--addprincipals`::
  Specifies a comma-separated list of EIS-specific principals to be
  added. Use either the `--addprincipals` option or the `--addgroups`
  option, but not both.
`--removegroups`::
  Specifies a comma-separated list of EIS groups to be removed.
`--removeprincipals`::
  Specifies a comma-separated list of EIS-specific principals to be
  removed.
`--raname`::
  Indicates the connector module name with which the work security map
  is associated.

[[sthref2269]]

Operands

mapname::
  The name of the work security map to be updated.

[[sthref2270]]

Examples

[[GSRFM786]][[sthref2271]]

Example 1   Updating a Connector Work Security Map

This example updates `workSecurityMap2` by removing `eis-group-2`.

[source,oac_no_warn]
----
asadmin> update-connector-work-security-map
--raname my-resource-adapter --removegroups eis-group-2 workSecurityMap2
Command update-connector-work-security-map executed successfully.
----

[[sthref2272]]

Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

[[sthref2273]]

See Also

link:asadmin.html#asadmin-1m[`asadmin`(1M)]

link:create-connector-work-security-map.html#create-connector-work-security-map-1[`create-connector-work-security-map`(1)],
link:delete-connector-work-security-map.html#delete-connector-work-security-map-1[`delete-connector-work-security-map`(1)],
link:list-connector-work-security-maps.html#list-connector-work-security-maps-1[`list-connector-work-security-maps`(1)]


