type=page
status=published
title=uptime
next=validate-dcom.html
prev=update-password-alias.html
~~~~~~

= uptime

[[uptime-1]][[GSRFM00258]][[uptime]]

== uptime

Returns the length of time that the DAS has been running

[[sthref2316]]

=== Synopsis

[source]
----
asadmin [asadmin-options] uptime [--help]
----

[[sthref2317]]

=== Description

The `uptime` subcommand returns the length of time that the domain
administration server (DAS) has been running since it was last
restarted.

This subcommand is supported in remote mode only.

[[sthref2318]]

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the link:asadmin.html#asadmin-1m[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[sthref2319]]

=== Examples

[[GSRFM795]][[sthref2320]]

==== Example 1   Showing How Long the DAS Has Been Running

This example shows the length of time that the DAS has been running.

[source]
----
asadmin> uptime
Uptime: 2 days, 1 hours, 30 minutes, 18 seconds, Total milliseconds: 178218706
Command uptime executed successfully.
----

[[sthref2321]]

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

[[sthref2322]]

=== See Also

link:asadmin.html#asadmin-1m[`asadmin`(1M)]

link:list-domains.html#list-domains-1[`list-domains`(1)],
link:start-domain.html#start-domain-1[`start-domain`(1)],
link:stop-domain.html#stop-domain-1[`stop-domain`(1)]


