#!/bin/bash
#
# Copyright (c) 2010, 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0, which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# This Source Code may also be made available under the following Secondary
# Licenses when the conditions for such availability set forth in the
# Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
# version 2 with the GNU Classpath Exception, which is available at
# https://www.gnu.org/software/classpath/license.html.
#
# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
#

PWD=`dirname $0`
PWD=`dirname $0`
cd src/main/java
javadoc -d ../../../javadoc -exclude org.glassfish.config:org.glassfish.admingui:org.glassfish.amx:org.glassfish.branding:org.glassfish.container:org.glassfish.content:org.glassfish.deployment:org.glassfish.embedded:org.glassfish.event:org.glassfish.invocation:org.glassfish.logging:org.glassfish.monitoring:org.glassfish.naming:org.glassfish.tests -linksource org/glassfish/api/admin/cli/*.java
cd $PWD
