/*
 * Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

package Data;

import jakarta.ejb.*;

/**
 * Created Dec 16, 2002 2:08:21 PM
 * Code generated by the Forte For Java EJB Builder
 * @author mvatkina
 */

public interface SPSession extends jakarta.ejb.EJBObject {

    public int checkAllParts() throws java.rmi.RemoteException;

    public int checkAllSuppliers() throws java.rmi.RemoteException;

    public void createPartsAndSuppliers() throws java.rmi.RemoteException;

    public void removePart(java.lang.Integer partid) throws java.rmi.RemoteException;

    public void removeSupplier(java.lang.Integer partid, java.lang.Integer supplierid) throws java.rmi.RemoteException;

}

