#!/bin/bash
#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
# Copyright (c) 2011, 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0, which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# This Source Code may also be made available under the following Secondary
# Licenses when the conditions for such availability set forth in the
# Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
# version 2 with the GNU Classpath Exception, which is available at
# https://www.gnu.org/software/classpath/license.html.
#
# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
#

AS_CONFIG="${S1AS_HOME}/config"
AS_CONFIG_SH="${AS_CONFIG}/config.sh"
source "${AS_CONFIG_SH}" "$AS_CONFIG" || { echo "${AS_CONFIG_SH} not found" >&2; exit 1; }

# Submits an app client for execution using Java Web Start
#
# Accepts the same command options as the appclient script so the test
# files can continue to invoke the appclient using the ${APPCLIENT}
# property substitution.
#
# This script runs a Java program to compute the URL to invoke the app client using
# Java Web Start. The program then returns a javaws command which launches the
# app client.

eval `"${JAVA}" -classpath "${APS_HOME}/lib/javaws-util.jar" util.LaunchJavaWS "$@"`
