type=page
status=published
title={productName} 7 Embedded Server Guide
prev=preface.html
~~~~~~

[[GSESG]]
== {productName} 7 Embedded Server Guide

This document explains how to run applications with embedded {productName} and to develop applications in which
{productName} is embedded. This document is for software developers
who are developing applications to run in embedded {productName}. The
ability to program in the Java language is assumed.

The following topics are addressed here:

* xref:#introduction-to-embedded-glassfish-server[Introduction to Embedded {productName}]
* xref:#embedded-glassfish-server-file-system[Embedded {productName} File System]
* xref:#including-the-glassfish-server-embedded-server-api-in-applications[Including the {productName} Embedded Server API in Applications]
* xref:#testing-applications-with-the-maven-plug-in-for-embedded-glassfish-server[Testing Applications with the Maven Plug-in for Embedded {productName}]
* xref:#GSESG00039[Using the EJB 3.1 Embeddable API with Embedded {productName}]
* xref:#changing-log-levels-in-embedded-glassfish-server[Changing Log Levels in Embedded {productName}]
* xref:#default-java-persistence-data-source-for-embedded-glassfish-server[Default Java Persistence Data Source for Embedded {productName}]
* xref:#restrictions-for-embedded-glassfish-server[Restrictions for Embedded {productName}]

[[introduction-to-embedded-glassfish-server]]

== Introduction to Embedded {productName}

Embedded {productName} enables you to use
{productName} as a library or run applications from command line. Embedded {productName} also enables
you to run {productName} inside any Virtual Machine for the Java
platform (Java Virtual Machine or JVMmachine).

No installation or configuration of embedded {productName} is
required. The ability to run {productName}
without installation or configuration simplifies the process of bundling
{productName} with applications or running applications from command line.


You can use embedded {productName} in the following ways:

* With the Embedded Server API (see xref:#including-the-glassfish-server-embedded-server-api-in-applications[Including the {productName} Embedded Server API in Applications])
* As an executable JAR, executed with `java -jar` (see xref:#running-from-command-line[Running {productName} Embedded Server from Command Line])
* With the Maven Plug-in (see xref:#testing-applications-with-the-maven-plug-in-for-embedded-glassfish-server[Testing Applications with the
Maven Plug-in for Embedded {productName}])
* With the EJB 3.1 Embeddable API (see xref:#GSESG00039[Using the EJB 3.1
Embeddable API with Embedded {productName}])

Embedded {productName} provides a plug-in for
http://maven.apache.org/[Apache Maven] (`http://maven.apache.org/`).
This plug-in simplifies the testing of applications by enabling you to
build an application and run it with {productName} on a single
system. Testing and debugging are simplified because the need for an
installed and configured {productName} is eliminated. Therefore, you
can run unit tests automatically in every build.


[NOTE]
====
For information on how to embed {productName} in an OSGi environment,
see the xref:add-on-component-development-guide.adoc#GSACG[{productName} Add-On
Component Development Guide].
====

[[editions]]

== Embedded {productName} Editions

Embedded {productName} comes with the following flavours:

`glassfish-embedded-all.jar`::
  Contains classes needed for deploying all Jakarta EE application types.
  Download this file from
  `https://central.sonatype.com/artifact/org.glassfish.main.extras/glassfish-embedded-all`.
`glassfish-embedded-web.jar`::
  Contains classes needed for deploying Jakarta EE web applications.
  Download this file from
  `https://central.sonatype.com/artifact/org.glassfish.main.extras/glassfish-embedded-web`.
`glassfish-embedded-nucleus.jar`::
  Corresponds to the nucleus distribution. Download this file from
  `https://central.sonatype.com/artifact/org.glassfish.main.extras/glassfish-embedded-nucleus`.
`glassfish-embedded-static-shell.jar`::
  Contains references to classes needed for deploying Jakarta EE
  applications. Must be used with a non-embedded installation of
  {productName}. It can run the same Jakarta EE applications that are supported by the non-embedded installation that contains it.
  Reference this file from the
  as-install``/lib/embedded`` directory of a nonembedded {productName}
  installation. Do not move this file or it will not work. For an
  explanation of as-install, see xref:#installation-root-directory[Installation Root
  Directory].

[[embedded-glassfish-server-file-system]]

== Embedded {productName} File System

The following Embedded {productName} directories and files are
important if you are referencing a nonembedded installation of {productName}:

* xref:#installation-root-directory[Installation Root Directory]
* xref:#instance-root-directory[Instance Root Directory]
* xref:#GSESG00056[The `domain.xml` File]

[[installation-root-directory]]

=== Installation Root Directory

The installation root directory, represented as as-install, is the
parent of the directory that embedded {productName} uses for
configuration files. This directory corresponds to the base directory
for an installation of {productName}. Configuration files are
contained in the following directories in the base directory for an
installation of {productName}:

* `domains`
* `lib`

Specify the installation root directory only if you have a valid
nonembedded {productName} installation and are using
`glassfish-embedded-static-shell.jar`.

[[instance-root-directory]]

=== Instance Root Directory

The instance root directory, also known as the domain directory, represented as domain-dir, is the parent
directory of a server instance directory. Embedded {productName} uses the server instance directory for domain
configuration files.

[NOTE]
====
If you have valid custom as-install and domain-dir
directories, specify both in the `BootstrapProperties` and
`GlassFishProperties` classes respectively as described in
xref:#creating-and-configuring-an-embedded-glassfish-server[Creating and Configuring an Embedded {productName}].
====


If domain-dir is not specified, {productName} creates a directory
named ``gfembed``random-number``tmp`` in a temporary directory, where
random-number is a randomly generated 19-digit number. {productName}
then copies configuration files into this directory. The temporary
directory is the value of the system property `java.io.tmpdir`. You can
override this value by specifying the `glassfish.embedded.tmpdir`
property in the `GlassFishProperties` class or as a system property.

[[GSESG00056]][[the-domain.xml-file]]

=== The `domain.xml` File

Using an existing `domain.xml` file avoids the need to configure
embedded {productName} programmatically in your application. Your
application obtains domain configuration data from an existing
`domain.xml` file. You can create this file by using the administrative
interfaces of an installation of nonembedded {productName}. To
specify an existing `domain.xml` file, invoke the `setConfigFileURI`
method of the `GlassFishProperties` class as described in
xref:#creating-and-configuring-an-embedded-glassfish-server[Creating and Configuring an Embedded {productName}].


[NOTE]
====
The built-in `domain.xml` file used by default by Embedded {productName} can be found in the Embedded {productName} JAR files, in path 
`org/glassfish/embed/domain.xml`. You can customize this
file and pass it in using the `setConfigFileURI` method while creating
an Embedded {productName}.
====

[[running-from-command-line]]

== Running {productName} Embedded Server from Command Line

Embedded {productName} JAR file can be started as an executable JAR from command line, such as:

```
java -jar glassfish-embedded-all.jar
```

```
java -jar glassfish-embedded-web.jar
```

```
java -jar glassfish-embedded-nucleus.jar
```

```
java -jar ${as-install}/lib/embedded/glassfish-embedded-static-shell.jar
```

For simplicity, this guide will use `glassfish-embedded.jar` to reference any of the above JAR files.

For description of all the JAR files, see xref:#editions[Embedded {productName} editions]

This starts the server and configures it according to the given arguments or
configuration files.
   
If executed without arguments or if no application is deployed, the server
is started and waits for further admin commands in a loop. The server can 
be terminated with the `exit` or `quit` commands or pressing Ctrl+C.

If `glassfish.properties` file exists in the current directory, properties
in this file are set as if the `--properties=glassfish.properties` argument
was defined on the command line.

If `autodeploy` directory exists in the current directory, files and 
directories in that directory are deployed as applications on startup.

If `glassfish-domain` directory exists in the current directory, it will be
used as the domain directory unless specified explicitly with 
`--domainDir=DIRECTORY`

If `domain.xml` file exists in the current directory, it will be
used as the domain configuration file unless specified explicitly with 
`--domainConfigFile=FILE`

By default, {productName} Embedded is started with the following configuration:

- HTTP listener enabled on port 8080
- HTTPS listener disabled

=== Examples of Running Embedded {productName} from Command Line

==== Example 1: Run an application from command line    

On port 8080 and root context by default:

```
java -jar glassfish-embedded.jar app.war
```

==== Example 2: Run an app on a different port

```
java -jar glassfish-embedded.jar --httpPort=8090 app.war
```

==== Example 3: Run custom commands on startup

Deploys an application with a custom root context and prints info about the deployed application. Custom commands need to be enclosed in quotes
if they contain spaces.

```
java -jar glassfish-embedded.jar "deploy --contextroot=/app app.war" list-applications
```

==== Example 4: Run 2 applications from command line

Deploys applications on different context roots, based on the file name
or info in the application descriptors.

```
java -jar glassfish-embedded-all.jar app1.war app2.war
```

=== Command-line Arguments Supported by Embedded {productName}

```
java -jar glassfish-embedded-all.jar [--properties=FILE] 
    [-p=PORT, --httpPort=PORT, --port=PORT] [--httpsPort=PORT_NUMBER] 
    [--domainConfigFile=FILE] 
    [--domainDir=DIRECTORY, --instanceRoot=DIRECTORY] 
    [--noListener, --noPort] [--autoDeployDir=DIRECTORY] [--logLevel=LEVEL] 
    [--logProperties=FILE] [--noInfo] [--help] 
    [applications or admin commands...]
```

`--properties=FILE`

Load properties from a file. This option can be repeated to 
load properties from multiple files. The propertes in the file can be 
any of the following:
    - Any properties supported by Embedded ${productName}.
    - Any command line options with the name of the option as the key, 
without the initial hyphens, and the value of the option as the value.
    - Keys that start with the "command." prefix, followed by any text. 
The value will be treated as a command to execute at startup.
    - Keys that start with the "deploy." prefix, followed by any text. The 
value will be treated as an application to deploy at startup, as if it 
was specified on the command line.
For example, the ${productName} domain directory can be specified with the 
usual Embedded ${productName} property 
"glassfish.embedded.tmpdir=myDomainDir", as well as with the property 
"domainDir=myDomainDir" that represents the "--domainDir=myDomainDir" 
command-line option. A command to deploy an application can be specified 
via a property key "command.deploy.app=deploy --contextroot=app 
myapp.war". An application to deploy at startup with the default deploy 
behavior can be specified via a property key "deploy.app=myapp.war". The 
property "properties" can also be defined in this file, pointing to 
another file. In that case, properties will be loaded also from that 
file.

`-p=PORT, --httpPort=PORT, --port=PORT`
    
Bind the HTTP listener to the specified port. If not set, the HTTP 
listener binds to port 8080 by default, unless it's disabled by the 
--noListener argument.

`--httpsPort=PORT_NUMBER`

Bind the HTTPS listener to the specified port. If not set, the HTTPS 
listener is disabled by default.

`--domainConfigFile=FILE`

Set the location of domain configuration file (i.e., domain.xml) using 
which Embedded {productName} should run.

`--domainDir=DIRECTORY, --instanceRoot=DIRECTORY`

Set the instance root (a.k.a. domain dir) using which Embedded {productName}  should 
run.

`--noListener, `--noPort`

Disable the HTTP listener, which is by default enabled and bound to 
port 8080.

`--autoDeployDir=DIRECTORY`

Files and directories in this directory will be deployed as 
applications (in random order), as if they were specified on the command 
line.

`--logLevel=LEVEL`

Set the log level of all loggers to LEVEL

`--logProperties=FILE`

Set logging properties from file FILE

`--noInfo`

Disable printing information about deployed applications after startup

`--help`

Print help information

---

Any argument that doesn't start with a hyphen (-), is treated as follows:

- If it's a file or directory, it's deployed at startup as an application. If it's
  the only application deployed at startup, it's deployed under the root context '/'.
  Otherwise it's deployed under the context root derived from the name of the file
  or deployment descriptors.
- In all other cases, the argument is executed as a {productName}  admin command.
  Individual commands must be enclosed in quotes if they contain spaces. {productName} 
  admin commands are the same commands supported by {productName} Server's "asadmin"
  command line tool or by the "CommandRunner" Java class in the {productName} Simple Public API.

[[including-the-glassfish-server-embedded-server-api-in-applications]]

== Including the {productName} Embedded Server API in Applications

{productName} provides an application programming
interface (API) for developing applications in which {productName} is
embedded. For details, see the `org.glassfish.embeddable` packages at
`http://embedded-glassfish.java.net/nonav/apidocs/`.

The following topics are addressed here:

* xref:#setting-the-class-path[Setting the Class Path]
* xref:#creating-starting-and-stopping-embedded-glassfish-server[Creating, Starting, and Stopping Embedded {productName}]
* xref:#deploying-and-undeploying-an-application-in-an-embedded-glassfish-server[Deploying and Undeploying an Application in an Embedded
{productName}]
* xref:#running-asadmin-commands-using-the-glassfish-server-embedded-server-api[Running `asadmin` Commands Using the {productName}
Embedded Server API]
* xref:#sample-applications[Sample Applications]

[[setting-the-class-path]]

=== Setting the Class Path

To enable your applications to locate the class libraries for embedded
{productName}, add a JAR file corresponding to one of the xref:#editions[Embedded {productName} editions] to your class path.

In addition, add to the class path any other JAR files or classes upon
which your applications depend. For example, if an application uses a
database other than Java DB, include the Java DataBase Connectivity
(JDBC) driver JAR files in the class path.

[[creating-starting-and-stopping-embedded-glassfish-server]]

=== Creating, Starting, and Stopping Embedded {productName}

Before you can run applications, you must set up and run the embedded
{productName}.

The following topics are addressed here:

* xref:#creating-and-configuring-an-embedded-glassfish-server[Creating and Configuring an Embedded {productName}]
* xref:#running-an-embedded-glassfish-server[Running an Embedded {productName}]

[[creating-and-configuring-an-embedded-glassfish-server]]

==== Creating and Configuring an Embedded {productName}

To create and configure an embedded {productName}, perform these
tasks:

1. Instantiate the `org.glassfish.embeddable.BootstrapProperties`
class.
2. Invoke any methods for configuration settings that you require. This
is optional.
3. Invoke the `GlassFishRuntime.bootstrap()` or
`GlassFishRuntime.bootstrap(BootstrapProperties)` method to create a
`GlassFishRuntime` object.
4. Instantiate the `org.glassfish.embeddable.GlassFishProperties`
class.
5. Invoke any methods for configuration settings that you require. This
is optional.
6. Invoke the `glassfishRuntime.newGlassFish(GlassFishProperties)`
method to create a `GlassFish` object.

The methods of the `BootstrapProperties` class for setting the server
configuration are listed in the following table. The default value of
each configuration setting is also listed.

[[gksir]]

Table 1-1 Methods of the `BootstrapProperties` Class

[width="100%",cols="<29%,<33%,<38%",options="header",]
|===
|Purpose |Method |Default Value
|References an existing xref:#installation-root-directory[Installation Root Directory], also called as-install
a|[source]
----
setInstallRoot(String as-install)
----

|None. If `glassfish-embedded-static-shell.jar` is used, the
xref:#installation-root-directory[Installation Root Directory] is automatically determined and
need not be specified.
|===


The methods of the `GlassFishProperties` class for setting the server
configuration are listed in the following table. The default value of
each configuration setting is also listed.

[[gkskl]]

Table 1-2 Methods of the `GlassFishProperties` Class

[width="100%",cols="<24%,<37%,<39%",options="header",]
|===
|Purpose |Method |Default Value
|References an existing xref:#instance-root-directory[Instance Root Directory], also
called domain-dir
a|
[source]
----
setInstanceRoot(String domain-dir)
----

a|
In order of precedence:

* `glassfish.embedded.tmpdir` property value specified in `GlassFishProperties` object
* `glassfish.embedded.tmpdir` system property value
* `java.io.tmpdir` system property value
* as-install``/domains/domain1`` if a nonembedded installation is referenced

|Creates a new or references an existing configuration file
a|
[source]
----
setConfigFileURI(String configFileURI)
----
a|In order of precedence:

* domain-dir``/config/domain.xml`` if domain-dir was set using `setInstanceRoot`
* built-in embedded `domain.xml`

|Specifies whether the configuration file is read-only
a|
[source]
----
setConfigFileReadOnly(boolean readOnly)
----
|`true`

|Sets the port on which Embedded {productName} listens.
|`setPort`(String networkListener, int port)
|none
|===

[NOTE]
====
Do not use `setPort` if you are using `setInstanceRoot` or `setConfigFileURI`.
====


[[gikmz]]
Example 1-1 Creating an Embedded {productName}

This example shows code for creating an Embedded {productName}.

[source,java]
----
...
import org.glassfish.embeddable.*;
...
    GlassFish glassfish = GlassFishRuntime.bootstrap().newGlassFish();
    glassfish.start();
...
----

[[gksjo]]
Example 1-2 Creating an Embedded {productName} with configuration
customizations

This example shows code for creating an Embedded {productName} using
the existing domain-dir
`C:\samples\test\applicationserver\domains\domain1`.

[source,java]
----
// ...
import org.glassfish.embeddable.*;
    // ...
    BootstrapProperties bootstrapProperties = new BootstrapProperties();
    bootstrapProperties.setInstallRoot("C:\\samples\\test\\applicationserver");
    GlassFishRuntime glassfishRuntime = GlassFishRuntime.bootstrap(bootstrapProperties);

    GlassFishProperties glassfishProperties = new GlassFishProperties();
    glassfishProperties.setInstanceRoot("C:\\samples\\test\\applicationserver\\domains\\domain1");
    GlassFish glassfish = glassfishRuntime.newGlassFish(glassfishProperties);

    glassfish.start();
    // ...
----

[[running-an-embedded-glassfish-server]]

==== Running an Embedded {productName}

After you create an embedded {productName} as described in
xref:#creating-and-configuring-an-embedded-glassfish-server[Creating and Configuring an Embedded {productName}], you
can perform operations such as:

* xref:#setting-the-port-of-an-embedded-glassfish-server-from-an-application[Setting the Port of an Embedded {productName} From an Application]
* xref:#starting-an-embedded-glassfish-server-from-an-application[Starting an Embedded {productName} From an Application]
* xref:#stopping-an-embedded-glassfish-server-from-an-application[Stopping an Embedded {productName} From an Application]

[[setting-the-port-of-an-embedded-glassfish-server-from-an-application]]

Setting the Port of an Embedded {productName} From an Application

You must set the server's HTTP or HTTPS port. If you do not set the
port, your application fails to start and throws an exception. You can
set the port directly or indirectly.

[NOTE]
====
Do not use `setPort` if you are using `setInstanceRoot` or
`setConfigFileURI`. These methods set the port indirectly.
====


* To set the port directly, invoke the `setPort` method of the
`GlassFishProperties` object.
* To set the port indirectly, use a `domain.xml` file that sets the
port. For more information, see xref:#GSESG00056[The `domain.xml` File].

[[gjkxc]]
Example 1-3 Setting the port of an Embedded {productName}

This example shows code for setting the port of an embedded {productName}.

[source,java]
----
...
import org.glassfish.embeddable.*;
...
    GlassFishProperties glassfishProperties = new GlassFishProperties();
    glassfishProperties.setPort("http-listener", 8080);
    glassfishProperties.setPort("https-listener", 8181);
...
----

[[starting-an-embedded-glassfish-server-from-an-application]]

Starting an Embedded {productName} From an Application

To start an embedded {productName}, invoke the `start` method of the `GlassFish` object.

[[gilry]]
Example 1-4 Starting an Embedded {productName}

This example shows code for setting the port and starting an embedded
{productName}. This example also includes the code from
xref:#gikmz[Example 1-1] for creating a `GlassFish` object.

[source,java]
----
...
import org.glassfish.embeddable.*;
...
    GlassFishProperties glassfishProperties = new GlassFishProperties();
    glassfishProperties.setPort("http-listener", 8080);
    glassfishProperties.setPort("https-listener", 8181);
    ...
    GlassFish glassfish = GlassFishRuntime.bootstrap().newGlassFish(glassfishProperties);
    glassfish.start();
...
----

[[stopping-an-embedded-glassfish-server-from-an-application]]

Stopping an Embedded {productName} From an Application

The API for embedded {productName} provides a method for stopping an
embedded server. Using this method enables your application to stop the
server in an orderly fashion by performing any necessary cleanup steps
before stopping the server, for example:

* Undeploying deployed applications
* Releasing any resources that your application uses

To stop an embedded {productName}, invoke the `stop` method of an
existing `GlassFish` object.

[[gilnz]]
Example 1-5 Stopping an Embedded {productName}

This example shows code for prompting the user to press the Enter key to
stop an embedded {productName}. Code for creating a `GlassFish`
object is not shown in this example. For an example of code for creating
a `GlassFish` object, see xref:#gikmz[Example 1-1].

[source,java]
----
...
import java.io.BufferedReader;
...
import org.glassfish.embeddable.*;
...
    System.out.println("Press Enter to stop server");
        // wait for Enter
    glassfish.stop(); // Stop Embedded GlassFish
...
----

As an alternative, you can use the `dispose` method to stop an embedded
{productName} and dispose of the temporary file system.

[[deploying-and-undeploying-an-application-in-an-embedded-glassfish-server]]

=== Deploying and Undeploying an Application in an Embedded {productName}

Deploying an application installs the files that comprise the
application into Embedded {productName} and makes the application
ready to run. By default, an application is enabled when it is deployed.

The following topics are addressed here:

* xref:#to-deploy-an-application-from-an-archive-file-or-a-directory[To Deploy an Application From an Archive File or a Directory]
* xref:#undeploying-an-application[Undeploying an Application]
* xref:#creating-a-scattered-archive[Creating a Scattered Archive]
* xref:#creating-a-scattered-enterprise-archive[Creating a Scattered Enterprise Archive]

For general information about deploying applications in {productName}, see the xref:application-deployment-guide.adoc#GSDPG[{productName}
Application Deployment Guide].

[[to-deploy-an-application-from-an-archive-file-or-a-directory]]

==== To Deploy an Application From an Archive File or a Directory

An archive file contains the resources, deployment descriptor, and
classes of an application. The content of the file must be organized in
the directory structure that the Jakarta EE specifications define for the
type of archive that the file contains. For more information, see
"xref:application-deployment-guide.adoc#deploying-applications[Deploying Applications]" in {productName} Application Deployment Guide.

Deploying an application from a directory enables you to deploy an
application without the need to package the application in an archive
file. The contents of the directory must match the contents of the
expanded Jakarta EE archive file as laid out by the {productName}. The
directory must be accessible to the machine on which the deploying
application runs. For more information about the requirements for
deploying an application from a directory, see "xref:application-deployment-guide.adoc#to-deploy-an-application-or-module-in-a-directory-format[To
Deploy an Application or Module in a Directory Format]" in {productName} Application Deployment Guide.

If some of the resources needed by an application are not under the
application's directory, see xref:#creating-a-scattered-archive[Creating a Scattered Archive].

1. Instantiate the `java.io.File` class to represent the archive file or directory.

2. Invoke the `getDeployer` method of the `GlassFish` object to get an
instance of the `org.glassfish.embeddable.Deployer` class.

3. Invoke the `deploy(File archive, String... params)` method of the
instance of the `Deployer` object. +
Specify the `java.io.File` class instance you created previously as the
first method parameter. +
For information about optional parameters you can set, see the
descriptions of the
xref:reference-manual.adoc#deploy[`deploy`(1)] subcommand parameters.
Simply quote each parameter in the method, for example `"--force=true"`.

[[gioph]]
Example 1-6 Deploying an Application From an Archive File

This example shows code for deploying an application from the archive
file `c:\samples\simple.war` and setting the name, contextroot, and
force parameters. This example also includes the code from
xref:#gikmz[Example 1-1] for creating `GlassFishProperties` and
`GlassFish` objects.

[source,java]
----
...
import java.io.File;
...
import org.glassfish.embeddable.*;
...
    GlassFishProperties glassfishProperties = new GlassFishProperties();
    glassfishProperties.setPort("http-listener", 8080);
    glassfishProperties.setPort("https-listener", 8181);
    ...
    GlassFish glassfish = GlassFishRuntime.bootstrap().newGlassFish(glassfishProperties);
    glassfish.start();
    File war = new File("c:\\samples\\simple.war");
    Deployer deployer = glassfish.getDeployer();
    deployer.deploy(war, "--name=simple", "--contextroot=simple", "--force=true");
    // deployer.deploy(war) can be invoked instead. Other parameters are optional.
...
----

[[undeploying-an-application]]

==== Undeploying an Application

Undeploy an application when the application is no longer required to
run in {productName}. For example, before stopping {productName},
undeploy all applications that are running in {productName}.


[NOTE]
====
If you reference a nonembedded {productName} installation using the
`glassfish-embedded-static-shell.jar` file and do not undeploy your
applications in the same server life cycle in which you deployed them,
expanded archives for these applications remain under the
domain-dir``/applications`` directory.
====


To undeploy an application, invoke the `undeploy` method of an existing
`Deployer` object. In the method invocation, pass the name of the
application as a parameter. This name is specified when the application
is deployed.

For information about optional parameters you can set, see the
descriptions of the
xref:reference-manual.adoc#deploy[`deploy`(1)] command parameters.
Simply quote each parameter in the method, for example
`"--cascade=true"`.

To undeploy all deployed applications, invoke the `undeployAll` method
of an existing `EmbeddedDeployer` object. This method takes no
parameters.

[[gilwu]]
Example 1-7 Undeploying an Application

This example shows code for undeploying the application that was
deployed in xref:#gioph[Example 1-6].

[source,java]
----
...
import org.glassfish.embeddable.*;
...
    deployer.undeploy(war, "--droptables=true", "--cascade=true");
...
----

[[creating-a-scattered-archive]]

==== Creating a Scattered Archive

Deploying a module from a scattered archive (WAR or JAR) enables you to
deploy an unpackaged module whose resources, deployment descriptor, and
classes are in any location. Deploying a module from a scattered archive
simplifies the testing of a module during development, especially if all
the items that the module requires are not available to be packaged.

In a scattered archive, these items are not required to be organized in
a specific directory structure. Therefore, you must specify the location
of the module's resources, deployment descriptor, and classes when
deploying the module.

To create a scattered archive, perform these tasks:

1. Instantiate the `org.glassfish.embeddable.archive.ScatteredArchive` class.
2. Invoke the `addClassPath` and `addMetadata` methods if you require them.
3. Invoke the `toURI` method to deploy the scattered archive.

The methods of this class for setting the scattered archive
configuration are listed in the following table. The default value of
each configuration setting is also listed.

[[gjrdg]]

Table 1-3 Constructors and Methods of the `ScatteredArchive` Class

[width="100%",cols="<52%,<38%,<10%",options="header",]
|===
|Purpose |Method |Default Value
|Creates and names a scattered archive
a|[source,java]
----
ScatteredArchive(String name, ScatteredArchive.Type type)
----

|None

|Creates and names a scattered archive based on a top-level directory.
If the entire module is organized under the topDir, this is the only
method necessary. The topDir can be null if other methods specify the
remaining parts of the module.
a|[source,java]
----
ScatteredArchive(String name, ScatteredArchive.Type type, File topDir)
----

|None

|Adds a directory to the classes classpath
a|[source,java]
----
addClassPath(File path)
----

|None

|Adds a metadata locator
a|[source,java]
----
addMetaData(File path)
----

|None

|Adds and names a metadata locator
a|[source,java]
----
addMetaData(File path, String name)
----

|None

|Gets the deployable URI for this scattered archive a|
[source,java]
----
toURI()
----

|None
|===


[[gjrfq]]
Example 1-8 Deploying an Application From a Scattered Archive

This example shows code for creating a WAR file and using the
`addClassPath` and `addMetadata` methods. This example also includes the
code from xref:#gioph[Example 1-6] for deploying an application from an archive file.

[source,java]
----
...
import java.io.File;
...
import org.glassfish.embeddable.*;
...
    GlassFishProperties glassfishProperties = new GlassFishProperties();
    glassfishProperties.setPort("http-listener", 9090);
    GlassFish glassfish = GlassFishRuntime.bootstrap().newGlassFish(glassfishProperties);
    glassfish.start();
    Deployer deployer = glassfish.getDeployer();
    ScatteredArchive archive = new ScatteredArchive("testapp", ScatteredArchive.Type.WAR);
    // target/classes directory contains complied servlets
    archive.addClassPath(new File("target", "classes"));
    // resources/sun-web.xml is the WEB-INF/sun-web.xml
    archive.addMetadata(new File("resources", "sun-web.xml"));
    // resources/web.xml is the WEB-INF/web.xml
    archive.addMetadata(new File("resources", "web.xml"));
    // Deploy the scattered web archive.
    String appName = deployer.deploy(archive.toURI(), "--contextroot=hello");

    deployer.undeploy(appName);
    glassfish.stop();
    glassfish.dispose();
...
----

[[creating-a-scattered-enterprise-archive]]

==== Creating a Scattered Enterprise Archive

Deploying an application from a scattered enterprise archive (EAR)
enables you to deploy an unpackaged application whose resources,
deployment descriptor, and classes are in any location. Deploying an
application from a scattered archive simplifies the testing of an
application during development, especially if all the items that the
application requires are not available to be packaged.

In a scattered archive, these items are not required to be organized in
a specific directory structure. Therefore, you must specify the location
of the application's resources, deployment descriptor, and classes when
deploying the application.

To create a scattered enterprise archive, perform these tasks:

1. Instantiate the
`org.glassfish.embeddable.archive.ScatteredEnterpriseArchive` class.
2. Invoke the `addArchive` and `addMetadata` methods if you require
them.
3. Invoke the `toURI` method to deploy the scattered enterprise
archive.

The methods of this class for setting the scattered enterprise archive
configuration are listed in the following table. The default value of
each configuration setting is also listed.

[[gkvgb]]

Table 1-4 Constructors and Methods of the `ScatteredEnterpriseArchive` Class

[width="99%",cols="<42%,<48%,<10%",options="header",]
|===
|Purpose |Method |Default Value
|Creates and names a scattered enterprise archive a|
[source,java]
----
ScatteredEnterpriseArchive(String name)
----

 |None
|Adds a module or library a|
[source,java]
----
addArchive(File archive)
----

 |None
|Adds a module or library a|
[source,java]
----
addArchive(File archive, String name)
----

 |None
|Adds a module or library a|
[source,java]
----
addArchive(URI URI)
----

 |None
|Adds a module or library a|
[source,java]
----
addArchive(URI URI, String name)
----

 |None
|Adds a metadata locator a|
[source,java]
----
addMetaData(File path)
----

 |None
|Adds and names a metadata locator a|
[source,java]
----
addMetaData(File path, String name)
----

 |None
|Gets the deployable URI for this scattered archive a|
[source,java]
----
toURI()
----

 |None
|===


[[gkvga]]
Example 1-9 Deploying an Application From a Scattered Enterprise Archive

This example shows code for creating an EAR file and using the
`addArchive` and `addMetadata` methods. This example also includes code
similar toxref:#gjrfq[Example 1-8] for creating a scattered archive.

[source,java]
----
...
import java.io.File;
...
import org.glassfish.embeddable.*;
...
    GlassFishProperties glassfishProperties = new GlassFishProperties();
    glassfishProperties.setPort("http-listener", 9090);
    GlassFish glassfish = GlassFishRuntime.bootstrap().newGlassFish(glassfishProperties);
    glassfish.start();
    Deployer deployer = glassfish.getDeployer();

    // Create a scattered web application.
    ScatteredArchive webmodule = new ScatteredArchive("testweb", ScatteredArchive.Type.WAR);
    // target/classes directory contains my complied servlets
    webmodule.addClassPath(new File("target", "classes"));
    // resources/sun-web.xml is my WEB-INF/sun-web.xml
    webmodule.addMetadata(new File("resources", "sun-web.xml"));

    // Create a scattered enterprise archive.
    ScatteredEnterpriseArchive archive = new ScatteredEnterpriseArchive("testapp");
    // src/application.xml is my META-INF/application.xml
    archive.addMetadata(new File("src", "application.xml"));
    // Add scattered web module to the scattered enterprise archive.
    // src/application.xml references Web module as "scattered.war".
    //Hence specify the name while adding the archive.
    archive.addArchive(webmodule.toURI(), "scattered.war");
    // lib/mylibrary.jar is a library JAR file.
    archive.addArchive(new File("lib", "mylibrary.jar"));
    // target/ejbclasses contain my compiled EJB module.
    // src/application.xml references EJB module as "ejb.jar".
    //Hence specify the name while adding the archive.
    archive.addArchive(new File("target", "ejbclasses"), "ejb.jar");

    // Deploy the scattered enterprise archive.
    String appName = deployer.deploy(archive.toURI());

    deployer.undeploy(appName);
    glassfish.stop();
    glassfish.dispose();
...
----

[[running-asadmin-commands-using-the-glassfish-server-embedded-server-api]]

=== Running `asadmin` Commands Using the {productName} Embedded API

Running xref:reference-manual.adoc#asadmin[`asadmin`] commands from an application enables
the application to configure the embedded {productName} to suit the
application's requirements. For example, an application can run the
required `asadmin` commands to create a JDBC technology connection to a
database.

For more information about configuring embedded {productName}, see
the xref:administration-guide.adoc#GSADG[{productName} Administration
Guide]. For detailed information about `asadmin` commands, see Section 1
of the xref:reference-manual.adoc#GSRFM[{productName} Reference
Manual].


[NOTE]
====
Ensure that your application has started an embedded {productName}
before the application attempts to run `asadmin` commands. For more
information, see xref:#running-an-embedded-glassfish-server[Running an Embedded {productName}].
====


The `org.glassfish.embeddable` package contains classes that you can use
to run `asadmin` commands. Use the following code examples as templates
and change the command name, parameter names, and parameter values as
needed.

[[gjldj]]
Example 1-10 Running an `asadmin create-jdbc-resource` Command

This example shows code for running an `asadmin create-jdbc-resource`
command. Code for creating and starting the server is not shown in this
example. For an example of code for creating and starting the server,
see xref:#gilry[Example 1-4].

[source,java]
----
...
import org.glassfish.embeddable.*;
...
    String command = "create-jdbc-resource";
    String poolid = "--connectionpoolid=DerbyPool";
    String dbname = "jdbc/DerbyPool";
    CommandRunner commandRunner = glassfish.getCommandRunner();
    CommandResult commandResult = commandRunner.run(command, poolid, dbname);
...
----

[[gjlfm]]
Example 1-11 Running an `asadmin set-log-level` Command

This example shows code for running an `asadmin set-log-level` command.
Code for creating and starting the server is not shown in this example.
For an example of code for creating and starting the server, see
xref:#gilry[Example 1-4].

[source,java]
----
...
import org.glassfish.embeddable.*;
...
    String command = "set-log-level";
    String weblevel = "jakarta.enterprise.system.container.web=FINE";
    CommandRunner commandRunner = glassfish.getCommandRunner();
    CommandResult commandResult = commandRunner.run(command, weblevel);
...
----

For another way to change log levels, see xref:#changing-log-levels-in-embedded-glassfish-server[Changing Log
Levels in Embedded {productName}].

[[sample-applications]]

=== Sample Applications

[[gionq]]
Example 1-12 Using an Existing `domain.xml` File and Deploying an
Application From an Archive File

This example shows code for the following:

* Using the existing file
`c:\myapp\embeddedserver\domains\domain1\config\domain.xml` and
preserving this file when the application is stopped.
* Deploying an application from the archive file
`c:\samples\simple.war`.

[source,java]
----
import java.io.File;
import java.io.BufferedReader;
import org.glassfish.embeddable.*;

public class Main {

     /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        File configFile = new File ("c:\\myapp\\embeddedserver\\domains\\domain1\\config\\domain.xml");
        File war = new File("c:\\samples\\simple.war");
        try {
            GlassFishRuntime glassfishRuntime = GlassFishRuntime.bootstrap();
            ...
            GlassFishProperties glassfishProperties = new GlassFishProperties();
            glassfishProperties.setConfigFileURI(configFile.toURI());
            glassfishProperties.setConfigFileReadOnly(false);
            ...
            GlassFish glassfish = glassfishRuntime.newGlassFish(glassfishProperties);
            glassfish.start();

            Deployer deployer = glassfish.getDeployer();
            deployer.deploy(war, "--force=true");
        }
        catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println("Press Enter to stop server");
        // wait for Enter
        new BufferedReader(new java.io.InputStreamReader(System.in)).readLine();
        try {
            glassfish.dispose();
            glassfishRuntime.shutdown();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
}
----

[[testing-applications-with-the-maven-plug-in-for-embedded-glassfish-server]]

== Testing Applications with the Maven Plug-in for Embedded {productName}

If you are using http://maven.apache.org/[Apache Maven]
(`http://maven.apache.org/`), the plug-in for embedded {productName}
simplifies the testing of applications. This plug-in enables you to
build and start an unpackaged application with a single Maven goal.

The following topics are addressed here:

* xref:#to-set-up-your-maven-environment[To Set Up Your Maven Environment]
* xref:#to-build-and-start-an-application-from-maven[To Build and Start an Application From Maven]
* xref:#to-stop-embedded-glassfish-server[To Stop Embedded {productName}]
* xref:#to-redeploy-an-application-that-was-built-and-started-from-maven[To Redeploy an Application That Was Built and Started From Maven]
* xref:#maven-goals-for-embedded-glassfish-server[Maven Goals for Embedded {productName}]

Predefined Maven goals for embedded {productName} are described in
xref:#maven-goals-for-embedded-glassfish-server[Maven Goals for Embedded {productName}].

To use Maven with Embedded {productName} and the EJB 3.1 Embeddable
API, see xref:#GSESG00064[Using Maven with the EJB 3.1 Embeddable API and
Embedded {productName}].

[[to-set-up-your-maven-environment]]

=== To Set Up Your Maven Environment

Setting up your Maven environment enables Maven to download the required
embedded {productName} distribution file when you build your project.
Setting up your Maven environment also identifies the plug-in that
enables you to build and start an unpackaged application with a single
Maven goal.

Before You Begin

Ensure that http://maven.apache.org/[Apache Maven]
(`http://maven.apache.org/`) is installed.

1. Identify the Maven plug-in for embedded {productName}.
+
Add the following `plugin` element to your POM file:
+
[source,xml]
----
...
        ...
        <plugins>
            ...
            <plugin>
                <groupId>org.glassfish</groupId>
                <artifactId>maven-embedded-glassfish-plugin</artifactId>
                <version>version</version>
            </plugin>
            ...
        </plugins>
...
----
version::
  The version to use. The version of the final promoted build for this
  release is `3.1.1`. The Maven plug-in is not bound to a specific version
  of {productName}. You can specify the version you want to use. If
  no version is specified, a default version is used.

2. Configure the the path to the application WAR, and other standard settings.
+
Add the following `configuration` element to your POM file:
+
[source,xml]
----
...
        <plugins>
            ...
            <plugin>
                ...
                <configuration>
                    <app>target/test.war</app>
                    <port>8080</port>
                    <contextRoot>test</contextRoot>
                    <autoDelete>true</autoDelete>
                    ...
                </configuration>
                ...
            </plugin>
            ...
        </plugins>
...
----
app::
  In the app parameter, substitute the archive file or directory for your
  application. The optional port, contextRoot, and autoDelete parameters
  show example values. For details, see xref:#maven-goals-for-embedded-glassfish-server[Maven Goals for
  Embedded {productName}].

3. Perform advanced plug-in configuration. This step is optional.
Add the following `configuration` element to your POM file:
+
[source,xml]
----
...
        <plugins>
            ...
            <plugin>
                ...
                <configuration>
                    <app>target/test.war</app>
                    <name>test</name>
                    <contextRoot>test</contextRoot>
                    <ports>
                        <http-listener>8080</http-listener>
                        <https-listener>8181</https-listener>
                    </ports>
                    <bootstrapProperties>
                        <property>test_key=test_value</property>
                    </bootstrapProperties>
                    <bootstrapPropertiesFile>bootstrap.properties</bootstrapPropertiesFile>
                    <glassfishProperties>
<property>embedded-glassfish-config.server.jms-service.jms-host.default_JMS_host.port=17676</property>
                    </glassfishProperties>
                    <glassfishPropertiesFile>glassfish.properties</glassfishPropertiesFile>
                    <systemProperties>
                        <property>ANTLR_USE_DIRECT_CLASS_LOADING=true</property>
                    </systemProperties>
                    <systemPropertiesFile>system.properties</systemPropertiesFile>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>start</goal>
                            <goal>deploy</goal>
                            <goal>undeploy</goal>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            ...
        </plugins>
...
----

4. Configure Maven goals.
Add `execution` elements to your POM file:
+
[source,xml]
----
...
        <plugins>
            ...
            <plugin>
                ...
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                                <goal>goal</goal>
                        </goals>
                    </execution>
                </executions>
                ...
            </plugin>
            ...
        </plugins>
...
----
goal::
  The goal to use. See xref:#maven-goals-for-embedded-glassfish-server[Maven Goals for Embedded {productName}].

5. Configure the repository.
Add the following `repository` element to your POM file:
+
[source,xml]
----
<pluginRepositories>
    <pluginRepository>
        <id>maven2-repository.dev.java.net</id>
        <name>Java.net Repository for Maven</name>
        <url>http://download.java.net/maven/glassfish/</url>
    </pluginRepository>
</pluginRepositories>
----

[[gjkod]]
Example 1-13 POM File for Configuring Maven to Use Embedded {productName}

This example shows a POM file for configuring Maven to use embedded {productName}.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<!--
Line breaks in the following element are for readability purposes only
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>org.glassfish</groupId>
  <artifactId>maven-glassfish-plugin-tester</artifactId>
  <version>3.1</version>
  <name>Maven test</name>
  <build>
    <plugins>
      <plugin>
        <groupId>org.glassfish</groupId>
        <artifactId>maven-embedded-glassfish-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <app>target/test.war</app>
          <port>8080</port>
          <contextRoot>test</contextRoot>
          <autoDelete>true</autoDelete>
       </configuration>
       <executions>
          <execution>
             <phase>install</phase>
             <goals>
                   <goal>run</goal>
             </goals>
          </execution>
       </executions>
     </plugin>
    </plugins>
  </build>
  <pluginRepositories>
      <pluginRepository>
          <id>maven2-repository.dev.java.net</id>
          <name>Java.net Repository for Maven</name>
          <url>http://download.java.net/maven/glassfish/</url>
      </pluginRepository>
  </pluginRepositories>
</project>
----

[[to-build-and-start-an-application-from-maven]]

=== To Build and Start an Application From Maven

If you are using Maven to manage the development of your application,
you can use a Maven goal to build and start the application in embedded
{productName}.

Before You Begin

Ensure that your Maven environment is configured, as described in
xref:#to-set-up-your-maven-environment[To Set Up Your Maven Environment].

1. Include the path to the Maven executable file `mvn` in your path
statement.
2. Ensure that the `JAVA_HOME` environment variable is defined.
3. Create a directory for the Maven project for your application.
4. Copy to your project directory the POM file that you created in
xref:#to-set-up-your-maven-environment[To Set Up Your Maven Environment].
5. Run the following command in your project directory:
+
[source]
----
mvn install
----
This command performs the following actions:
* Installs the Maven repository in a directory named `.m2` under your
home directory.
* Starts Embedded {productName}.
* Deploys your application.
+
The application continues to run in Embedded {productName} until
Embedded {productName} is stopped.

[[to-stop-embedded-glassfish-server]]

=== To Stop Embedded {productName}

1. Change to the root directory of the Maven project for your
application.
2. Run the Maven goal to stop the application in embedded {productName}.
+
[source]
----
mvn embedded-glassfish:stop
----
This runs the `stop` method of the `GlassFish` object and any other
methods that are required to shut down the server in an orderly fashion.
See xref:#stopping-an-embedded-glassfish-server-from-an-application[Stopping an Embedded {productName} From an
Application].

[[to-redeploy-an-application-that-was-built-and-started-from-maven]]

=== To Redeploy an Application That Was Built and Started From Maven

An application that was built and started from Maven continues to run in
Embedded {productName} until Embedded {productName} is stopped.
While the application is running, you can test changes to the
application by redeploying it.

To redeploy, in the window from where the application was built and
started from Maven, press Enter.

[[maven-goals-for-embedded-glassfish-server]]

=== Maven Goals for Embedded {productName}

You can use the following Maven goals to test your applications with
embedded {productName}:

* xref:#embedded-glassfishrun-goal[`embedded-glassfish:run` Goal]
* xref:#embedded-glassfishstart-goal[`embedded-glassfish:start` Goal]
* xref:#embedded-glassfishdeploy-goal[`embedded-glassfish:deploy` Goal]
* xref:#embedded-glassfishundeploy-goal[`embedded-glassfish:undeploy` Goal]
* xref:#embedded-glassfishstop-goal[`embedded-glassfish:stop` Goal]
* xref:#embedded-glassfishadmin-goal[`embedded-glassfish:admin` Goal]

[[embedded-glassfishrun-goal]]

==== `embedded-glassfish:run` Goal

This goal starts the server and deploys an application. You can redeploy
if you change the application. The application can be a packaged archive
or a directory that contains an exploded application. You can set the
parameters described in the following table.

[[gjkws]]

Table 1-5 `embedded-glassfish:run` Parameters

[width="100%",cols="<18%,<42%,<40%",options="header",]
|===
|Parameter |Default |Description
|app |None |The archive file or directory for the application to be deployed.

|serverID |`maven` |(optional) The ID of the server to start.

|containerType |`all` |(optional) The container to start: `web`, `ejb`, `jpa`, or `all`.

|installRoot |None |(optional) The xref:#installation-root-directory[Installation Root Directory].

|instanceRoot a|
In order of precedence:

* `glassfish.embedded.tmpdir` property value specified in `GlassFishProperties` object
* `glassfish.embedded.tmpdir` system property value
* `java.io.tmpdir` system property value
* as-install``/domains/domain1`` if a nonembedded installation is referenced

 |(optional) The xref:#instance-root-directory[Instance Root Directory]

|configFile |domain-dir``/config/domain.xml`` |(optional) The
configuration file.

|port |None. Must be set explicitly or defined in the configuration
file. |The HTTP or HTTPS port.

|name a|
In order of precedence:

* The `application-name` or `module-name` in the deployment descriptor.
* The name of the archive file without the extension or the directory name.

For more information, see "xref:application-deployment-guide.adoc#naming-standards[Naming Standards]" in
{productName} Application Deployment Guide.

 |(optional) The name of the application.

|contextRoot |The name of the application. |(optional) The context root
of the application.

|precompileJsp |`false` |(optional) If `true`, JSP pages are precompiled
during deployment.

|dbVendorName |None |(optional) The name of the database vendor for
which tables can be created. Allowed values are `javadb`, `db2`,
`mssql`, `mysql`, `oracle`, `postgresql`, `pointbase`, `derby` (also for
CloudScape), and `sybase`, case-insensitive.

|createTables |Value of the `create-tables-at-deploy` attribute in
`sun-ejb-jar.xml`. |(optional) If `true`, creates database tables during
deployment for beans that are automatically mapped by the EJB container.

|dropTables |Value of the `drop-tables-at-undeploy` attribute in
`sun-ejb-jar.xml`. a|
(optional) If `true`, and deployment and undeployment occur in the same
JVM session, database tables that were automatically created when the
bean(s) were deployed are dropped when the bean(s) are undeployed.

If `true`, the name parameter must be specified or tables may not be
dropped.

|autoDelete |`false` a|
(optional) If `true`, deletes the contents of the xref:#instance-root-directory[Instance
Root Directory] when the server is stopped.

Caution: Do not set `autoDelete` to `true` if you are using
`installRoot` to refer to a preexisting {productName} installation.

|===


[[embedded-glassfishstart-goal]]

==== `embedded-glassfish:start` Goal

This goal starts the server. You can set the parameters described in the
following table.

[[gjkye]]

Table 1-6 `embedded-glassfish:start` Parameters

[width="100%",cols="<17%,<38%,<45%",options="header",]
|===
|Parameter |Default |Description
|serverID |`maven` |(optional) The ID of the server to start.

|containerType |`all` |(optional) The container to start: `web`, `ejb`,
`jpa`, or `all`.

|installRoot |None |(optional) The xref:#installation-root-directory[Installation Root
Directory].

|instanceRoot a|
In order of precedence:

* `glassfish.embedded.tmpdir` system property value
* `java.io.tmpdir` system property value
* as-install``/domains/domain1``

 |(optional) The xref:#instance-root-directory[Instance Root Directory]

|configFile |domain-dir`/config/domain.xml` |(optional) The
configuration file.

|port |None. Must be set explicitly or defined in the configuration
file. |The HTTP or HTTPS port.

|autoDelete |`false` a|
(optional) If `true`, deletes the contents of the xref:#instance-root-directory[Instance
Root Directory] when the server is stopped.

Caution: Do not set `autoDelete` to `true` if you are using
`installRoot` to refer to a preexisting {productName} installation.

|===


[[embedded-glassfishdeploy-goal]]

==== `embedded-glassfish:deploy` Goal

This goal deploys an application. You can redeploy if you change the
application. The application can be a packaged archive or a directory
that contains an exploded application. You can set the parameters
described in the following table.

[[gjkvv]]

Table 1-7 `embedded-glassfish:deploy` Parameters

[width="100%",cols="<18%,<39%,<43%",options="header",]
|===
|Parameter |Default |Description
|app |None |The archive file or directory for the application to be
deployed.

|serverID |`maven` |(optional) The ID of the server to start.

|name a|
In order of precedence:

* The `application-name` or `module-name` in the deployment descriptor.
* The name of the archive file without the extension or the directory
name.

For more information, see "xref:application-deployment-guide.adoc#naming-standards[Naming Standards]" in
{productName} Application Deployment Guide.

 |(optional) The name of the application.

|contextRoot |The name of the application. |(optional) The context root
of the application.

|precompileJsp |`false` |(optional) If `true`, JSP pages are precompiled
during deployment.

|dbVendorName |None |(optional) The name of the database vendor for
which tables can be created. Allowed values are `javadb`, `db2`,
`mssql`, `oracle`, `postgresql`, `pointbase`, `derby` (also for
CloudScape), and `sybase`, case-insensitive.

|createTables |Value of the `create-tables-at-deploy` attribute in
`sun-ejb-jar.xml`. |(optional) If `true`, creates database tables during
deployment for beans that are automatically mapped by the EJB container.
|===


[[embedded-glassfishundeploy-goal]]

==== `embedded-glassfish:undeploy` Goal


[NOTE]
====
If you reference a nonembedded {productName} installation using the
`glassfish-embedded-static-shell.jar` file and do not undeploy your
applications in the same server life cycle in which you deployed them,
expanded archives for these applications remain under the
domain-dir``/applications`` directory.
====


This goal undeploys an application. You can set the parameters described
in the following table.

[[gjkxf]]

Table 1-8 `embedded-glassfish:undeploy` Parameters

[width="100%",cols="<14%,<34%,<52%",options="header",]
|===
|Parameter |Default |Description
|name |If the name is omitted, all applications are undeployed. |The
name of the application.

|serverID |`maven` |(optional) The ID of the server to start.

|dropTables |Value of the `drop-tables-at-undeploy` attribute in
`sun-ejb-jar.xml`. a|
(optional) If `true`, and deployment and undeployment occur in the same
JVM session, database tables that were automatically created when the
bean(s) were deployed are dropped when the bean(s) are undeployed.

If `true`, the name parameter must be specified or tables may not be
dropped.

|cascade |`false` a|
(optional) If `true`, deletes all connection pools and connector
resources associated with the resource adapter being undeployed.

If `false`, undeployment fails if any pools or resources are still
associated with the resource adapter.

This attribute is applicable to connectors (resource adapters) and
applications with connector modules.

|===


[[embedded-glassfishstop-goal]]

==== `embedded-glassfish:stop` Goal

This goal stops the server. You can set the parameters described in the
following table.

[[gjkwm]]

Table 1-9 `embedded-glassfish:stop` Parameters

[width="100%",cols="<16%,<17%,<67%",options="header",]
|===
|Parameter |Default |Description
|serverID |`maven` |(optional) The ID of the server to stop.
|===


[[embedded-glassfishadmin-goal]]

==== `embedded-glassfish:admin` Goal

This goal runs a {productName} administration command. You must use
either the command and commandParameters parameters in combination or
the commandLine parameter. For more information about administration
commands, see the xref:reference-manual.adoc#GSRFM[{productName}
Reference Manual]. You can set the parameters described in the following
table.

[[gjkwe]]

Table 1-10 `embedded-glassfish:start` Parameters

[width="100%",cols="<24%,<10%,<66%",options="header",]
|===
|Parameter |Default |Description
|serverID |`maven` |(optional) The ID of the server on which to run the
command.

|command |None |The name of the command, for example
`createJdbcResource`.

|commandParameters |None |A map of the command parameters. See the
`org.glassfish.embeddable.admin.CommandParameters` class at
`http://glassfish.java.net/nonav/docs/v3/api/`.

|commandLine |None |The full `asadmin` syntax of the command.
|===


[[GSESG00039]][[using-the-ejb-3.1-embeddable-api-with-embedded-glassfish-server]]

== Using the EJB 3.1 Embeddable API with Embedded {productName}

The EJB 3.1 Embeddable API is designed for unit testing of EJB modules.
You must use this API with a pre-installed, nonembedded {productName}
instance. However, you can take advantage of Embedded {productName}'s
ease of use by referencing the nonembedded {productName} instance
with the `glassfish-embedded-static-shell.jar` file.

Embedded {productName} is not related to the EJB 3.1 Embeddable API,
but you can use these APIs together.

The Maven plug-in does not apply to embeddable EJB applications.
However, you can use Maven with the POM file shown in xref:#GSESG00064[Using
Maven with the EJB 3.1 Embeddable API and Embedded {productName}].

The EJB 3.1 Embeddable API is described in
http://jcp.org/en/jsr/detail?id=318[Java Specification Request (JSR) 318]
(`http://jcp.org/en/jsr/detail?id=318`). An `ejb-embedded` example
is available at
https://jakarta.ee/learn/docs/jakartaee-tutorial/9.1/entbeans/ejb-embedded/ejb-embedded.html[Code Samples]
(`https://jakarta.ee/learn/docs/jakartaee-tutorial/9.1/entbeans/ejb-embedded/ejb-embedded.html`).

The EJB 3.1 Embeddable API supports all EJB 3.1 Lite features with
addition of the EJB timer service and testing of EJB modules packaged in
a WAR file.

For EJB modules in a WAR file (or an exploded directory), if a web
application has one EJB module, and there are no other EJB modules in
the classpath, those entries (libraries) are ignored. If there are other
EJB modules, a temporary EAR file is created. For EJB modules in a WAR
file to be tested, the client code must use EJB modules with interfaces
or without annotations. Those EJB modules are not part of the classpath
and can't be loaded by the client class loader.

The following topics are addressed here:

* xref:#GSESG00026[To Use the EJB 3.1 Embeddable API with Embedded {productName}]
* xref:#GSESG00063[EJB 3.1 Embeddable API Properties]
* xref:#GSESG00064[Using Maven with the EJB 3.1 Embeddable API and Embedded
{productName}]

[[GSESG00026]][[to-use-the-ejb-3.1-embeddable-api-with-embedded-glassfish-server]]

=== To Use the EJB 3.1 Embeddable API with Embedded {productName}

1. To specify {productName} as the Container Provider, include
`glassfish-embedded-static-shell.jar` or `glassfish-embedded-all.jar` in
the class path of your embeddable EJB application.
+
Reference the `glassfish-embedded-static-shell.jar` file from the
as-install``/lib/embedded`` directory of a {productName} installation.
Do not move this file or it will not work.
+
See xref:#setting-the-class-path[Setting the Class Path] and Section 22.3.3 of the EJB
3.1 Specification, Embeddable Container Bootstrapping.
2. Configure any required resources.
+
For more information about configuring resources, see the Administration
Console Online Help or "xref:administration-guide.adoc#part-ii[Resources and Services
Administration]" in {productName} Administration
Guide. The `jdbc/__default` Java DB database is preconfigured with all
distributions of {productName}. However, if you are using
`glassfish-embedded-static-shell.jar`, you must start the database
manually.
+
If your embeddable EJB application uses Java Persistence, you do not
need to specify a JDBC resource. See xref:#default-java-persistence-data-source-for-embedded-glassfish-server[Default Java
Persistence Data Source for Embedded {productName}].
3. Invoke one of the `createEJBContainer` methods.
+

[NOTE]
====
Do not deploy your embeddable EJB application or any of its dependent
Jakarta EE modules before invoking one of the `createEJBContainer` methods.
These methods perform deployment in the background and do not load
previously deployed applications or modules.
====

4. To change the xref:#instance-root-directory[Instance Root Directory], set the
`org.glassfish.ejb.embedded.glassfish.instance.root` system property
value by using the `createEJBContainer``(Map<?, ?> properties)` method.
+
The default xref:#instance-root-directory[Instance Root Directory] location is
as-install``/domains/domain1`` if a nonembedded installation is
referenced. This system property applies only to embeddable EJB
applications used with nonembedded {productName}.
5. Close the EJB container properly to release all acquired resources
and threads.

[[GSESG00063]][[ejb-3.1-embeddable-api-properties]]

=== EJB 3.1 Embeddable API Properties

Properties that can be passed to the
`EJBContainer#createEJBContainer(Properties)` method are summarized in
the following table. All properties are in the
`org.glassfish.ejb.embedded.glassfish` package. For example, the full
name of the `installation.root` property is
`org.glassfish.ejb.embedded.glassfish.installation.root`.

[[gksop]]

Table 1-11 EJB 3.1 Embeddable API Properties

[width="100%",cols="<30%,<39%,<31%",options="header",]
|===
|Property |Default |Description
|`installation.root` |{productName} installation location from which
`glassfish-embedded-static-shell.jar` is referenced |The
xref:#installation-root-directory[Installation Root Directory].

|`instance.root` a|
In order of precedence:

* `glassfish.embedded.tmpdir` property value specified in
`GlassFishProperties` object
* `glassfish.embedded.tmpdir` system property value
* `java.io.tmpdir` system property value
* as-install``/domains/domain1`` if a nonembedded installation is referenced

 |The xref:#instance-root-directory[Instance Root Directory].

|`configuration.file` |domain-dir`/config/domain.xml` |The configuration
file.

|`keep-temporary-files` |`false` |If `true`, keeps temporary files
(exploded EAR file and configuration file) created by the embedded EJB
container when Embedded {productName} is stopped.

|`web.http.port` |None |Enables the web container if set. Needed for
testing web services in a WAR file. The value is ignored and can be an
empty string.

|`instance.reuse` |`false` |If `true`, no changes are made to the
existing configuration file, and a temporary server instance is not
created for the embedded run. Instead, execution happens against the
existing server instance. Do not use this option if the reused server
instance could be in use by the running nonembedded {productName}.

|`skip-client-modules` |`false` |If `true`, omits modules from the
classpath if they are not specified using `EJBContainer.MODULES` and
have a manifest file with a `Main-Class` attribute.
|===


[[GSESG00064]][[using-maven-with-the-ejb-3.1-embeddable-api-and-embedded-glassfish-server]]

=== Using Maven with the EJB 3.1 Embeddable API and Embedded {productName}

When using Maven with the EJB 3.1 Embeddable API and Embedded {productName}, you cannot use the features of the Maven plug-in. You must start
and stop Embedded {productName} manually or programmatically outside
of Maven.

[[gjxds]]
Example 1-14 Maven POM File for Using the EJB 3.1 Embeddable API with
Embedded {productName}

This example shows a POM file for configuring Maven to use the EJB 3.1
Embeddable API with Embedded {productName}.

[source,xml]
----
<!--
Line breaks in the following element are for readability purposes only
-->
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.glassfish</groupId>
    <artifactId>my-ejb-app-tester</artifactId>
    <version>3.1</version>
    <name>Maven test</name>
    <dependencies>
        <dependency>
            <groupId>org.glassfish.extras</groupId>
            <artifactId>glassfish-embedded-static-shell</artifactId>
            <version>${project.version}</version>
            <scope>system</scope>
            <systemPath>
                ${env.S1AS_HOME}/lib/embedded/glassfish-embedded-static-shell.jar
            </systemPath>
        </dependency>
<!--
        The javaee-api is stripped of any code and is just used to compile your
        application. The scope provided in Maven means that it is used for compiling,
        but is also available when testing. For this reason, the javaee-api needs to
        be below the embedded Glassfish dependency. The javaee-api can actually be
        omitted when the embedded Glassfish dependency is included, but to keep your
        project Java-EE 6 rather than GlassFish 3, specification is important.
-->
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>6.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <pluginRepositories>
        <pluginRepository>
            <id>maven2-repository.dev.java.net</id>
            <name>Java.net Repository for Maven</name>
            <url>http://download.java.net/maven/glassfish/</url>
        </pluginRepository>
    </pluginRepositories>
</project>
----

If you are using `glassfish-embedded-static-shell.jar`, you can omit the
`dependency` element with the `javaee-api` `artifactId` and the
`pluginRepositories` element.

Set the `S1AS_HOME` environment variable to the installation root
directory before running the `mvn clean verify` command.

[[changing-log-levels-in-embedded-glassfish-server]]

== Changing Log Levels in Embedded {productName}

To change log levels in Embedded {productName}, you can follow the
steps in this section or you can use the Embedded Server API as shown in
xref:#gjlfm[Example 1-11]. For more information about {productName}
logging, see "xref:administration-guide.adoc#administering-the-logging-service[Administering the Logging Service]" in
{productName} Administration Guide.

You can change log levels in Embedded {productName} in either of the
following ways:

* Using the {productName} Embedded Server API
* Creating a custom logging configuration file

Both these ways use logger names. For a list of logger names, use the
xref:reference-manual.adoc#list-log-levels[`list-log-levels`] subcommand.

[[gkrhh]]
Example 1-15 Using the {productName} Embedded Server API

This example shows how to set log levels using the `getLogger` method in
the API.

[source,java]
----
import org.glassfish.embeddable.*;

// Create Embedded GlassFish
GlassFish glassfish = GlassFishRuntime.bootstrap().newGlassFish();

// Set the log levels. For example, set 'deployment' and 'server' log levels to FINEST
Logger.getLogger("").getHandlers()[0].setLevel(Level.FINEST);
Logger.getLogger("jakarta.enterprise.system.tools.deployment").setLevel(Level.FINEST);
Logger.getLogger("jakarta.enterprise.system").setLevel(Level.FINEST);

// Start Embedded GlassFish and deploy an application.
// You will see all the FINEST logs printed on the console.
glassfish.start();
glassfish.getDeployer().deploy(new File("sample.war"));

// Dispose Embedded GlassFish
glassfish.dispose();
----

[[gkrgw]]
Example 1-16 Creating a Custom Logging Configuration File

This example shows the contents of a custom logging configuration file,
`customlogging.properties`.

[source]
----
handlers= java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = FINEST
jakarta.enterprise.system.tools.deployment.level = FINEST
jakarta.enterprise.system.level = FINEST
----

Pass the name of this custom logging configuration file to the `java`
command when you invoke Embedded {productName}. For example:

[source]
----
java -Djava.util.logging.config.file=customlogging.properties MyEmbeddedGlassFish
----

[[default-java-persistence-data-source-for-embedded-glassfish-server]]

== Default Java Persistence Data Source for Embedded {productName}

The `jdbc/__default` Java DB database is preconfigured with Embedded
{productName}. It is used when an application is deployed in Embedded
{productName} that uses Java Persistence but doesn't specify a data
source. Embedded {productName} uses the embedded Java DB database
created in a temporary domain that is destroyed when Embedded {productName} is stopped. You can use a Java DB database configured with
nonembedded {productName} if you explicitly specify the instance root
directory or the configuration file.

By default, weaving is enabled when the {productName} Embedded Server
API is used. To disable weaving, set the
`org.glassfish.persistence.embedded.weaving.enabled` property to
`false`.

[[restrictions-for-embedded-glassfish-server]]

== Restrictions for Embedded {productName}

The `glassfish-embedded-web.jar` file for embedded {productName}
supports only these features of nonembedded {productName}:

* The following web technologies of the Jakarta EE platform:

** Java Servlet API

** Java Server Pages (JSP) technology

** Java Server Faces technology
* JDBC-technology connection pooling
* Java Persistence API
* Java Transaction API
* Java Transaction Service

The `glassfish-embedded-all.jar` and
`glassfish-embedded-static-shell.jar` files support all features of
nonembedded {productName} with these exceptions:

* Installers
* Administration Console
* Update Tool
* Apache Felix OSGi framework
* The Maven plug-in for embedded {productName} does not support
application clients.
* Applications that require ports for communication, such as remote EJB
components, do not work with the EJB 3.1 Embeddable API running with
embedded {productName} if a nonembedded {productName} is running
in parallel.

Embedded {productName} requires no installation or configuration. As
a result, the following files and directories are absent from the file
system until embedded {productName} is started:

* `default-web.xml` file
* `domain.xml` file
* Applications directory
* Instance root directory

When embedded {productName} is started, the base installation
directory that {productName} uses depends on the options with which
{productName} is started. If necessary, embedded {productName}
creates a base installation directory. Embedded {productName} then
copies the following directories and their contents from the Java
archive (JAR) file in which embedded {productName} is distributed:

* `domains`
* `lib`

If necessary, {productName} also creates an instance root directory.
